### ISSUE TITLE
[css-grid] Support named lines

### ISSUE THREAD

**Issue by evgeny-petukhov** [postcss/autoprefixer#1020]
Now names lines are skipped when processing `grid-template`:
```css
.wrapper {
  display: grid;
  grid-template-columns: [main-start] 1fr [content-start] 1fr [content-end] 1fr [main-end];
  grid-template-rows: [main-start] 100px [content-start] 100px [content-end] 100px [main-end];
}

.box1 {
  grid-column-start: main-start;
  grid-row-start: main-start;
  grid-row-end: main-end;
}

.box2 {
  grid-column-start: content-end;
  grid-row-start: main-start;
  grid-row-end: content-end;
}

.box3 {
  grid-column-start: content-start;
  grid-row-start: main-start;
}

.box4 {
  grid-column-start: content-start;
  grid-column-end: main-end;
  grid-row-start: content-end;
}
```
Example with repeat
```css
.wrapper {
  display: grid;
  grid-template-columns: repeat(6, [col1-start] 1fr [col2-start] 3fr);
}

.item1 {
  grid-column: col1-start / col2-start 2
}

.item2 {
  grid-row: 2;
  grid-column: col1-start 2 / span 2 col1-start;
}
```

Description and more examples here https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Layout_using_Named_Grid_Lines

**Comment by evgeny-petukhov** [comment]
I think it has very low priority, but it's interesting and real case. It's would be cool to have some voting about such features to understand are they really useful for users.

**Comment by Dan503** [comment]
It would be a nice to have but not essential. I find it much easier to use grid areas instead.

**Comment by Dan503** [comment]
This comment on the css-working-group issue tracker gave an interesting use case
https://github.com/w3c/csswg-drafts/issues/2270#issuecomment-388222647

````css
.grid {
  grid-template-rows: [start] repeat(2, repeat(2, repeat(3, minmax(0,1fr) [small]) [medium]) [large] [half]) [end]; 
}

.small { grid-column-end: span small; }
.medium { grid-column-end: span medium }
.large { grid-column-end: span large }
.half { grid-column-end: span half }
.full { grid-column-start: start; grid-column-end: end; }
````

It's a bit of a monster. I thought I would post it here as an interesting super complicated test case for this issue.
