### ISSUE TITLE
[css-grid] Unprefix gap properties

### ISSUE THREAD

**Issue by evgeny-petukhov** [postcss/autoprefixer#1021]
Prefix unprefixed gap properties for CSS Grid Layout
## Refs
https://github.com/w3c/csswg-drafts/issues/1696
https://blogs.igalia.com/mrego/2018/04/04/getting-rid-of-grid-prefix-on-css-grid-layout-gutter-properties/
## New properties:
* `gap` -> `grid-gap`
* `column-gap` -> `grid-column-gap`
* `row-gap` -> `grid-row-gap`
## Example
```css
.foo {
  gap: 20px;
}
/* output */
.foo {
  grid-gap: 20px;
  gap: 20px;
}
```
## Problems
`column-gap` is also used for Columns Layout
