### ISSUE TITLE
[css-grid] translate `grid` property syntax into IE safe syntax when possible

### ISSUE THREAD

**Issue by Dan503** [postcss/autoprefixer#1023]
This code

````css
.grid {
    display: grid;
    grid:
      "left .... right" 100px /
       1fr  10px   1fr;
}

.left-cell { grid-area: left; }

.right-cell { grid-area: right; }
````

Should translate into this:

````css
.grid {
  display: -ms-grid;
  display: grid;
  -ms-grid-columns: 1fr 10px 1fr;
  -ms-grid-rows: 100px;
  grid:
      "left .... right" 100px /
       1fr  10px   1fr;
}

.left-cell {
  -ms-grid-row: 1;
  -ms-grid-column: 1;
  grid-area: left;
}

.right-cell {
  -ms-grid-row: 1;
  -ms-grid-column: 3;
  grid-area: right;
}
````

**Comment by ai** [comment]
What is your current output?

**Comment by Dan503** [comment]
It doesn't attempt to translate it at all so the output is what I put it

````css
/* what autoprefixer outputs even if the grid setting is turned on */

.grid {
  display: -ms-grid;
  display: grid;
  grid: "left .... right" 100px /
 1fr  10px   1fr;
}

.left-cell {
  grid-area: left;
}

.right-cell {
  grid-area: right;
}
````
