### ISSUE TITLE
`Stretch vs fill-available` warning doesn't make sense

### ISSUE THREAD

**Issue by josh-degraw** [postcss/autoprefixer#1035]
I'm having a hard time regarding #784. According to [caniuse.com](https://caniuse.com/#feat=intrinsic-width), no major browser actually seems to support this yet. At first it looks like chrome does, but in the footnotes it states 

> Chrome does not yet unprefix stretch (aka fill/fill-available), because the [CSSWG](https://lists.w3.org/Archives/Public/www-style/2015Aug/0127.html) is not ready for that yet. [See Chromium bug](https://chromium.googlesource.com/chromium/blink.git/+/bf119cdfece210e69c9a99af06f1b9981e2a1bc2)

and it states that Firefox only supports it with a prefix, yet

> Firefox currently supports the -moz-available property rather than -moz-stretch

Messing around in both browsers shows me that it doesn't work in either.

My question / issue here is simply that the warnings generated for when I set any or all of the following:

```scss
.element {
    max-width: fill-available;
    max-width: -webkit-fill-available;
    max-width: -moz-available;
}
```
I get the warning _(even if I'm using the prefixed version already)_

```
Replace fill-available to stretch, because spec had been changed
```

but this warning is, as far as I can tell, both unnecessary and invalid. I searched around for a way to just silence the warning, but in #473 it seems that it was decided not to have a way to suppress warnings, and since I'm using Create React App in this project, it's not as simple to just wire up the plugin as was suggested in  #473 _(unless I'm just not doing it right, which is definitely a possibility)_.

So now, if i set

```scss
.element {
    max-width: fill-available;
}
```

the output is unchanged, and I get the above warning, when it still seems to me like it should still add the prefixed versions and not show any warnings. 

It may be a minor issue, and mostly just annoying, but it still seems to me to be a problem that should be addressed. To me, this is a prime example of why having a way to suppress warnings (like with eslint-style comments, etc.) has merits. 

If I have any of this incorrect, please let me know.

**Comment by ai** [comment]
Your CSS input must be:

```css
.element {
    max-width: stretch;
}
```

Autoprefixer will compile it to:

```css
.element {
    max-width: -webkit-fill-available;
    max-width: -moz-available;
    max-width: stretch;
}
```

So Chrome/Firefox will get their custom values.
