### ISSUE TITLE
[css-grid] Report a warning if duplicate area names are detected

### ISSUE THREAD

**Issue by Dan503** [postcss/autoprefixer#1038]
Take this css:

````css
.grid-alpha {
  grid-template-areas: "delta  echo";
}

.grid-beta {
  grid-template-areas: "echo  delta";
}

.grid-cell {
  -ms-grid-column: ???; /* what column does .grid-cell go in? */
  arid-area: echo;
}
````

Autoprefixer has no access to the DOM so it doesn't really know what area `.grid-cell` belongs to.

Currently Autoprefixer silently just goes with whatever the last `grid-template-areas` definition was in the style-sheet (in this case `"echo  delta"`). If a user places `.grid-cell` in `.grid-alpha` then it will look great in modern browsers but be placed in the wrong column in IE.

Since it is silent, a user could end up building their whole site blissfully unaware of this issue, using duplicate area names everywhere, then finally open IE to see their whole layout go to shit.

Autoprefixer should detect if there are any area name conflicts and if so, warn users to use unique area names at all times.

**Comment by evgeny-petukhov** [comment]
Good suggestion! I think we can do it.

**Comment by Dan503** [comment]
Oh I just realised that you will need to be careful not to trigger false positives on media queries.

This code would be valid:

````css
.grid {
  display: grid;
  grid-gap: 10px;
  grid-template:
    "a   b" 100px
    "c   d" 100px
    "e   f" 100px /
    1fr  1fr;
}

@media (min-width: 600px){
  .grid {
    grid-template-areas:
      "a   b   c"
      "d   e   f";
    grid-template-columns: repeat(3, 1fr);
    grid-template-rows: repeat(2, 100px);
  }
}

.cell-A {
  grid-area: a;
}

.cell-B {
  grid-area: b;
}

.cell-C {
  grid-area: c;
}

.cell-D {
  grid-area: d;
}
````
