### ISSUE TITLE
[css-grid] Bug when specifying two values for grid-gap

### ISSUE THREAD

**Issue by yuheiy** [postcss/autoprefixer#1044]
Test case:

```css
.a-two {
    grid-gap: 2rem 1rem;
    grid-template-rows: 1fr minmax(100px, 1fr) 2fr;
    grid-template-columns: repeat(3, 1fr);
    grid-template-areas:
        "head-two head-two head-two"
        "nav-two  main-two main-two"
        "nav-two  foot-two foot-two";
}
```

Expected:

```css
.a-two {
    grid-gap: 2rem 1rem;
    -ms-grid-rows: 1fr 2rem minmax(100px, 1fr) 2rem 2fr;
    grid-template-rows: 1fr minmax(100px, 1fr) 2fr;
    -ms-grid-columns: 1fr 1rem 1fr 1rem 1fr;
    grid-template-columns: repeat(3, 1fr);
    grid-template-areas:
        "head-two head-two head-two"
        "nav-two  main-two main-two"
        "nav-two  foot-two foot-two";
}
```

Actual:

```css
.a-two {
    grid-gap: 2rem 1rem;
    -ms-grid-rows: 1fr 2rem 1rem minmax(100px, 1fr) 2rem 1rem 2fr;
    grid-template-rows: 1fr minmax(100px, 1fr) 2fr;
    -ms-grid-columns: 1fr 2rem 1rem 1fr 2rem 1rem 1fr;
    grid-template-columns: repeat(3, 1fr);
    grid-template-areas:
        "head-two head-two head-two"
        "nav-two  main-two main-two"
        "nav-two  foot-two foot-two";
}
```
