### ISSUE TITLE
[css-grid] grid-gap is depracated

### ISSUE THREAD

**Issue by yepninja** [postcss/autoprefixer#1046]
https://developer.mozilla.org/en-US/docs/Web/CSS/grid-gap
https://drafts.csswg.org/css-grid/#change-2016-grid-gap

`grid-gap` is already deprecated (renamed to `gap`). It's would be also good to handle `gap` property.

**Comment by ai** [comment]
Autoprefixer is only about prefixes. We can generate `-ms-` from `gap`, but not `grid-gap`.

**Comment by yepninja** [comment]
It's not about adding prefixes to `gap`. It's about latest release (the feature of adding empty tracks when `grid-gap` and `grid-template-areas` detected). Now we handle only for `grid-gap`.

**Comment by ai** [comment]
Yeap, we need to support `gap` in this case too.

**Comment by ai** [comment]
Closed by https://github.com/postcss/autoprefixer/pull/1054

**Comment by JLHwung** [comment]
> Autoprefixer is only about prefixes. We can generate -ms- from gap, but not grid-gap.

FYI I just write a plugin that generates `grid-gap` from `gap`: https://github.com/JLHwung/postcss-gap-grid-prefix

**Comment by Dan503** [comment]
@ai found the old `grid-gap` deprecation issue.

The comments in this issue suggest that it has been fixed in v8.6 but when I tried on https://autoprefixer.github.io/ (v9.7.3) gap isn't getting prefixed with `grid-gap` ☹

https://github.com/tailwindcss/tailwindcss/pull/1274#issuecomment-568933942

**Comment by ai** [comment]
@Dan503 sorry, I have too many open-source tasks today. Can you help me? What is input CSS, what is current warnings and what is expected warnings?

**Comment by yepninja** [comment]
@Dan503 This issue [is not about prefixing](#issuecomment-389497145) `gap` property with `grid` prefix. It's about support of `gap` property as `grid-gap` when calculating tracks for `IE`.

For example:
```css
.example {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 10px;
}
```
transpiles to:
```css
.example {
    display: -ms-grid;
    display: grid;
    -ms-grid-columns: 1fr 10px 1fr;
    grid-template-columns: 1fr 1fr;
    gap: 10px;
}
```

If you want to transpile `gap` to `grid-gap`, you should use [postcss-gap-properties](https://github.com/jonathantneal/postcss-gap-properties), which is a part of [postcss-preset-env](https://preset-env.cssdb.org/features#gap-properties)
