### ISSUE TITLE
4- & 8-digit hex

### ISSUE THREAD

**Issue by MrGrigri** [postcss/autoprefixer#1051]
Add support for 4- and 8-digit hex codes. There are a couple of [browsers](https://caniuse.com/#feat=css-rrggbbaa) that don't quite support it yet...mainly IE. 😢 

#RRGGBBAA or #RGBA is the style.

Rxample:

```CSS
body {
    color: #000000DE; /* rgba(0, 0, 0, 0.87) */
    background-color: tomato;
}
```
