### ISSUE TITLE
Autoprefixer outputting unsafe IE [column/row] [end/span] syntax

### ISSUE THREAD

**Issue by Dan503** [postcss/autoprefixer#1064]
The following CSS grid combinations are outputting unsafe IE code:

Input:
````css
.xxx {
  /* IE can't span backwards and Autoprefixer doesn't know the end value */
  grid-column-start: span 6;
}

.yyy {
  /* IE can't do "end" and Autoprefixer doesn't know the start value */
  grid-column-end: 3;
}
````

Output

````css
.xxx {
  /* -ms-grid-column: span 6; is invalid css in IE */
  -ms-grid-column: span 6;
      grid-column-start: span 6;
}
.yyy {
  /* -ms-grid-column-span: 3; != grid-column-end: 3; */
  -ms-grid-column-span: 3;
  grid-column-end: 3;
}
````

My recommendation is to not output any code when using those combinations and issue a warning to the user that Autoprefixer can't translate that code.
