### ISSUE TITLE
grid-column: span X; can be translated safely

### ISSUE THREAD

**Issue by Dan503** [postcss/autoprefixer#1065]
input
```css
.grid-cell {
  grid-column: span 6;
}
```
expected output
```css
.grid-cell {
  -ms-grid-column-span: 6;
  grid-column: span 6;
}
```
current output: (and it warns you not to use this syntax)
```css
.grid-cell {
  grid-column: span 6;
}
```

**Comment by Dan503** [comment]
@bogdan0083 Thanks for all the awesome work you've been doing. :)

How do you feel about fixing this one?

I don't imagine it would be that difficult to fix.

**Comment by bogdan0083** [comment]
> Thanks for all the awesome work you've been doing. :)

@Dan503 I'm happy to help :). Your reviews were extremely helpful, thank you for that too 😄 

> How do you feel about fixing this one?

It's not a big of a problem to fix this. I'll see what I can do 👍

**Comment by bogdan0083** [comment]
Fixed here: #1090

**Comment by Dan503** [comment]
I should have included this in the original issue

input

```css
.grid-cell {
  grid-column: span 2;
  grid-row: span 2;
}
```

expected output

```css
.grid-cell {
  -ms-grid-column-span: 2;
  grid-column: span 2;
  -ms-grid-row-span: 2;
  grid-row: span 2;
}
```
