### ISSUE TITLE
TypeError: gridArea.parent.after is not a function

### ISSUE THREAD

**Issue by Dan503** [postcss/autoprefixer#1072]
I wrote this (simplified) grid code:

````css
@media (min-width: 960px) {
  .grid {
    display: grid;
    grid-template:
      "............ .. feature_img" minmax(20px, 1fr)
      "feature_head .. feature_img"
      "feature_text .. feature_img"
      "feature_link .. feature_img"
      "............ .. feature_img" minmax(20px, 1fr) /
        3fr      5%     4fr;
  }
}
.img { grid-area: feature_img; }
.head { grid-area: feature_head; }
.text { grid-area: feature_text; }
.link { grid-area: feature_link; }

````
And received this error:
````
TypeError: gridArea.parent.after is not a function
    at C:\xxxxxxxxx\node_modules\autoprefixer\lib\hacks\grid-utils.js:351:33
    at C:\xxxxxxxxx\node_modules\postcss\lib\container.es6:164:28
    at C:\xxxxxxxxx\node_modules\postcss\lib\container.es6:110:26
    at Rule.each (C:\xxxxxxxxx\node_modules\postcss\lib\container.es6:78:22)
    at Rule.walk (C:\xxxxxxxxx\node_modules\postcss\lib\container.es6:109:21)
    at C:\xxxxxxxxx\node_modules\postcss\lib\container.es6:112:32
    at Root.each (C:\xxxxxxxxx\node_modules\postcss\lib\container.es6:78:22)
    at Root.walk (C:\xxxxxxxxx\node_modules\postcss\lib\container.es6:109:21)
    at Root.walkDecls (C:\xxxxxxxxx\node_modules\postcss\lib\container.es6:162:25)
    at insertAreas (C:\xxxxxxxxx\node_modules\autoprefixer\lib\hacks\grid-utils.js:317:17)
````

Also occurs if I write code like this:

````css
.grid {
  display: grid;
  grid-template:
    "............ .. feature_img" minmax(20px, 1fr)
    "feature_head .. feature_img"
    "feature_text .. feature_img"
    "feature_link .. feature_img"
    "............ .. feature_img" minmax(20px, 1fr) /
      3fr      5%     4fr;
}

@media (max-width: 960px) {
  .grid {
    grid-template:
      "feature_img"
      "feature_head"
      "feature_text"
      "feature_link" /
      1fr;
  }
}

.img { grid-area: feature_img; }
.head { grid-area: feature_head; }
.text { grid-area: feature_text; }
.link { grid-area: feature_link; }
````

(PS. Autoprefixer grid article comes out on Wednesday and I praise the grid area functionality a lot in it)

**Comment by Dan503** [comment]
I'm working around this at the moment by turning off autoprefixer in the max-width media query
```css
@media (max-width: 960px) {
  /* autoprefixer: off */
  .grid {
    grid-template:
      "feature_img"
      "feature_head"
      "feature_text"
      "feature_link" /
      1fr;
  }
}
```
