### ISSUE TITLE
@supports 

### ISSUE THREAD

**Issue by jonathantneal** [postcss/autoprefixer#1073]
Autoprefixer automatically clones `width: fit-content` as `width: -moz-fit-content`. If this is done automatically, I think the respective `@supports` query should be prefixed automatically as well. This would change a query such as:

```css
@supports not (width: fit-content) {}
```

Into the following query (depending upon the browserslist):

```css
@supports not ((width: -moz-fit-content) or (width: -webkit-fit-content) or (width: fit-content)) {}
```

I would think this should apply to all automatically prefixed declarations.

**Comment by ai** [comment]
It should works. Check Autoprefixer version

**Comment by jonathantneal** [comment]
@ai, are you sure of this? Test the following CSS at https://preset-env.cssdb.org/playground

```css
@supports (fit-content) {
  dialog {
    width: fit-content;
  }
}
```

That CSS becomes:

```css
@supports (fit-content) {
  dialog {
    width: -webkit-fit-content;
    width: fit-content;
  }
}
```
