### ISSUE TITLE
[css-grid] Idea on how to 100% support duplicate area names

### ISSUE THREAD

**Issue by Dan503** [postcss/autoprefixer#1091]
I've realized a use case where duplicate area names makes sense.

```html
<div class="grid">
  <div class="grid-cell a"></div>
  <div class="grid-cell b"></div>
</div>

<!-- I want this to have a slightly different layout. -->
<!-- It is the same component but this time with a modifier class on it -->
<div class="grid conflict">
  <div class="grid-cell a"></div>
  <div class="grid-cell b"></div>
</div>
```
Input CSS
```css
.grid {
  display: grid;
  grid-template-areas:
    "a b";
}

.grid.conflict {
  display: grid;
  grid-template-areas:
    "a"
    "b";
}

.a { grid-area: a; }
.b { grid-area: b; }
```

Current Output CSS (and it warns the user that there is a duplicate area name in rule `.grid.conflict`)
```css
.grid {
  display: -ms-grid;
  display: grid;
  grid-template-areas: "a b";
}

.grid.conflict {
  display: -ms-grid;
  display: grid;
  grid-template-areas:
    "a"
    "b";
}

.a {
  -ms-grid-row: 1;
  -ms-grid-column: 1;
  grid-area: a;
}

.b {
  -ms-grid-row: 2;
  -ms-grid-column: 1;
  grid-area: b;
}
```

This is my proposed output idea:

```css
.grid {
  display: -ms-grid;
  display: grid;
  grid-template-areas: "a b";
}

.grid.conflict {
  display: -ms-grid;
  display: grid;
  grid-template-areas:
    "a"
    "b";
}

/* It uses the first area by default */
.a {
  -ms-grid-row: 1;
  -ms-grid-column: 1;
  grid-area: a;
}
.b {
  -ms-grid-row: 1;
  -ms-grid-column: 2;
  grid-area: b;
}

/* It has detected a conflict, it now prefixes with the conflicting grid selector */
.grid.conflict > .a {
  -ms-grid-row: 1;
  -ms-grid-column: 1;
}
.grid.conflict > .b {
  -ms-grid-row: 2;
  -ms-grid-column: 1;
}
```

This is what we know purely from looking at the CSS and knowing how CSS Grid works:
- A grid cell _must_ be a direct descendant of the parent grid container that controls it in the HTML for CSS Grid to work.
- `.grid.conflict > .a` will only work on `.a` elements that have been placed _directly_ inside a `.grid.conflict` element.
- `.grid.conflict > .a` will have no effect on `.a` elements inside `.grid` elements.
- `.grid.conflict > .a` will have no effect on `.a` elements nested deeply inside `.grid.conflict` elements.

If we create these additional prefixed rules with `[grid-selector] >` I think we can pretty safely support duplicate area names without having to give out a warning.

There is a danger in that we are increasing the rule specificity. I think specificity issues will be easier to work around than trying to work around not being able to use duplicate area names though.

For example, you could work around the specificity issue by writing a rule like `.grid > .a { grid-area: a; }` instead of just `.a { grid-area: a; }`.

**Comment by Dan503** [comment]
This is how I think media queries should be handled.

Input CSS

```css
.grid {
  display: grid;
  grid-template-areas: "a b";
}

@media (max-width: 600px) {
  .grid {
    grid-template-areas:
      "a"
      "b";
  }
}

.grid.conflict {
  display: grid;
  grid-template-areas:
    "a"
    "b";
}

@media (min-width: 601px) {
  .grid.conflict {
    grid-template-areas: "a b";
  }
}

.a {
  grid-area: a;
}

.b {
  grid-area: b;
}
```

My idea for output CSS:

```css

.grid {
  display: -ms-grid;
  display: grid;
  grid-template-areas: "a b";
}

@media (max-width: 600px) {
  .grid {
    grid-template-areas:
      "a"
      "b";
  }
}

.grid.conflict {
  display: -ms-grid;
  display: grid;
  grid-template-areas:
    "a"
    "b";
}

@media (min-width: 601px) {
  .grid.conflict {
    grid-template-areas: "a b";
  }
}

.a {
  -ms-grid-row: 1;
  -ms-grid-column: 1;
  grid-area: a;
}

.b {
  -ms-grid-row: 1;
  -ms-grid-column: 2;
  grid-area: b;
}

@media (max-width: 600px) {
  .a {
    -ms-grid-row: 1;
    -ms-grid-column: 1;
  }
  .b {
    -ms-grid-row: 2;
    -ms-grid-column: 1;
  }
}

.grid.conflict > .a {
  -ms-grid-row: 1;
  -ms-grid-column: 1;
}

.grid.conflict > .b {
  -ms-grid-row: 2;
  -ms-grid-column: 1;
}

@media (min-width: 601px) {
  .grid.conflict > .a {
    -ms-grid-row: 1;
    -ms-grid-column: 1;
  }
  .grid.conflict > .b {
    -ms-grid-row: 1;
    -ms-grid-column: 2;
  }
}
```

**Comment by bogdan0083** [comment]
Wow! This idea is looking awesome and it won't be much of a problem to implement it. I need to think about it in my spare time.

**Comment by Dan503** [comment]
Awesome! I wasn't sure how difficult it would be to fix.

If we could get this issue fixed then it would open up a whole world of new CSS Grid in IE possibilities! 🤩

**Comment by Dan503** [comment]
I might even write up a new article for CSS Tricks looking at the sorts of new possibilities that this opens up if we can get this implemented :)

**Comment by Dan503** [comment]
Two little snags that we need to handle:

If someone uses a selector that contains a space in it when declaring the grid area, this won't work.

```css
/* we can't support this */
.grand-parent .parent .child {
  grid-area: a;
}

/* 
We need to support this as a way for people to control specificity.
if ".grand-parent .grid" is an identical selector to the grid initializer, this should act like a replacement for our generated conflict resolution selector.
*/
.grand-parent .grid > .cell {
  grid-area: a;
}
```

**Comment by Dan503** [comment]
Oh I just realized that `display: contents;` is another thing that will cause issues.

```html
<div class="grid">
    <div class="display-contents-element">
        <div class="grid-cell a"></div>
        <div class="grid-cell b"></div>
    </div>
</div>
<div class="grid conflict">
    <div class="display-contents-element">
        <div class="grid-cell a"></div>
        <div class="grid-cell b"></div>
    </div>
</div>
```
```css
/* This allows the grid to ignore .display-contents-element */
.display-contents-element {
  display: contents;
}

.grid {
  display: grid;
  grid-template-areas:
    "a b";
}
.grid.conflict {
  display: grid;
  grid-template-areas:
    "a"
    "b";
}
.a { grid-area: a; }
.b { grid-area: b; }
```
```css
/* This will not work in this scenario */
.grid.conflict > .a {
  -ms-grid-row: 1;
  -ms-grid-column: 1;
}
.grid.conflict > .b {
  -ms-grid-row: 2;
  -ms-grid-column: 1;
}
```
To avoid this issue, I think if the `grid` setting is enabled we should just shout out a warning not to use `display: contents` if someone uses it.

We have no way of getting IE to replicate `display: contents` functionality so we will need to just warn users not to use it if they have the `grid` setting enabled.

**Comment by bogdan0083** [comment]
Thank you very much for the comments! They are really helpful and informative. I'm going to open WIP PR soon and we will work through every detail step by step :)

**Comment by Dan503** [comment]
> /* we can't support this */

Actually I'm thinking that if a user write this:

```css
.grand-parent .parent {
  display: grid;
  grid-template-areas: "a";
}
.grand-parent .parent .child {
  grid-area: a;
}
```
We should support that. We should treat that scenario the same way as if the user wrote this:
```css
.grand-parent .parent {
  display: grid;
  grid-template-areas: "a";
}
.grand-parent .parent > .child {
  grid-area: a;
}
```

**Comment by Dan503** [comment]
If someone writes something like this though:
```css
.grand-parent .parent {
  display: grid;
  grid-template-areas: "a";
}
.uncle .child {
  grid-area: a;
}
```
That should output a warning since the parent selector of the child doesn't match up with any of the grid initializer selectors.
