### ISSUE TITLE
Preserve indentation

### ISSUE THREAD

**Issue by sindresorhus** [postcss/autoprefixer#11]
A tab or 4 space indentation is converted to 2 spaces:

``` css
body {
    transition: all 1s ease-out;
}
```

```
body {
  -webkit-transition: all 1s ease-out;
  -o-transition: all 1s ease-out;
  transition: all 1s ease-out
}
```

This is important as people don't like tools mucking with their precious indentation.
