### ISSUE TITLE
autoprefixing css with php code

### ISSUE THREAD

**Issue by nikitasol** [postcss/autoprefixer#1106]
Hi,

I have this line of code, for example, that I am trying to autoprefix in Sublime:

```css
.price {
	    height: 10%;
	    top: 10px;
	    display: flex;
	    justify-content: center;
	    align-items: center;
	    opacity: 1;
	    font-size: 1.5em;
	    padding: 1em;
	    background-color: <?php echo CSS::getVar('price_tag') ?>;
	    transform: scaleY(1);
	    transition: all .3s ease-in;
}
```
As you can see there is a php echo for pulling the price_tag and it throws an error preventing the transform from being prefixed. This is the error:

>Autoprefixer
Error: 10:27: Missed semicolon

Is there a way for autoprefixer to ignore php code? Thanks!
