### ISSUE TITLE
[css-grid] Suppress IE warnings that are not relevant

### ISSUE THREAD

**Issue by mikkelwf** [postcss/autoprefixer#1110]
Hi

After updating to version 9.x (i've tried 9.0.2 and 9.1.3), I now get warnings for css-grid errors regarding IE (which is great btw).

One of them regards the use of `auto-fill`:

`grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));`

To make a fallback to IE i desided to just render the grid when auto-fill is supported, so i wrapped the code in `@supports`

```
  @supports (grid-template-columns: repeat(auto-fill, minmax(200px, 1fr))) {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
  }
```

However i still get the warning, even though IE never reaches the specific line, due to the `@supports`.
The warning is correct, but in context is wrong, and should not be shown to the user.

**Comment by Dan503** [comment]
You can use a control comment to work around the issue.

This will turn off autoprefixer for the whole block
```
  @supports (grid-template-columns: repeat(auto-fill, minmax(200px, 1fr))) {
    /* autoprefixer: off */
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
  }
```

or you can turn it off for individual lines

```
  @supports (grid-template-columns: repeat(auto-fill, minmax(200px, 1fr))) {
    /* autoprefixer: ignore next */
    display: grid;
    /* autoprefixer: ignore next */
    grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
  }
```

**Comment by ai** [comment]
I agree that we need to check parents for `@supports` before showing warning.

**Comment by ai** [comment]
But this issue could take week or more, so using control comments is a good idea for now

**Comment by mikkelwf** [comment]
I can live with the warnings for now, so its super if you consider this feature. :D

**Comment by ai** [comment]
I sent this task to our Cult of Martians

**Comment by Dan503** [comment]
Do you think we can extend this to not just suppress warnings but also suppress IE prefixes?

**Input CSS**
```css
.ie_grid {
  display: grid;
}

@supports (grid-gap: 0) {
  .modern_grid {
    display: grid;
  }
}
```

**current output CSS**

```css
.ie_grid {
  display: -ms-grid;
  display: grid;
}

@supports (grid-gap: 0) {
  .modern_grid {
    /* this prefix is pointless */
    display: -ms-grid;
    display: grid;
  }
}
```

**Expected output CSS**
```css
.ie_grid {
  display: -ms-grid;
  display: grid;
}

@supports (grid-gap: 0) {
  .modern_grid {
    display: grid;
  }
}
```
