### ISSUE TITLE
CSS Grid Not prefixing for `grid-area`

### ISSUE THREAD

**Issue by rodoabad** [postcss/autoprefixer#1113]
#     "autoprefixer": "^9.0.1"

https://github.com/rodoabad/automatic-palm-tree

```
// .browserlistrc
> 1%
last 2 versions
ie >= 11
```

```
// postcssrc
{
  "modules": true,
  "plugins": {
    "autoprefixer": {
      "grid": true
    },
    "postcss-modules": {
        "generateScopedName": "[path]_[name]__[local]"
    }
  }
}
```

```
// home.scss
.home {
  border: 1px solid darkseagreen;
  display: grid;

  grid-template-columns: 1fr 1fr; /* <--  IF THIS IS ABOVE grid-template-areas PREFIX IS NOT GENERATED */
  grid-template-rows: 1fr 1fr;/* <--  IF THIS IS ABOVE grid-template-areas PREFIX IS NOT GENERATED */
  grid-template-areas:
    'hello hello'
    'links links';
 }

:global {
  body,
  html {
   box-sizing: border-box;
  }
}
```

```
// links.scss
.links {
  border: 1px solid red;
  grid-area: links;
}
```

Generated (includes other styles I omitted).

```
.src-_anonymous__anonymous {
  border: 1px solid green; }
.src-_hello__hello {
  border: 1px solid deepskyblue;
  grid-area: hello; }
.src-_links__links {
  border: 1px solid red;
  grid-area: links; }
.src-_home__home {
  border: 1px solid darkseagreen;
  display: -ms-grid;
  display: grid;
  -ms-grid-columns: 1fr 1fr;
      grid-template-columns: 1fr 1fr;
  -ms-grid-rows: 1fr 1fr;
      grid-template-rows: 1fr 1fr;
  grid-template: 'hello hello' 'links links'; }

body,
html {
  box-sizing: border-box; }
.src-_restricted__restricted {
  border: 1px solid red; }
```

**Comment by rodoabad** [comment]
I've updated the issue and added comments. I've confirmed it on https://autoprefixer.github.io/

**Comment by ai** [comment]
@rodoabad you need to add some component with `grid-area: hello` and `grid-area: links`.

Autoprefixer will add properties to these components. Looks at the example here: https://gist.github.com/ai/a1426ec4ad404119467c391522cf32a7#file-autoprefixer72-grid-example-css-L13-L15

**Comment by rodoabad** [comment]
@ai instead of closing please allow me to reply first. Have you actually tried it on the autoprefixer page?

**Comment by rodoabad** [comment]
@ai have you tried and cloned the repo I posted? The autogenerated CSS does not include those prefixes.

https://github.com/rodoabad/automatic-palm-tree

```
$ npm i
$ npm run start
```

**Comment by ai** [comment]
@rodoabad can you give me direct link to CSS file with `grid-area` property?

**Comment by rodoabad** [comment]
https://github.com/rodoabad/automatic-palm-tree/blob/master/src/home.scss
https://github.com/rodoabad/automatic-palm-tree/blob/master/src/links.scss

**Comment by ai** [comment]
Don't worry, I will reopen issue if I found that it is a problem in the code. I close it because right now I am thinking that it is problem with input CSS.

Open/close status is a category system just for me. You will continue to get help no matter if open/close status.

**Comment by rodoabad** [comment]
![test](https://user-images.githubusercontent.com/1240667/45484402-95cb6380-b719-11e8-9e9d-4163ace1c900.PNG)

**Comment by rodoabad** [comment]
I've included the dependencies and how I'm using it. The window open on the far right is the auto generated CSS.

**Comment by ai** [comment]
Autoprefixer needs to see `grid-template` and `grid-area` properties in the single file (since there is no these properties in IE, we need to emulate container’s template by children row/column properties).

Or you can create `home_links` wrap to keep `grid-area` in Home component.

Try to run Autoprefixer after files concatination. Or move

**Comment by rodoabad** [comment]
That sort of defeats some of the purpose of using CSS modules (extracting CSS to other files). But I will try right now.

**Comment by rodoabad** [comment]
> Try to run Autoprefixer after files concatination. Or move

This is what I was thinking before I sleep last night as an extra step in our pipeline before we ship.

**Comment by ai** [comment]
> That sort of defeats some of the purpose of using CSS modules (extracting CSS to other files).

Absolutely agree. I prefer to have small components as well.

Also, maybe this thoughts would be interesting for you. The best components should be independent from each other. For instance, Links company should not know about it's parent (and could work in any parent). As result, it will be even better if both `grid-template` and `grid-area` will not know about each other 👍.

**Comment by rodoabad** [comment]
Yep. Hence the reason why they are in different files as I want them to be totally independent with one another.

👍

**Comment by rodoabad** [comment]
Looks like the best course of action is to run `autoprefixer` on the `dist` folder for this type of scenario.

**Comment by rodoabad** [comment]
Running `postcss-cli` with `-r` deplaces all the classes. Do you have any suggestions on how to approach this problem? @ai

**Comment by Dan503** [comment]
@roboabad have a read of this article I wrote

https://css-tricks.com/abem-useful-adaptation-bem/

A large portion of the article is dedicated to explaining context sensitive styles. I think context sensitive styles is the solution to the problem you are having.

**Comment by rodoabad** [comment]
@Dan503 are you suggesting BEM and CSS modules? I don't think this has anything to do with context sensitive styles though because you will still have that inherent problem of coupling (in this context) `home` and `links`. With CSS modules alone, we remove that coupling, with BEM we add it back.

**Comment by Dan503** [comment]
Read the article. The bit about context sensitive styles really should have been split off into a seperate article because the concept actually has nothing to do with BEM.

**Comment by rodoabad** [comment]
I've read it in its entirety before when it wa first published and I'm reading it again as we go through this conversation. I still do not understand how it will fix the inherent problem of coupling the styles.

It's the reason why `home` is just `home` and `links` is just `links` they are independent of one another. In theory `home` and `links` could both be atoms in the hierarchy.

```scss
.home {
  border: 1px solid darkseagreen;
  display: grid;

  grid-template-areas:
    'hello hello'
    'links links';

  grid-template-columns: 1fr 1fr;
  grid-template-rows: 1fr 1fr;
 }
```

```scss
.something-random { /* renamed */
  border: 1px solid red;
  grid-area: links;
}
```

I am not sure if we're on the same page here.

**Comment by Dan503** [comment]
You will need to do something like this:

Home.css
```
.home {
  grid-template-areas:
    'hello hello'
    'links links';
  /* other styles */
}
.home .links { grid-area: links }
```
Links.css
```
.links {
  /* links styles */
}
```

That way all the grid styles are contained in the one CSS file.

**Comment by rodoabad** [comment]
@Dan503, that's what we're trying to avoid. We do not want the styles to be on the same file.

**Comment by rodoabad** [comment]
For now let's omit `something-else.css` as we won't be doing that (due to that problem that you just mentioned).

Looking at your other example...

```
.home {
  grid-template-areas:
    'hello hello'
    'links links';
  /* other styles */
}
.home .links { grid-area: links }
```

```
.links {
  /* links styles */
}
```

With CSS modules, `.links` would probably be something like...

```
/* .links */
.src-_links__links {
  border: 1px solid red;
  grid-area: links; }

/* .home .links */
.src-_home__home .src-_home__links {
  -ms-grid-row: 2;
  -ms-grid-column: 1;
  -ms-grid-column-span: 2;
  grid-area: links; }
```



After CSS modules. As you can see, they are not compatible.

**Comment by rodoabad** [comment]
Right now I'm trying to run autoprefixer again on the generated file (it sort of fixes it) however the problem I'm having right now is it renames the classes. I don't see any option that says do not rename existing classes and only add prefixes.

**Comment by Dan503** [comment]
What happens if you do this?

home.css
```css
.home {
  grid-template-areas:
    'hello hello'
    'links links';
  /* other styles */
}
.links { grid-area: links }
```

Links.css
```css
.links {
  /* links styles */
}
```

Would that work?

I'm assuming that the HTML is able to have more than one class on it. If the HTML is forced to only accept one class... well you're kind of skewed 😕

**Comment by ai** [comment]
> Running postcss-cli with -r deplaces all the classes. Do you have any suggestions on how to approach this problem?

What do you mean by replaces?

**Comment by ai** [comment]
> that's what we're trying to avoid. We do not want the styles to be on the same file.

Why do you not like component isolation idea? It is core of CSS Modules.

To be completely isolated, child should not know about parent. So cold should not rely of parent’s `display: grid`.

**Comment by rodoabad** [comment]
Sorry I mean *replaces* but I think I know why. It's because I was using the same configuration when before compiling which meant that CSS modules was also turned on which in turn renamed the classes.

@ai I think your last quote was meant for another clip of text. Looks like it was more for @Dan503

**Comment by ai** [comment]
@rodoabad nope, it was for you. Right now your Links will work only if Home will have `display: grid`. It is not isolated components.

It will be better for isolation to:

```
.home
  .home_links
    .links
```

`.home` (with `grid-template`) and `.home_links` (with `grid-area`) will be defined in Home component. Link will be isolated from knowing it's parent. Everything will work without build process changes.

**Comment by rodoabad** [comment]
You would be generating a new hash if you do that. Unless you import what's in `/home` into `/links` then it's not completely isolated.

**Comment by rodoabad** [comment]
![test](https://user-images.githubusercontent.com/1240667/45515514-fbe1d600-b76d-11e8-84d0-346a8a9e95a6.PNG)

```css
.src-_anonymous__anonymous {
  border: 1px solid green; }
.src-_hello__hello {
  border: 1px solid deepskyblue;
  grid-area: hello; }
.src-_links__links {
  border: 1px solid red; }
.src-_home__home {
  border: 1px solid darkseagreen;
  display: -ms-grid;
  display: grid;
          grid-template-areas: 'hello hello' 'links links';
  -ms-grid-columns: 1fr 1fr;
  grid-template-columns: 1fr 1fr;
  -ms-grid-rows: 1fr 1fr;
  grid-template-rows: 1fr 1fr; }

.src-_home__home__links {
  -ms-grid-row: 2;
  -ms-grid-column: 1;
  -ms-grid-column-span: 2;
  grid-area: links; }

body,
html {
  -webkit-box-sizing: border-box;
          box-sizing: border-box; }
.src-_restricted__restricted {
  border: 1px solid red; }

```

```jsx
import {Link} from 'react-router-dom';
import React from 'react';
import {links} from './links.scss';

const linksList = [
  {
    label: 'Home',
    url: '/'
  },
  {
    label: 'Anonymous',
    url: '/anonymous'
  },
  {
    label: 'Restricted A',
    url: '/restricted-a'
  },
  {
    label: 'Restricted B',
    url: '/restricted-b'
  }
];

const Links = () => (
  <ul
    className={links}
    data-test='links'
  >
    {linksList.map((link) => (
      <li key={link.url}>
        <Link to={link.url}>{link.label}</Link>
      </li>
    ))}
  </ul>
);

export default Links;

```

```scss
.links {
  border: 1px solid red;
}
```

**Comment by ai** [comment]
Use `home_links` in Home.

```js
<div className={ styles.homeLinks }>
  <Links>
</div>
```

**Comment by rodoabad** [comment]
@ai AAAH. I see where you're getting at now. You want `home` to own that responsibility of placing where `Links` should be.

```diff
const Home = () => (
  <div className={home}>
    <Hello/>
+    <div className={home_links}>
      <Links/>
+    </div>
  </div>
);
```

Hmm. This will work but will add unnecessary elements but it should do the trick.

**Comment by Dan503** [comment]
Yes!!! Now you are getting it!

That is the idea I was trying to get across by pointing you to the article.

The parent component should always be the one in control of the child's layout inside the component.

The child should not be dependent on being inside a certain parent to work.

**Comment by rodoabad** [comment]
![1_ev2yqevqz6cpje3i5pdtsw](https://user-images.githubusercontent.com/1240667/45516140-d1911800-b76f-11e8-8b9a-3031670e4ca6.gif)

**Comment by Dan503** [comment]
Are you able to do this in react?

```
const Home = () => (
  <div className={home}>
    <Hello/>
    <Links className={home_links} />
  </div>
);
```
It wouldn't require the extra markup then.

**Comment by rodoabad** [comment]
Done! @Dan503 

```jsx
const Links = ({className}) => (
  <ul
    className={`${className} ${links}`} // Add external `className` declaration.
    data-test='links'
  >
    {linksList.map((link) => (
      <li key={link.url}>
        <Link to={link.url}>{link.label}</Link>
      </li>
    ))}
  </ul>
);

Links.propTypes = {
  className: PropTypes.string
};

Links.defaultProps = {
  className: ''
};

export default Links;
```

```jsx
const Home = () => (
  <div className={home}>
    <Hello/>
    <Links className={home__links}/>
  </div>
);
```

**Comment by Dan503** [comment]
If you also add a class to `<Hello/>` then you can place that in the layout using the same technique as you are using for `<Links/>`.

Also, theoretically, you shouldn't need to use BEM style classes here. That should be taken care of by CSS modules.

So this would be my final recommend markup:

```
const Home = () => (
  <div className={home}>
    <Hello className={hello}/>
    <Links className={links}/>
  </div>
);
```

**Comment by Dan503** [comment]
Maybe go back and read the context sensitive styles part of the ABEM article again now that you understand what we were trying to tell you.

It will probably make more sense or mean something different to you now.

Not all of it will be relevant to you since you are using CSS modules. The rules it puts in place for what styles to give the parent and what styles to give the child will be useful to you.

https://css-tricks.com/abem-useful-adaptation-bem/

**Comment by rodoabad** [comment]
Thank you for your patience @ai @Dan503 Let me know if there's anything else.

End result:

```scss
.home {
  border: 1px solid darkseagreen;
  display: grid;

  grid-template-areas:
    'hello hello'
    'links links';

  grid-template-columns: 1fr 1fr;
  grid-template-rows: 1fr 1fr;

  &Hello { /* if this element is inside this parent, apply these styles to it */
    grid-area: home;
  }

  &Links { /* if this element is inside this parent, apply these styles to it */
    grid-area: links;
  }
 }
```

```jsx
import {home, homeHello, homeLinks} from './home.scss';
import Hello from './hello';
import Links from './links';
import React from 'react';

const Home = () => (
  <div className={home}>
    <Hello className={homeHello}/>
    <Links className={homeLinks}/>
  </div>
);

export default Home;
```

```jsx
import PropTypes from 'prop-types';
import React from 'react';
import {hello} from './hello.scss';

const Hello = ({className}) => (
  <h1
    className={`${className} ${hello}`}
    data-test='hello'
  >

    {
      `${process.env.MESSAGE}, ${process.env.NAME}!` // eslint-disable-line no-process-env
    }
  </h1>
);

Hello.propTypes = {
  className: PropTypes.string
};

Hello.defaultProps = {
  className: ''
};

export default Hello;

```

```scss
.hello {
  border: 1px solid deepskyblue;
}
```

### Goals Achieved

1. Stay true to CSS Modules principles
2. Context sensitive styles - *if this element is inside this parent, apply these styles to it.*
3. Works in IE 11
4. Use CSS Grid

![test](https://user-images.githubusercontent.com/1240667/45523813-c69aaf80-b790-11e8-8659-37b85c6a8a15.PNG)

![test](https://user-images.githubusercontent.com/1240667/45523824-d31f0800-b790-11e8-97ee-4f430c7e0edd.PNG)
