### ISSUE TITLE
[css-grid] Not inheriting gaps from less specific rules

### ISSUE THREAD

**Issue by Dan503** [postcss/autoprefixer#1117]
<details>
    <summary>Input CSS</summary>

```css

.grid {
  display: grid;
  grid-gap: 20px; /* <-- Notice the grid-gap value here */
  grid-template-areas:
    "a b"
    "c d";
  grid-template-columns: repeat(2, 1fr);
  grid-template-rows: repeat(2, 1fr);
}

.grid.more-specific {
  /* grid-gap left out but should be inherited from .grid */
  grid-template-areas:
    "e f"
    "g h";
  grid-template-columns: repeat(2, 1fr);
  grid-template-rows: repeat(2, 1fr);
}

@media (max-width: 600px) {
  .grid {
    grid-template-areas:
      "a b"
      "c d";
    grid-template-columns: repeat(2, 1fr);
    grid-template-rows: repeat(2, 1fr);
  }
  .grid.more-specific {
    grid-template-areas:
      "e f"
      "g h";
    grid-template-columns: repeat(2, 1fr);
    grid-template-rows: repeat(2, 1fr);
  }
}

.a { grid-area: a; }
.b { grid-area: b; }
.c { grid-area: c; }
.d { grid-area: d; }
.e { grid-area: e; }
.f { grid-area: f; }
.g { grid-area: g; }
.h { grid-area: h; }
```

</details>

<details>
    <summary>Current CSS output</summary>

```css
.grid {
  display: -ms-grid;
  display: grid;
  grid-gap: 20px;
      grid-template-areas: "a b"
 "c d";
  -ms-grid-columns: 1fr 20px 1fr;
  grid-template-columns: repeat(2, 1fr);
  -ms-grid-rows: 1fr 20px 1fr;
  grid-template-rows: repeat(2, 1fr);
}

.grid.more-specific {
      grid-template-areas: "e f"
 "g h";
  -ms-grid-columns: (1fr)[2];  /* <-- no grid-gap inheritance */
  grid-template-columns: repeat(2, 1fr);
  -ms-grid-rows: (1fr)[2];  /* <-- no grid-gap inheritance */
  grid-template-rows: repeat(2, 1fr);
}

@media (max-width: 600px) {
  .grid {
        grid-template-areas: "a b"
 "c d";
    -ms-grid-columns: 1fr 20px 1fr;
    grid-template-columns: repeat(2, 1fr);
    -ms-grid-rows: 1fr 20px 1fr;
    grid-template-rows: repeat(2, 1fr);
  }
  .grid.more-specific {
        grid-template-areas: "e f"
 "g h";
    -ms-grid-columns: (1fr)[2];  /* <-- no grid-gap inheritance */
    grid-template-columns: repeat(2, 1fr);
    -ms-grid-rows: (1fr)[2];  /* <-- no grid-gap inheritance */
    grid-template-rows: repeat(2, 1fr);
  }
}

.a {
  -ms-grid-row: 1;
  -ms-grid-column: 1;
  grid-area: a;
}

.b {
  -ms-grid-row: 1;
  -ms-grid-column: 3;
  grid-area: b;
}

.c {
  -ms-grid-row: 3;
  -ms-grid-column: 1;
  grid-area: c;
}

.d {
  -ms-grid-row: 3;
  -ms-grid-column: 3;
  grid-area: d;
}

@media (max-width: 600px) {
  .a {
    -ms-grid-row: 1;
    -ms-grid-column: 1;
  }
  .b {
    -ms-grid-row: 1;
    -ms-grid-column: 2;
  }
  .c {
    -ms-grid-row: 2;
    -ms-grid-column: 1;
  }
  .d {
    -ms-grid-row: 2;
    -ms-grid-column: 2;
  }
}

.e {
  -ms-grid-row: 1;
  -ms-grid-column: 1;
  grid-area: e;
}

.f {
  -ms-grid-row: 1;
  -ms-grid-column: 2;
  grid-area: f;
}

.g {
  -ms-grid-row: 2;
  -ms-grid-column: 1;
  grid-area: g;
}

.h {
  -ms-grid-row: 2;
  -ms-grid-column: 2;
  grid-area: h;
}

@media (max-width: 600px) {
  .e {
    -ms-grid-row: 1;
    -ms-grid-column: 1;
  }
  .f {
    -ms-grid-row: 1;
    -ms-grid-column: 2;
  }
  .g {
    -ms-grid-row: 2;
    -ms-grid-column: 1;
  }
  .h {
    -ms-grid-row: 2;
    -ms-grid-column: 2;
  }
}
```

</details>

<details>
    <summary>Expected CSS output</summary>

```css
.grid {
  display: -ms-grid;
  display: grid;
  grid-gap: 20px;
      grid-template-areas: "a b"
 "c d";
  -ms-grid-columns: 1fr 20px 1fr;
  grid-template-columns: repeat(2, 1fr);
  -ms-grid-rows: 1fr 20px 1fr;
  grid-template-rows: repeat(2, 1fr);
}

.grid.more-specific {
      grid-template-areas: "e f"
 "g h";
  -ms-grid-columns: 1fr 20px 1fr;  /* <-- grid-gap inheritance */
  grid-template-columns: repeat(2, 1fr);
  -ms-grid-rows: 1fr 20px 1fr;  /* <-- grid-gap inheritance */
  grid-template-rows: repeat(2, 1fr);
}

@media (max-width: 600px) {
  .grid {
        grid-template-areas: "a b"
 "c d";
    -ms-grid-columns: 1fr 20px 1fr;
    grid-template-columns: repeat(2, 1fr);
    -ms-grid-rows: 1fr 20px 1fr;
    grid-template-rows: repeat(2, 1fr);
  }
  .grid.more-specific {
        grid-template-areas: "e f"
 "g h";
    -ms-grid-columns: 1fr 20px 1fr;  /* <-- grid-gap inheritance */
    grid-template-columns: repeat(2, 1fr);
    -ms-grid-rows: 1fr 20px 1fr;  /* <-- grid-gap inheritance */
    grid-template-rows: repeat(2, 1fr);
  }
}

.a {
  -ms-grid-row: 1;
  -ms-grid-column: 1;
  grid-area: a;
}

.b {
  -ms-grid-row: 1;
  -ms-grid-column: 3;
  grid-area: b;
}

.c {
  -ms-grid-row: 3;
  -ms-grid-column: 1;
  grid-area: c;
}

.d {
  -ms-grid-row: 3;
  -ms-grid-column: 3;
  grid-area: d;
}

@media (max-width: 600px) {
  .a {
    -ms-grid-row: 1;
    -ms-grid-column: 1;
  }
  .b {
    -ms-grid-row: 1;
    -ms-grid-column: 3;
  }
  .c {
    -ms-grid-row: 3;
    -ms-grid-column: 1;
  }
  .d {
    -ms-grid-row: 3;
    -ms-grid-column: 3;
  }
}

.e {
  -ms-grid-row: 1;
  -ms-grid-column: 1;
  grid-area: e;
}

.f {
  -ms-grid-row: 1;
  -ms-grid-column: 3;
  grid-area: f;
}

.g {
  -ms-grid-row: 3;
  -ms-grid-column: 1;
  grid-area: g;
}

.h {
  -ms-grid-row: 3;
  -ms-grid-column: 3;
  grid-area: h;
}

@media (max-width: 600px) {
  .e {
    -ms-grid-row: 1;
    -ms-grid-column: 1;
  }
  .f {
    -ms-grid-row: 1;
    -ms-grid-column: 3;
  }
  .g {
    -ms-grid-row: 3;
    -ms-grid-column: 1;
  }
  .h {
    -ms-grid-row: 3;
    -ms-grid-column: 3;
  }
}
```

</details>

**Comment by ai** [comment]
It is unfixable in general way but can be fixed for some specific cases like `.origin {} .origin.modifier {}` or `.origin {} .modifier .origin {}`.

Unfortunately, in this case it will be even worse:

```css
.origin { grid-gap: 10px; … }
.origin.is-a { grid-gap: 20px; … }
.origin.is-b { … }
```

We do not know is it `<div class="origin is-b">` or `<div class="origin is-b is-a">`.

We can show a warning to ask explicitly set `grid-gap`.

What are your thoughts about fixing it?
