### ISSUE TITLE
[css-grid] Handle [align/justify]-[content/items] appropriately

### ISSUE THREAD

**Issue by Dan503** [postcss/autoprefixer#1118]
IE does not supporting any of these properties:

- align-content
- align-items
- justify-content
- justify-items

For `align-items` and `justify-items`, you can often work around the issue by using `align-self` and `justify-self` instead:

```css
/* This: */
.grid {
  justify-items: center;
  align-items: center;
}

/* Is very similar to this: */
.grid > * {
  align-self: center;
  justify-self: center;
}
```
It doesn't work in 100% of circumstances but it does work most of the time. If Autoprefixer knows that the element is a grid container then it should be prefixed like so:

**Input CSS**

```css
.grid {
  display: grid;
  justify-items: center;
  align-items: center;
}
```

**Expected output CSS**

```css
.grid {
  display: -ms-grid;
  display: grid;
  justify-items: center;
  align-items: center;
}
.grid > * {
  -ms-grid-column-align: center;
  -ms-grid-row-align: center;
}
```

If `justify-items` or `align-items` is used in the same rule as any of the following properties, then it is safe to assume that it is a grid container element:

- display: grid
- display: inline-grid
- grid-template-columns
- grid-template-rows
- grid-template-areas
- grid-template
- grid-column-gap
- grid-row-gap
- grid-gap

For `align-content` and `justify-content` Autoprefixer should warn users that IE does not support those properties if it detects that they are being used on a grid container and grid translations are enabled.

Example Warning:

> IE does not support align-content and justify-content on grid containers
