### ISSUE TITLE
Double processing and align-content

### ISSUE THREAD

**Issue by janczer** [postcss/autoprefixer#1127]
WIth the property `align-content` the autoprefixer flip properties with prefixes `-webkit-` and `-ms-` after double processing

Here the minimal application that reproduce this bug:

```js
const autoprefixer = require('autoprefixer');
const postcss      = require('postcss');

const grider = autoprefixer({
  browsers: ['Chrome 25', 'Edge 12', 'IE 10'],
  cascade: false,
  grid: true
})

const input = '.warn_ei { align-content: center; display: grid; }'

const processor = postcss([grider])

processor.process(input).then((result) => {
    console.log(result.css)
    return result
}).then((prev) => {
    let result = processor.process(prev)
    console.log(result.css)
    return result
}).then((prev) => {
    let result = processor.process(prev)
    console.log(result.css)
    return result
})
```

The output is:

```css
.warn_ei { -webkit-align-content: center; -ms-flex-line-pack: center; align-content: center; display: -ms-grid; display: grid; }
.warn_ei { -ms-flex-line-pack: center; -webkit-align-content: center; align-content: center; display: -ms-grid; display: grid; }
.warn_ei { -ms-flex-line-pack: center; -webkit-align-content: center; align-content: center; display: -ms-grid; display: grid; }
```
