### ISSUE TITLE
[css-grid] Inheritance of grid-gap values for similar selectors

### ISSUE THREAD

**Issue by bogdan0083** [postcss/autoprefixer#1131]
Grid gap values should be inherited from the rules with the same selector, but modifiers placed in a different order.

An example:
```css
.grid.one.two {
  grid-gap: 20px;
  /* other styles */
}

.grid.two.one {
  /* grid gap should inherit from .grid.one.two */
}
```

The use case is minor, but it would be cool if we can get this thing implemented! 🤠

**Comment by Dan503** [comment]
You also might want to think about this

```css
.mum.dad .grid.one.two {
  grid-gap: 20px;
  /* other styles */
}

.dad.mum .grid.two.one {
  /* grid gap should inherit from .grid.one.two */
}
```
