### ISSUE TITLE
[css-grid] Major bug in grid-gap media query inheritance

### ISSUE THREAD

**Issue by Dan503** [postcss/autoprefixer#1133]
I only just noticed this. The media query column/row value is not updated to take the inherited grid-gap value into account.

## Input CSS
```css
.grid {
  display: grid;
  grid-gap: 20px; /* grid-gap is stated here */
  grid-template:
    "one two" /
    1fr  1fr;
}
@media (max-width: 600px) {
  .grid {
    /* grid-gap is inherited here */
    grid-template:
      "one"
      "two" /
       1fr;
  }
}
.one {
  grid-area: one;
}
.two {
  grid-area: two;
}
```
## Output CSS

```css
.grid {
  display: -ms-grid;
  display: grid;
  grid-gap: 20px; /* grid-gap is stated here */
  -ms-grid-rows: auto;
  -ms-grid-columns: 1fr 20px 1fr;
      grid-template:
    "one two" /
    1fr  1fr;
}
@media (max-width: 600px) {
  .grid {
    /* grid-gap is inherited here */
    -ms-grid-rows: auto 20px auto;
    -ms-grid-columns: 1fr;
        grid-template:
      "one"
      "two" /
       1fr;
  }
}
.one {
  -ms-grid-row: 1;
  -ms-grid-column: 1;
  grid-area: one;
}
.two {
  -ms-grid-row: 1;
  -ms-grid-column: 3;
  grid-area: two;
}
@media (max-width: 600px) {
  .one {
    -ms-grid-row: 1;
    -ms-grid-column: 1;
  }
  .two {
    -ms-grid-row: 2; /* This should be 3 not 2  */
    -ms-grid-column: 1;
  }
}
```

The expected output is the same as the regular output except with a 3 instead of a 2.

//cc @bogdan0083
