### ISSUE TITLE
9.2.0 adds `-webkit-box-align`

### ISSUE THREAD

**Issue by XhmikosR** [postcss/autoprefixer#1142]
For example:

```css
.foo {
  align-items: center;
}
```

results in:

```css
.foo {
  -webkit-box-align: center;
  -webkit-align-items: center;
  -ms-flex-align: center;
  align-items: center;
}
```

With 9.1.5 I get this:

```css
.foo {
  -webkit-align-items: center;
  -ms-flex-align: center;
  align-items: center;
}
```

.browserslistrc:

```
>= 0.25% in US
last 2 major versions
not dead
Android >= 4.4
Chrome >= 45
Edge >= 12
Explorer >= 10
Firefox >= 38
iOS >= 8
Opera >= 30
Safari >= 8
```

Is this expected?

Here's a test repo https://github.com/XhmikosR/autoprefixer-test

If you revert the last patch you will get the previous behavior without `-webkit-box-align`.
