### ISSUE TITLE
[css-grid] `place-self` can be translated

### ISSUE THREAD

**Issue by Dan503** [postcss/autoprefixer#1143]
I'm kicking myself for not realizing this while we were working on the align/justify-content/items warnings >_<

## Input CSS

```css
.grid > * {
  place-self: center;
}
```

## Current Output CSS

```css
.grid > * {
  place-self: center;
}
```

## Expected output CSS

```css
.grid > * {
  -ms-grid-row-align: center;
  -ms-grid-column-align: center;
  place-self: center;
}
```

**Comment by Dan503** [comment]
Also be aware that if you write this CSS:

```css
.grid {
  display: grid;
  place-items: start end;
}
```

It will output this warning:

> autoprefixer: C:\xxx\autoprefixer\playground\output.css:11:3: IE does not support place-items on grid containers. Try using place-self on child elements instead: .grid > * { place-self: start end }

This warning is misleading to users as using `place-self` currently does not get translated by Autoprefixer.
