### ISSUE TITLE
`-ms-writing-mode` does not take `direction` property into account

### ISSUE THREAD

**Issue by Dan503** [postcss/autoprefixer#1152]
In this code pen, I have both `writing-mode: vertical-rl;` and `direction: rtl;` in the same rule CSS rule.

https://codepen.io/daniel-tonon/pen/rqPbmZ

In modern browsers it looks like this:

![v-rl_d-rtl](https://user-images.githubusercontent.com/10610368/47600215-457a3d80-da09-11e8-926a-50191ee55b98.png)

However in IE it appears like this:

![v-rl_d-ltr](https://user-images.githubusercontent.com/10610368/47600192-e7e5f100-da08-11e8-82e8-06a75485b71f.png)

Usually IE does support `direction` when it is used on it's own however when it is combined with writing mode, `writing-mode` takes priority, even if `direction` was used after `writing-mode` in the CSS order.

**Input CSS**

```css
.element {
  writing-mode: vertical-rl;
  direction: rtl;
}
```

**Current output CSS**

```css
.element {
  -ms-writing-mode: tb-rl;
  writing-mode: vertical-rl;
  direction: rtl;
}
```

**Expected output CSS**
```css
.element {
  -ms-writing-mode: bt-rl;
  writing-mode: vertical-rl;
  direction: rtl;
}
```
----

# Examples of every combination

For the sake of completeness here are a bunch of screenshots and code snippets showing all the different possible configurations you can have:

---

````
direction: ltr;
-ms-writing-mode: lr-tb;
writing-mode: horizontal-tb;
````
![h-tb_d-ltr](https://user-images.githubusercontent.com/10610368/47600103-ccc6b180-da07-11e8-94d2-1512619f35ca.png)

---

````
direction: rtl;
-ms-writing-mode: rl-tb;
writing-mode: horizontal-tb;
````
![h-tb_d-rtl](https://user-images.githubusercontent.com/10610368/47600124-10212000-da08-11e8-80e7-869bb9b5343c.png)

---

````
direction: ltr;
-ms-writing-mode: tb-lr;
writing-mode: vertical-lr;
````
![v-lr_d-ltr](https://user-images.githubusercontent.com/10610368/47600150-5d9d8d00-da08-11e8-8ef1-0692e70596af.png)

---

````
direction: rtl;
-ms-writing-mode: bt-lr;
writing-mode: vertical-lr;
````
![v-lr_d-rtl](https://user-images.githubusercontent.com/10610368/47600171-a5241900-da08-11e8-95f1-dd89798a2974.png)

---

````
direction: ltr;
-ms-writing-mode: tb-rl;
writing-mode: vertical-rl;
````
![v-rl_d-ltr](https://user-images.githubusercontent.com/10610368/47600192-e7e5f100-da08-11e8-82e8-06a75485b71f.png)

---

````
direction: rtl;
-ms-writing-mode: bt-rl;
writing-mode: vertical-rl;
````
![v-rl_d-rtl](https://user-images.githubusercontent.com/10610368/47600215-457a3d80-da09-11e8-926a-50191ee55b98.png)
