### ISSUE TITLE
The autoprefixer spans columns and gaps instead of columns including gaps

### ISSUE THREAD

**Issue by mruoss** [postcss/autoprefixer#1155]
When using `column-gap` and `column-span`, the autoprefixer turns gaps into columns and spans the columns and gaps, instead of columns including gaps.

Test case:
```sass
.grid
    grid-template-rows: repeat(6, auto)
    grid-template-columns: repeat(4, 1fr)
    grid-template-areas: "tile-1 tile-2 tile-3 tile-4" "tile-5 tile-6 tile-7 tile-8" 
    column-gap: 28px

.spanning-tile
    grid-area: tile-5
    grid-column: span 2
```

Output:
```css
.grid {
    -ms-grid-rows: (auto)[6];
    grid-template-rows: repeat(6,auto);
    -ms-grid-columns: 1fr 28px 1fr 28px 1fr 28px 1fr;
    grid-template-columns: repeat(4,1fr);
    grid-template-areas: "tile-1 tile-2 tile-3 tile-4" "tile-5 tile-6 tile-7 tile-8";
    -webkit-column-gap: 28px;
    column-gap: 28px;
}

.spanning-tile {
    -ms-grid-row: 2;
    -ms-grid-column: 1;
    grid-area: tile-5;
    grid-column: span 2;
    -ms-grid-column-span: 2;
}
```

Problem:
On IE, the gaps are made out of additional columns. Hence, the `-ms-grid-column-span: 2;` will span the first colum and the first gap, while on other browsers, `grid-column: span 2;` spans the first column, the gap and the second column.

Possible solution: 
Turn `grid-column: span $cols;` into `-ms-grid-column-span: 2*$cols - 1` if `column-gap` is defined.

**Comment by Dan503** [comment]
This is a use case for named grid lines.

https://github.com/postcss/autoprefixer/issues/1020

That issue has been on the back burner for quite a while.

My best recommendation right now is to manually write the IE prefix:

```
.spanning-tile
    grid-area: tile-5
    -ms-grid-column-span: 3;
    grid-column: span 2
```

**Comment by Dan503** [comment]
IE doesn't support `grid-gap` so the only way that Autoprefixer can replicate gaps is to add extra rows and columns to the grid.

**Comment by Dan503** [comment]
Do you need the overlap?

If not, the best way to handle the situation is to make the grid area span multiple columns:

```
.grid
    grid-template-rows: repeat(6, auto)
    grid-template-columns: repeat(4, 1fr)
    grid-template-areas: "tile-1 tile-2 tile-3 tile-4" "tile-5 tile-5 tile-6 tile-7" 
    column-gap: 28px
```

**Comment by mruoss** [comment]
> My best recommendation right now is to manually write the IE prefix:

Hi @Dan503 and thanks for the quick response. Okay, this is exactly the workaround we used:
 
```
.spanning-tile
    // autoprefixer grid: off
    grid-column: span 2
    // autoprefixer grid: on
    -ms-grid-column-span: 3;
    grid-area: tile-5
```

Is it possible / are you planning to build this logic as proposed into the autoprefixer or is it a wontfix as this is gonna be solved with #1020? (in which case we can close the issue)

**Comment by mruoss** [comment]
Yeah in fact we need the overlap in our case.

**Comment by Dan503** [comment]
Don't use the `on` and `off` comments like that. They affect the while block. The second control comment should be getting ignored.

Do this instead:

```
.spanning-tile
    // autoprefixer: ignore next
    grid-column: span 2
    -ms-grid-column-span: 3;
    grid-area: tile-5
```

It is feasable that we could support this since we know the grid cell has a gap thanks to the grid area.

@bogdan0083 how do you feel about this issue? Is it worth fixing or should people just hack around it?

**Comment by mruoss** [comment]
Oh right, thanks for the tipp.

**Comment by Dan503** [comment]
Ummm... I tested this out and what you have posted doesn't seem to work in modern browsers :/

```css
.spanning-tile {
    grid-column: span 2; /* This is ignored by modern browsers because grid-area overrides it */
    grid-area: tile-5;
}
```

```css
.spanning-tile {
    grid-area: tile-5;
    grid-column: span 2; /* This places the start of the column in the wrong place */
}
```

The only way to make it work in a modern browser is to place the `grid-column` after `grid-area` and define _both_ a start and end line for `grid-column`.

```css
.spanning-tile {
    grid-area: tile-5;
    grid-column: 1 / span 2; /* define both the start and end line of the column */
}
```

I made a demo here: https://codepen.io/daniel-tonon/pen/eQePXQ

If you override the `grid-column` though, it makes using grid-areas kind of pointless. You are overriding the automatic placement functionality so if you change the grid template areas definition, it can't reliably move into the correct position.

**Comment by mruoss** [comment]
You're right, @Dan503. It was by chance my code resulted in the desired result. I guess, if you want to use the name of the grid area instead of the start columns, you could also define column and row separately:

```css
.spanning-tile {
    grid-row: tile-5;
    grid-column: tile-5 / span 2; /* define start as tile-5 */
}
```
Added it to your demo: https://codepen.io/anon/pen/WYXqrz

However, this will not return the desired result by the autoprefixer as far as I can tell...

**Comment by Dan503** [comment]
Since Autoprefixer doesn't support named lines yet, your solution isn't an option.

**Comment by Dan503** [comment]
I think we should close this issue. The use case that was keeping this issue open isn't actually valid.

This is a use case for #1020 (named grid lines).

**Comment by Dan503** [comment]
Oh actually `grid-column-end: span 2` might work. Let me try that out.

**Comment by Dan503** [comment]
It worked! 😁

https://codepen.io/daniel-tonon/pen/eQePXQ

The trick is to use `grid-column-end: span 2;`

```css
.spanning-tile {
    grid-area: tile-5;
    grid-column-end: span 2; /* works perfectly */
}
```

It even works in IE11.

**Comment by mruoss** [comment]
Yes excactly, but now we are back to the initial problem. If you add a gap, it doesn't work as desired. But my workaround from above works here, too:

```css
.spanning-tile {
	grid-area: tile-5;
	/* autoprefixer: ignore next */
	grid-column-end: span 2;
	-ms-grid-column-span: 3;
}
```
