### ISSUE TITLE
Remove warning from grid-[column/row]-end: span X; + grid-area combo

### ISSUE THREAD

**Issue by Dan503** [postcss/autoprefixer#1157]
In #1155 we discovered that `grid-column-end: span 2;` is a valid way to make a grid area cell overlap other areas.

```css
.spanning-tile {
    grid-area: tile-5;
    grid-column-end: span 2; /* force an overlap */
}
```

We should remove the warning for `grid-[column/row]-end: span X;`

>You already have a grid-area declaration present in the rule. You should use either grid-area or grid-column-end, not both
