### ISSUE TITLE
IE 11 justify-content property

### ISSUE THREAD

**Issue by aduh95** [postcss/autoprefixer#1170]
IE 11 doesn't support `start`, `end`, `left` nor `right` value for `justify-content` property.

Using `IE 11` as browser list.

#### Input 

```css
.class {
  display: flex;
  justify-content: start;
}
```

#### Expected Output

```css
.class {
    display: flex;
    -ms-flex-pack: start;
        justify-content: start;
}
```

#### Actual output

```css
.class {
    display: flex;
    justify-content: start;
}
```

Note: Autoprefixer add the `-ms-flex-pack` property for IE 10, but not for IE 11.
