### ISSUE TITLE
Missing Edge prefix for ::placeholder

### ISSUE THREAD

**Issue by mh-nichts** [postcss/autoprefixer#1176]
Hello,

Maybe I'm missing something, but it seems that Edge ::placeholder prefix is no longer generated : `::-ms-input-placeholder` (notice the double colon),.
However, the one for IE11 is still there (with single colon).

Original code : 
```
::placeholder {
  color: inherit;
}
```
Generated code : 
```
:-ms-input-placeholder {
  color: inherit; }
::placeholder {
  color: inherit; }
```
Expected generated code : 
```
:-ms-input-placeholder {
  color: inherit; }
::-ms-input-placeholder {
  color: inherit; }
::placeholder {
  color: inherit; }
```

I think it's related to the following issues : 
- https://github.com/postcss/autoprefixer/issues/913
- and especially https://github.com/postcss/autoprefixer/issues/1161, because I've read that Edge also supports `::-webkit-input-placeholder` (cf. https://caniuse.com/#feat=css-placeholder), so it might have been "visually working" until that prefix was removed (I don't know when exactly).

Or maybe there is something in my browsers list that needs to change ?
```
"browserslist": [
    "> 1%",
    "last 2 versions",
    "ie >= 11",
    "iOS 7"
  ],
```

Thanks in advance !

**Comment by ai** [comment]
Run `npx browserslist` in your project directory. It will show what browsers are selected by Browserslist config.

**Comment by ai** [comment]
My output for the same input and the same `browserslist`:

```css
::-webkit-input-placeholder {
  color: inherit
}

:-ms-input-placeholder {
  color: inherit
}

::-ms-input-placeholder {
  color: inherit
}

::placeholder {
  color: inherit
}
```

Try to update your Autoprefixer and Can I Use.
