### ISSUE TITLE
[css-grid] Autoprefixer outputting wrong IE grid-span syntax

### ISSUE THREAD

**Issue by cloudsociety** [postcss/autoprefixer#1181]
As mentioned in #1064, I'm seeing similar behaviour with `span x` not prefixing correctly with `grid-gap`. 

When declaring `grid-area: 1 / 2 / 1 / span 4;`, it is being prefixed to the following: 

```
    -ms-grid-row: 1;
    -ms-grid-column: 2;
    -ms-grid-column-span: 4;
    grid-area: 1 / 2 / 1 / span 4;
```

But `-ms-grid-column-span: 4;` should actually be `-ms-grid-column-span: 7;` to account for the grid gaps.

Test case: https://codepen.io/davecross/pen/ce7e08421ea29a8464ff82b84fcc7d12?editors=1100

**Comment by Dan503** [comment]
Here is a cleaner reduced test case of the problem:

## Input CSS

```css
.grid {
  display: grid;
}

.grid--2col {
  grid-gap: 20px;
  grid-template-columns: repeat(12, 1fr);
  grid-template-areas: "a a a a a a b b b b b b";
}

.grid--2col > .a {
  grid-area: a;
}

.grid--2col > .b {
  grid-area: b;
}

@media (min-width: 376px) {
  .grid--2col .smaller {
    grid-area: 1 / 2 / 1 / span 4;
  }
}
```

## Current output CSS

```css
.grid {
  display: -ms-grid;
  display: grid;
}

.grid--2col {
  grid-gap: 20px;
  -ms-grid-columns: 1fr 20px 1fr 20px 1fr 20px 1fr 20px 1fr 20px 1fr 20px 1fr 20px 1fr 20px 1fr 20px 1fr 20px 1fr 20px 1fr;
  grid-template-columns: repeat(12, 1fr);
      grid-template-areas: "a a a a a a b b b b b b";
}

.grid--2col > .a {
  -ms-grid-row: 1;
  -ms-grid-column: 1;
  -ms-grid-column-span: 11;
  grid-area: a;
}

.grid--2col > .b {
  -ms-grid-row: 1;
  -ms-grid-column: 13;
  -ms-grid-column-span: 11;
  grid-area: b;
}

@media (min-width: 376px) {
  .grid--2col .smaller {
    -ms-grid-row: 1;
    -ms-grid-column: 2;
    -ms-grid-column-span: 4;
    grid-area: 1 / 2 / 1 / span 4;
  }
}
```

## expected output

```css
.grid {
  display: -ms-grid;
  display: grid;
}

.grid--2col {
  grid-gap: 20px;
  -ms-grid-columns: 1fr 20px 1fr 20px 1fr 20px 1fr 20px 1fr 20px 1fr 20px 1fr 20px 1fr 20px 1fr 20px 1fr 20px 1fr 20px 1fr;
  grid-template-columns: repeat(12, 1fr);
      grid-template-areas: "a a a a a a b b b b b b";
}

.grid--2col > .a {
  -ms-grid-row: 1;
  -ms-grid-column: 1;
  -ms-grid-column-span: 11;
  grid-area: a;
}

.grid--2col > .b {
  -ms-grid-row: 1;
  -ms-grid-column: 13;
  -ms-grid-column-span: 11;
  grid-area: b;
}

@media (min-width: 376px) {
  .grid--2col .smaller {
    -ms-grid-row: 1;
    -ms-grid-column: 2;
    -ms-grid-column-span: 7; /* <= Note the 7 here instead of 4 */
    grid-area: 1 / 2 / 1 / span 4;
  }
}
```
