### ISSUE TITLE
cannot read property 'inserAfter' of undefined, with grid: "autoplace" on

### ISSUE THREAD

**Issue by nachtfunke** [postcss/autoprefixer#1187]
I've been using an older version of autoprefixer (4.x), so I updated to maybe try out the new support for legacy Grid syntax. I get this very cryptic error though that I unfortunately don't understand enough to solve:

```
Message:
    Cannot read property 'insertAfter' of undefined
Details:
    postcssNode: grid-area: main
    fileName: /src/sass/style.css
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false

Stack:
TypeError: Cannot read property 'insertAfter' of undefined
```
I am on the latest version of autoprefixer. Has anyone else encountered this issue?
