### ISSUE TITLE
Named grid-row-start values generate -ms-grid-row-span: NaN

### ISSUE THREAD

**Issue by marmaak** [postcss/autoprefixer#1189]
Hi,

I am working on a layout using this CSS rule:

```css
.main {
    display: grid;
    grid-template: 
        "header header"
        "menu   content";
}
```

And sometimes, my content must cover also the menu area:

```css
.content {
    grid-row-start: menu-start;
    grid-column-start: menu-start;
    grid-row-end: content-end;
    grid-column-end: content-end;
}
```

But the generated CSS after Autoprefixer task has some NaN values:

```css
.main {
    display: -ms-grid;
    display: grid;
    -ms-grid-rows: auto;
        grid-template: 
        "header header"
        "menu   content";
}
.content {
    -ms-grid-row: menu-start;
        grid-row-start: menu-start;
    -ms-grid-column: menu-start;
        grid-column-start: menu-start;
    -ms-grid-row-span: NaN;
        grid-row-end: content-end;
    -ms-grid-column-span: NaN;
        grid-column-end: content-end;
}
```

Tried on https://autoprefixer.github.io/ using PostCSS v. 7.0.6 and Autoprefixer 9.4.0

**Comment by ai** [comment]
cc @bogdan0083

**Comment by Dan503** [comment]
I think this is a duplicate of #1020.

Autoprefixer currently doesn't support named lines. It does support areas though.

There is a hacky work around using grid span syntax and manual -ms- prefix for creating the overlap that you are after. (https://github.com/postcss/autoprefixer/issues/1155)

Use this syntax:

```css
.content {
    grid-area: menu;
    -ms-grid-column-span: 3;
    grid-column-end: span 2;
}
```
