### ISSUE TITLE
Prevent duplication and remove unneeded prefixes

### ISSUE THREAD

**Issue by sindresorhus** [postcss/autoprefixer#12]
The user might already have some of the properties prefixed while others not. Currently if you run autoprefixer on already prefixed properties it will duplicate them.

Before:

``` css
body {
  -webkit-transition: all 1s ease-out;
  -o-transition: all 1s ease-out;
  transition: all 1s ease-out
}
```

After:

``` css
body {
  -webkit-transition: all 1s ease-out;
  -o-transition: all 1s ease-out;
  -webkit-transition: all 1s ease-out;
  -o-transition: all 1s ease-out;
  transition: all 1s ease-out
}
```

It should also remove no longer needed properties that might already exist in the CSS file.
