### ISSUE TITLE
[css-grid] grid-gap warning needlessly appearing 

### ISSUE THREAD

**Issue by Dan503** [postcss/autoprefixer#1209]
I have this grid code:

```scss
.grid {
	display: grid;
	// This is producing a warning in Autoprefixer. This code works perfectly in IE though.
	grid-gap: 0 30px;

	@media (min-width: 601px) {
		grid-template:
		"title img listing" auto
		"intro img listing" 1fr /
		21rem  275px 1fr;
	}

	@media (max-width: 600px) {
		grid-template:
		"title   img" auto
		"intro   img" auto
		"listing listing " 1fr /
		 1fr     1fr;
	}
}
```

Both the grid template declarations are wrapped in media queries. The grid gap is a default.

This code works fine in IE with Autoprefixer so there should not be any warning given.
