### ISSUE TITLE
Grid not working in angular7

### ISSUE THREAD

**Issue by joecollett** [postcss/autoprefixer#1210]
I am trying to get Angular7 working nicely with the Autoprefixer. I'm specifically looking to get support on IE11. I've removed the "not" from "IE 9 - 11" in the browserlist file. I've also added

/* autoprefixer grid: autoplace / / autoprefixer grid: on */

To the top of my _grid.scss file. Problem is grid items are still not getting any prefixes. Flexbox seems to work fine but not CSS grid. Is there any configuration I've missed?

**Comment by Dan503** [comment]
It sounds like you have done everything right. The only thing a bit off in what you said is how you wrote the control comment. 

```css
/* autoprefixer grid: autoplace */
```

If you have included IE in your browsers list, and added that control comment, and you are using the latest version of Autoprefixer then it should be working for you.

**Comment by joecollett** [comment]
Tried that as well and its still not working 
![autoprefixer](https://user-images.githubusercontent.com/13499326/56819015-cdb68f80-6840-11e9-9b46-cb986baf2aad.PNG)
![browserlist](https://user-images.githubusercontent.com/13499326/56819027-d3ac7080-6840-11e9-8bf3-be9ef8dc9306.PNG)
![css](https://user-images.githubusercontent.com/13499326/56819032-d60eca80-6840-11e9-8cd3-ae9a097ffe2f.PNG)

**Comment by ai** [comment]
What is Autoprefixer version? You can check it by `npm ls | grep autoprefixer`.

**Comment by joecollett** [comment]
autoprefixer@9.5.1 extraneous

**Comment by ai** [comment]
Are you have only one Autoprefixer in that list?

**Comment by joecollett** [comment]
Found this error npm ERR! extraneous: autoprefixer@9.5.1 C:\Projects\ClientCommandCentre\node_modules\autoprefixer

**Comment by joecollett** [comment]
Yea only one on the list

**Comment by ai** [comment]
What is paths for Browserslist config and CSS file?

**Comment by joecollett** [comment]
C:\Projects\ClientCommandCentre\src\browserslist
C:\Projects\ClientCommandCentre\src\scss\base\_grid.scss

**Comment by ai** [comment]
Can you create a simple `scss/test.scss` with:

```scss
a {
  display: grid
}
```

Maybe the problem is in mixin?

**Comment by joecollett** [comment]
![simple](https://user-images.githubusercontent.com/13499326/56821718-035e7700-6847-11e9-9d4e-e38f4243dc93.PNG)
![test](https://user-images.githubusercontent.com/13499326/56821723-048fa400-6847-11e9-8e3a-7b5de6d4104d.PNG)

**Comment by joecollett** [comment]
Flexbox seems to work though 

![flexbox](https://user-images.githubusercontent.com/13499326/56821881-6cde8580-6847-11e9-8995-f64e18ceff47.PNG)
![flexbox2](https://user-images.githubusercontent.com/13499326/56821905-7a940b00-6847-11e9-928b-1161b5b896a0.PNG)

**Comment by Dan503** [comment]
Try this:

```css
/* autoprefixer grid: autoplace */
.test {
  display: grid;
  grid-template-rows: auto;
  grid-template-columns: auto;
}
```

**Comment by Dan503** [comment]
If that doesn't work, maybe your compiler is stripping out comments before Autoprefixer has a chance to run.

**Comment by joecollett** [comment]
So after the scss has been compiled the comments should still be in the css? Looks like the compiled style sheet doesnt have any of the comments.

**Comment by Dan503** [comment]
Yes. That is your problem.

Don't do this:

```scss
// autoprefixer grid: autoplace
.test {
  display: grid;
  grid-template-rows: auto;
  grid-template-columns: auto;
}
```

Do this:

```css
/* autoprefixer grid: autoplace */
.test {
  display: grid;
  grid-template-rows: auto;
  grid-template-columns: auto;
}
```

There is a difference.

**Comment by joecollett** [comment]
Yep thats what I'm doing, just when I'm building the application its optimizing the css so stripping out all the comments. Will give that ago and see if it works!

**Comment by Dan503** [comment]
You can also try this:
```css
/*! autoprefixer grid: autoplace */
.test {
  display: grid;
  grid-template-rows: auto;
  grid-template-columns: auto;
}
```
