### ISSUE TITLE
I need help my prefixes are not correct, still not work code for IE

### ISSUE THREAD

**Issue by harshan89** [postcss/autoprefixer#1221]
My HTML **code**
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="main.css">
</head>
<body>
        <aside></aside>
        <header></header>
        <section></section>
        <section></section>
        <section></section>
        <main></main>
        <footer></footer>

</body>
</html>
```

**My CSS code**
```html
body, html {
    height: 100vh;
}

body {
    margin: 0;
    display: -ms-grid;
    display: grid;
    -ms-grid-columns: 100%;
    grid-template-columns: 100%;
    -ms-grid-rows: 8% 30% 44% 10% 8%;
    grid-template-rows: 8% 30% 44% 10% 8%;
        grid-template-areas: 
        "header" 
        "sec1" 
        "sec2"
        "sec3"
        "main" 
        "footer" 
}

aside {
    grid-area: sidebar;
    background-color: aqua;
}

header {
    -ms-grid-row: 1;
    -ms-grid-column: 1;
    grid-area: header;
    background-color: chocolate
}

section:nth-of-type(1) {
    -ms-grid-row: 2;
    -ms-grid-column: 1;
    grid-area: sec1;
    background-color: green;
}

section:nth-of-type(2) {
    -ms-grid-row: 3;
    -ms-grid-column: 1;
    grid-area: sec2;
    background-color: greenyellow;
}

section:nth-of-type(3) {
    -ms-grid-row: 4;
    -ms-grid-column: 1;
    grid-area: sec3;
    background-color: hotpink;
}

main {
    -ms-grid-row: 5;
    -ms-grid-column: 1;
    grid-area: main;
    background-color: indigo;
}

footer {
    -ms-grid-row:1; 
    -ms-grid-column:1;
    grid-area: footer;
    background-color: blueviolet
}

@media only screen and (min-width: 768px) {
    body {
        margin: 0;
        display:-ms-grid;
        display: grid;
        -ms-grid-columns:auto 27% 27% 27%;
        grid-template-columns: auto 27% 27% 27%;
        /* grid-template-rows: 8% 30% auto 10%; */
            grid-template-areas: 
            "sidebar header header header" 
            "sidebar sec1 sec2 sec3" 
            "sidebar main main main" 
            "sidebar footer footer footer" 
    }
    aside {
        -ms-grid-row: 1;
        -ms-grid-row-span: 4;
        -ms-grid-column: 1 
    }
    header {
        -ms-grid-row: 1;
        -ms-grid-column: 2;
        -ms-grid-column-span: 3 
    }
    section:nth-of-type(1) {
        -ms-grid-row: 2;
        -ms-grid-column: 2 
    }
    section:nth-of-type(2) {
        -ms-grid-row: 2;
        -ms-grid-column: 3 
    }
    section:nth-of-type(3) {
        -ms-grid-row: 2;
        -ms-grid-column: 4 
    }
    main {
        -ms-grid-row: 3;
        -ms-grid-column: 2;
        -ms-grid-column-span: 3 
    }
}
```

**Comment by ai** [comment]
> My CSS code

This is output after Autoprefixer? Or is it your CSS input?

cc @Dan503

**Comment by harshan89** [comment]
> > My CSS code
> 
> This is output after Autoprefixer? Or is it your CSS input?
> 
> cc @Dan503

That is my compiled code i got my css compiled via  [autoprefixer.github.io](https://autoprefixer.github.io)

My original css code is: 

```css
body, html {
    height: 100vh;
}

body {
    margin: 0;
    display: grid;
    grid-template-columns: 100%;
    grid-template-rows: 8% 30% 44% 10% 8%;
        grid-template-areas: 
        "header" 
        "sec1" 
        "sec2"
        "sec3"
        "main" 
        "footer" 
}

aside {
    grid-area: sidebar;
    background-color: aqua;
}

header {
    grid-area: header;
    background-color: chocolate
}

section:nth-of-type(1) {
    grid-area: sec1;
    background-color: green;
}

section:nth-of-type(2) {
    grid-area: sec2;
    background-color: greenyellow;
}

section:nth-of-type(3) {
    grid-area: sec3;
    background-color: hotpink;
}

main {
    grid-area: main;
    background-color: indigo;
}

footer {
    grid-area: footer;
    background-color: blueviolet
}

@media only screen and (min-width: 768px) {
    body {
        margin: 0;
        display: grid;
        grid-template-columns: auto 27% 27% 27%;
        grid-template-rows: 8% 30% auto 10%;
            grid-template-areas: 
            "sidebar header header header" 
            "sidebar sec1 sec2 sec3" 
            "sidebar main main main" 
            "sidebar footer footer footer" 
    }
}
```

**OUTPUT ON MOBILE AND DESKTOP** 

![grid_on_mobile](https://user-images.githubusercontent.com/9652826/58885136-4a217580-86ff-11e9-845c-864b0658653a.PNG)
![grid_on_desktop](https://user-images.githubusercontent.com/9652826/58885145-4d1c6600-86ff-11e9-820d-8f11aabd7cde.PNG)

**Comment by ai** [comment]
And what did you get on IE?

**Comment by harshan89** [comment]
> And what did you get on IE?

Blank page

**Comment by ai** [comment]
OK, let'’l’s wait for our Grid specialists.

**Comment by harshan89** [comment]
![ie_output](https://user-images.githubusercontent.com/9652826/58885520-fe230080-86ff-11e9-9185-f8efe121abaf.PNG)

**Comment by Dan503** [comment]
I'm wondering if it is because IE doesn't understand the HTML5 elements.

I found out recently that IE has a bug where inline elements will not be placed in a grid. They need to be set to `display: block;`.

Try adding this to your CSS.

```css
aside, header, section, main, footer {
  display: block;
}
```

I normally use normalize.css in my projects which adds stuff like this for me.

PS. Place the `<header>` before the `<aside>` in your HTML for the semantics to be correct.
