### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Lachiave** [postcss/autoprefixer#1238]
Autoprefixer creates errors like this:

from:
```css
.angle-container .right{
background:linear-gradient(82deg,white 15%,transparent 15%);
}
```

to:
```css
.angle-container .right{
background:-o-linear-gradient(8deg,white 15%,transparent 15%);
background:linear-gradient(82deg,white 15%,transparent 15%);
}
```

In the first line it writes 8 instead of 82
