### ISSUE TITLE
Autoprefixer fails on combination of @supports and grid-template-columns

### ISSUE THREAD

**Issue by smashercosmo** [postcss/autoprefixer#1244]
The following snippet 
```css
@supports (grid-template-columns: 1fr) {
  .columns {
    grid-template-columns: 1fr;
  }
}
```
results in error
```
TypeError: Cannot read property 'grid' of undefined
```
