### ISSUE TITLE
image-set with cursor generates invalid css

### ISSUE THREAD

**Issue by pixelass** [postcss/autoprefixer#1250]
When using image-set with cursors several issues occur:

1. styles are split into media-queries
1. cursor-position is removed (`cursor: url(...) [position], fallback`)
1. fallback is removed (`cursor: url(...) [position], fallback`)
1. selectors and rules are duplicated

**CONFIG**

```json
{
	"plugins": {
		"postcss-preset-env": {},
		"autoprefixer": {}
	}
};
```

**INPUT**

```css
.foo {
	cursor: image-set(
		url("foo.png") 1x,
		url("foo@2x.png") 2x
	) 9 9, default;
}
```

**EXPECTED**

```css
.foo {
 	cursor: url("foo.png") 9 9, default;
	cursor: -webkit-image-set(
		url("foo.png") 1x,
		url("foo@2x.png") 2x
	) 9 9, default;
	cursor: image-set(
		url("foo.png") 1x,
		url("foo@2x.png") 2x
	) 9 9, default;
}
```

**ACTUAL**

```css
.foo {
	cursor: 
		url("foo.png");
}

@media (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi) {
    .foo {
        cursor: 
            url("foo@2x.png");
    }
}

.foo {
	cursor: 
		url("foo.png");
}

@media (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi) {
    .foo {
        cursor: 
            url("foo@2x.png");
    }
}

.foo {
	cursor: -webkit-image-set(
		url("foo.png") 1x,
		url("foo@2x.png") 2x
	) 9 9, default;
	cursor: 
		url("foo.png");
}

@media (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi) {
    .foo {
        cursor: -webkit-image-set(
            url("foo.png") 1x,
            url("foo@2x.png") 2x
        ) 9 9, default;
        cursor: 
            url("foo@2x.png");
    }
}

.foo {
	cursor: -webkit-image-set(
		url("foo.png") 1x,
		url("foo@2x.png") 2x
	) 9 9, default;
	cursor: image-set(
		url("foo.png") 1x,
		url("foo@2x.png") 2x
	) 9 9, default;
}

```

related to #899

**Comment by ai** [comment]
Can you show output without `postcss-preset-env`? Seems like it is a `postcss-preset-env` problem.

It inserts `media` because some of your target browsers do not support `image-set`. You can check current target browsers by `npx browserslist` call. Here is a `postcss-preset-env` API to disable some features: https://www.npmjs.com/package/postcss-preset-env#features

**Comment by pixelass** [comment]
I added some further tests using `/* autoprefixer off */` which also does not work

**CONFIG**

```json
{
	"autoprefixer": {}
}
```

**INPUT**

```css
/* autoprefixer off */

.nRotate {
	cursor: url("../src/cursors/images/n-rotate.png") 9 9, default;
	cursor: image-set(
		url("../src/cursors/images/n-rotate.png") 1x,
		url("../src/cursors/images/n-rotate@2x.png") 2x
	) 9 9, default;
}

/* autoprefixer on */


.neRotate {
	cursor: url("../src/cursors/images/ne-rotate.png") 9 9, default;
	cursor: image-set(
		url("../src/cursors/images/ne-rotate.png") 1x,
		url("../src/cursors/images/ne-rotate@2x.png") 2x
	) 9 9, default;
}

.nwRotate {
	cursor: url("../src/cursors/images/nw-rotate.png") 9 9, default;
	cursor: -webkit-image-set(
		url("../src/cursors/images/nw-rotate.png") 1x,
		url("../src/cursors/images/nw-rotate@2x.png") 2x
	) 9 9, default;
}
```


**OUTPUT**

```css
/* autoprefixer off */

.nRotate {
	cursor: url("../src/cursors/images/n-rotate.png") 9 9, default;
	cursor: -webkit-image-set(
		url("../src/cursors/images/n-rotate.png") 1x,
		url("../src/cursors/images/n-rotate@2x.png") 2x
	) 9 9, default;
	cursor: image-set(
		url("../src/cursors/images/n-rotate.png") 1x,
		url("../src/cursors/images/n-rotate@2x.png") 2x
	) 9 9, default;
}

/* autoprefixer on */


.neRotate {
	cursor: url("../src/cursors/images/ne-rotate.png") 9 9, default;
	cursor: -webkit-image-set(
		url("../src/cursors/images/ne-rotate.png") 1x,
		url("../src/cursors/images/ne-rotate@2x.png") 2x
	) 9 9, default;
	cursor: image-set(
		url("../src/cursors/images/ne-rotate.png") 1x,
		url("../src/cursors/images/ne-rotate@2x.png") 2x
	) 9 9, default;
}

.nwRotate {
	cursor: url("../src/cursors/images/nw-rotate.png") 9 9, default;
	cursor: -webkit-image-set(
		url("../src/cursors/images/nw-rotate.png") 1x,
		url("../src/cursors/images/nw-rotate@2x.png") 2x
	) 9 9, default;
}
```

**Comment by Dan503** [comment]
You have done the control comments wrong in your example.

Do this sort of thing instead:

```css

.neRotate {
    /* autoprefixer off */
}

.neRotate {
    /* autoprefixer on */
}
```

**Comment by ai** [comment]
Hm, why do you have `-webkit-` if you disabled Autoprefixer? Let's do the simplest test. Use only Autoprefixer in PostCSS config and show input/output pair.

**Comment by pixelass** [comment]
it was just an additional test

**Comment by ai** [comment]
Do not use control comments, they could confuse is in this example.

**Comment by pixelass** [comment]
**CONFIG**:

```json
{
	"autoprefixer": {}
}
```


**INPUT**

```css
.foo {
	cursor: image-set(
		url("foo.png") 1x,
		url("foo@2x.png") 2x
	) 9 9, default;
}
```

**OUTPUT**

```css
.foo {
	cursor: -webkit-image-set(
		url("foo.png") 1x,
		url("foo@2x.png") 2x
	) 9 9, default;
	cursor: image-set(
		url("foo.png") 1x,
		url("foo@2x.png") 2x
	) 9 9, default;
}
```


### Without `url()`

**INPUT**

```css
.foo {
	cursor: image-set(
		"foo.png" 1x,
		"foo@2x.png" 2x
	) 9 9, default;
}
```

**OUTPUT**

```css
.foo {
	cursor: -webkit-image-set(
		url("foo.png") 1x,
		url("foo@2x.png") 2x
	) 9 9, default;
	cursor: image-set(
		"foo.png" 1x,
		"foo@2x.png" 2x
	) 9 9, default;
}
```
