### ISSUE TITLE
Ручные стили и анимации

### ISSUE THREAD

**Issue by Diokuz** [postcss/autoprefixer#126]
``` css
.ani {
    -webkit-transition: all .2s linear;
    transition: all .2s linear;
    -ms-transition: all .3s linear;
    animation: last 3s infinite;
    }

@keyframes last {
    from {
        transform: translate3d(0, 0, 0)
    }
    to {
        transform: translate3d(0, 100px, 0)
    }
}
```

Превращается в

``` css
.ani {
  -webkit-transition: all .2s linear;
  transition: all .2s linear;
  -webkit-animation: last 3s infinite;
  animation: last 3s infinite;
}

@-webkit-keyframes last {
  from {
    -webkit-transform: translate3d(0, 0, 0);
    transform: translate3d(0, 0, 0);
  }

  to {
    -webkit-transform: translate3d(0, 100px, 0);
    transform: translate3d(0, 100px, 0);
  }
}

@keyframes last {
  from {
    -webkit-transform: translate3d(0, 0, 0);
    -ms-transform: translate3d(0, 0, 0);
    transform: translate3d(0, 0, 0);
  }

  to {
    -webkit-transform: translate3d(0, 100px, 0);
    -ms-transform: translate3d(0, 100px, 0);
    transform: translate3d(0, 100px, 0);
  }
}
```

Более логично:

``` css
.ani {
  -webkit-transition: all .2s linear;
  transition: all .2s linear;
  -moz-transition: all .3s linear;
  -webkit-animation: last 3s infinite;
  animation: last 3s infinite;
}

@-webkit-keyframes last {
  from {
    -webkit-transform: translate3d(0, 0, 0);
  }

  to {
    -webkit-transform: translate3d(0, 100px, 0);
  }
}

@keyframes last {
  from {
    -ms-transform: translate3d(0, 0, 0);
    transform: translate3d(0, 0, 0);
  }

  to {
    -ms-transform: translate3d(0, 100px, 0);
    transform: translate3d(0, 100px, 0);
  }
}
```

То есть я хочу при желании вручную указывать те или иные префиксы, например для лисы я хочу больше транзишн. Браузера который поддерживает transform но не поддерживает keyframes (или наоборот) без префикса вебкит не существует, и даже если появится - дублировать свойства нет смысла. Вебкиту вебкитово) Этот код хочется выпилить.
