### ISSUE TITLE
user-select: contain is fixed incorrectly for IE/Edge

### ISSUE THREAD

**Issue by AmyAmy** [postcss/autoprefixer#1264]
IE and Edge use the non-standard value `element` instead of `contain` for the `user-select` property.

Currently autoprefixer transforms `user-select: contain;` into `-ms-user-select: contain;` in stead of `-ms-user-select: element;`

Documentation:
* https://developer.mozilla.org/en-US/docs/Web/CSS/user-select
* https://caniuse.com/#feat=mdn-css_properties_user-select_contain

**Comment by ai** [comment]
Thanks for the well-formed issue. I will try to fix it on this week.

**Comment by ai** [comment]
Fixed f34429b

**Comment by ai** [comment]
Released in 9.7.4

**Comment by yisibl** [comment]
There seems to be a bit of a problem here, -webkit and -moz are wrong, these browsers don't implement this value.

```css
/*
* Prefixed by https://autoprefixer.github.io
* PostCSS: v8.4.14,
* Autoprefixer: v10.4.7
* Browsers: > 0%
*/

.example {
    -webkit-user-select: contain;
       -moz-user-select: contain;
        -ms-user-select: element;
            user-select: contain;
}
```
