### ISSUE TITLE
Shouldn't supports: false disable prefixing inside @supports block?

### ISSUE THREAD

**Issue by frippz** [postcss/autoprefixer#1266]
`autoprefixer@9.7.2`

### Browserslist config
```json
"browserslist": [
  "last 2 versions",
  "not < 1%",
  "last 2 edge versions",
  "not ie < 11"
],
```

### postcss.config.js
```javascript
module.exports = {
  plugins: {
    autoprefixer: {
      supports: false,
    },
    'postcss-import': {},
    'postcss-custom-properties': {
      preserve: false,
    },
    'postcss-custom-media': {
      preserve: false,
    },
  },
};
```

### Input CSS
```css
@supports (position: sticky) {
  .search-results {
    position: sticky;
    top: 0;
  }
}
```

### Output CSS
```css
@supports (position: sticky) {
  .search-results {
    position: -webkit-sticky;
    position: sticky;
    top: 0;
  }
}
```

### Expected output CSS
```css
@supports (position: sticky) {
  .search-results {
    position: sticky;
    top: 0;
  }
}
```

Given the configuration option, and the fact that the `@supports` block effectively causes non-supporting browsers to skip over the content inside — wouldn't it make sense that autoprefixer _didn't_ prefix anything inside said `@supports` block?

**Comment by ai** [comment]
Nice idea, but I will not have time for this during next few weeks.

Do you want to send PR?

**Comment by frippz** [comment]
Hmm, I will at least give it a look. But this would be the first time I'd do something outside of simple DOM manipulation with JavaScript. 😄

**Comment by frippz** [comment]
Well, I gave up. This was clearly outside of my competence area. 😂

**Comment by ai** [comment]
You can remove `-webkit-sticky` by `/* autoprefixer:off */` inside `@supports`

**Comment by Dan503** [comment]
That's an ok temporary solution. The advantage of having Autoprefixer understand `@supports` though is that you can still get prefixing on values not associated with the `@supports` statement inside `@supports`.

**Comment by Dan503** [comment]
Yes it should disable prefixing but only for properties associated with the `@supports` statement.

```css
@supports (display: grid) {
  display: grid; /* should not get prefixed */
  user-select: none; /* should still get prefixed */
}
```
This is really complicated to do though so it's probably likely to have lots of bugs in it if implemented.

There are still the `/* autoprefixer:off */` and `/* autoprefixer: ignore next */` control comments though which are able to achieve the result needed with a bit of extra writing.

```css
@supports (display: grid) {
  /* autoprefixer: ignore next */
  display: grid; /* not prefixed */
  user-select: none; /* still prefixed */
}
```
