### ISSUE TITLE
Ignored `-webkit-`, `-ms-` prefix on `@-moz-document` rules

### ISSUE THREAD

**Issue by denis-g** [postcss/autoprefixer#1271]
NodeJs v10.15.2
NPM v6.13.1

I'm testing `postcss` with `autoprefixer`, and also `gulp-autoprefixer`.
`browserslist` setting is default.

Source scss:
```scss
body {
    appearance: none;
    user-select: none;
}

@-moz-document domain('example.com') {
    body {
        appearance: none;
        user-select: none;
    }
}
```

Output css:
```css
body {
    -webkit-appearance: none;
       -moz-appearance: none;
            appearance: none;
    -webkit-user-select: none;
       -moz-user-select: none;
        -ms-user-select: none;
            user-select: none;
}

@-moz-document domain('example.com') {
    body {
        -moz-appearance: none;
             appearance: none;
        -moz-user-select: none;
             user-select: none;
    }
}
```

Same result on http://autoprefixer.github.io/

**Comment by ai** [comment]
Good idea. Do you want to send PR?

**Comment by ai** [comment]
@denis-g seems like you need to fix this method https://github.com/postcss/autoprefixer/blob/master/lib/prefixer.js#L79-L107

**Comment by ai** [comment]
@denis-g what is a problem here?

Current output seems like OK to me:

```css
body {
    -webkit-appearance: none;
       -moz-appearance: none;
            appearance: none;
    -webkit-user-select: none;
       -moz-user-select: none;
        -ms-user-select: none;
            user-select: none;
}

@-moz-document domain('example.com') {
    body {
        -moz-appearance: none;
             appearance: none;
        -moz-user-select: none;
             user-select: none;
    }
}
```
