### ISSUE TITLE
Grid related css not being outputed for IE

### ISSUE THREAD

**Issue by minuz** [postcss/autoprefixer#1278]
Hi all, I hope I'm doing something silly here...
So I have a grunt library to compile our sass files using grunt-postcss to trigger autoprefixer. 

.browserslistrc
``` 
last 4 versions
ie >= 9
```
Reduced snippet in scss
``` scss
        .inner-wrapper {
          padding: $leader;
          display: grid;
          grid-template-columns: 2fr .5fr .5fr;
          grid-template-rows: 1fr 1fr;
          grid-template-areas:
            'Heading     Price Button'
            'Sub-heading Price Button';
        }
```
The css output...
``` css
#quote-selector .plans li .lhs .inner-wrapper {
  padding: 16px;
  display: grid;
  grid-template-columns: 2fr 0.5fr 0.5fr;
  grid-template-rows: 1fr 1fr;
  grid-template-areas: "Heading     Price Button" "Sub-heading Price Button";
}
```
I can see other ms related prefixes being appended. But for the grid related styles, it's not working for me.

```
"devDependencies": {
    "autoprefixer": "^9.7.4"
} 
```
