### ISSUE TITLE
width/height `stretch` prefixes missing `-webkit-` version

### ISSUE THREAD

**Issue by lunelson** [postcss/autoprefixer#1294]
According to [caniuse](https://caniuse.com/#feat=mdn-css_properties_width_stretch), Safari should get a `-webkit-stretch` version of `stretch` width/height rule

![image](https://user-images.githubusercontent.com/1242864/77299221-6c1ad180-6cec-11ea-9e3e-dc34bb57919f.png)

...however this doesn't appear to be the case with the current demo at https://autoprefixer.github.io/, using the "last 10 years" config:

### Input

```css
/* pre-prefixed */
.stretch {
  width: -webkit-fill-available;
  width: -webkit-stretch;
  width: -moz-available;
  width: stretch;
}

/* non-prefixed */
.stretch {
  width: stretch;
}
```

### Output
```css
/* pre-prefixed */
.stretch {
  width: -webkit-fill-available;
  width: -webkit-stretch;
  width: -moz-available;
  width: stretch;
}

/* non-prefixed */
.stretch {
  width: -webkit-fill-available;
  width: -moz-available;
  width: stretch;
}
```

**Comment by ai** [comment]
Thanks for good issue with all details.

Fixed a38e426

**Comment by ai** [comment]
Released in 9.7.5

**Comment by ai** [comment]
BTW, I like the design of [your website](https://lunelson.xyz/)

**Comment by lunelson** [comment]
Thanks @ai that's so nice to hear! And thanks for the quick fix 😉 !

**Comment by simevidas** [comment]
The `width: stretch` value seems to be non-standard and, more importantly, unspecified. Maybe Autoprefixer should not support such features until they are ready for use.

@lunelson Could you describe your use-case? I’m curious what this value does and what it is useful for.

**Comment by ai** [comment]
Hm, I thought that I saw it in some previous draft.

Maybe they changed the draft because I am still founding [it’s mentions](https://drafts.csswg.org/css-sizing-4/#block-intrinsic) but without definitions.

**Comment by simevidas** [comment]
It was removed from Level 3 in 2017: https://github.com/w3c/csswg-drafts/commit/f5f655bc98a8dfce25473ecf563f230fa3bf6d35.

It will probably be added to Level 4 at some point, but right now there is no definition.

**Comment by lunelson** [comment]
@simevidas my use-case had to do with ensuring that block items with negative horizontal margins (`left`, `right` or both) would expand to the full possible width (which strangely does not happen in all browsers under all conditions). Previously I had done it with explicit widths (`.foo`), but `stretch` does not require knowing the other values (`.bar`):

```css
.foo, .bar {
  margin: 0 -2rem;
}
.foo {
  width: calc(100% + 4rem);
}
.bar {
  width: stretch;
}
```
> The width: stretch value seems to be...completely unspecified. Maybe Autoprefixer should not support such features until they are ready to use.

I'll defer to you and @ai on supporting unspecified features; but this one *was* specified and then removed, thus at least in this case "unspecified" is not strictly the same as "ready to use". This feature works in the majority of browsers, if prefixed, and I have used it successfully.
