### ISSUE TITLE
Grid template areas not being inherited

### ISSUE THREAD

**Issue by Unknow-max** [postcss/autoprefixer#1310]
**Hi everyone,**
Maybe this will be a duplicate issue (I already searched in the closed issues, but  I don't foud anything).

Take this piece of code (grid: no-autoplace) 

```scss



  .l-values-grid {
    grid-gap: 3.5rem 2.5rem;
    grid-template-columns: repeat(3, 1fr);
    grid-template-areas. "value-1 value-2 value-3"
    "value-4 value-5 value-6";
  }
  
.l-values-grid>*:nth-child(1) {
  grid-area: value-1;
}

.l-values-grid>*:nth-child(2) {
  grid-area: value-2;
}

.l-values-grid>*:nth-child(3) {
  grid-area: value-3;
}

.l-values-grid>*:nth-child(4) {
  grid-area: value-4;
}

.l-values-grid>*:nth-child(5) {
  grid-area: value-5;
}

.l-values-grid>*:nth-child(6) {
  grid-area: value-6;
}
  
@media screen and (min-width: 1200px) {

  .l-values-grid {
    grid-gap: 5rem 6.5rem;
    grid-template-columns: repeat(3, 1fr);
  }

}


```

The first part of the code, out of the media query is translated well with the right declarations ecc.
But the second part of the code is a little bit a problem where the final css output prefixed is:

```scss
@media screen and (min-width: 1200px) {
  .l-values-grid {
    grid-gap: 3.5rem 2.5rem;
    -ms-grid-columns: (1fr)[3];
    grid-template-columns: repeat(3, 1fr);
  }
}
```

**Instead when we add a duplicated `grid-area` all work good. Why autoprefixer cannot "inherit" the grid area declaration?**

**Comment by ai** [comment]
Do you want to send PR with grid area declaration inheriting?

**Comment by Unknow-max** [comment]
What a fast response 😅,
Unfortunately, I don't know  a lot about Js, for that I can't help a lot.
Sorry 😥

**Comment by ai** [comment]
The reason why we do not copy is that it is hard to do it for all cases.

For instance:

```css
.grid {
  grid-template-columns: repeat(3, 1fr);
}

@media (min-width: 900px) {
  grid-template-columns: repeat(4, 1fr);
}

.grid.is-big {
  grid-template-columns: repeat(5, 1fr);
}

@media (min-width: 1200px) {
  grid-gap: 3.5rem 2.5rem;
  // we need to copy from (min-width: 900px) and dublicate .grid.is-big
}
```

Because IE 11 dies and the CSS community doesn’t give a proper support for JS tools, it is very unlikely that somebody will write this complex logic.

Do you have an idea of how we can improve docs to make it clear that you must to duplicate `grid-template-columns`?
