### ISSUE TITLE
Support for :placeholder-shown

### ISSUE THREAD

**Issue by tkrotoff** [postcss/autoprefixer#1311]
Autoprefixer does not currently "translate" :placeholder-shown

(I'm NOT talking about [::placeholder](https://developer.mozilla.org/en-US/docs/Web/CSS/::placeholder) which is a different thing and already supported)

- https://developer.mozilla.org/en-US/docs/Web/CSS/:placeholder-shown#Browser_compatibility
- https://caniuse.com/#feat=css-placeholder-shown
- https://dev.to/thesheebs/comment/aog1

Example 1:

```CSS
input:placeholder-shown {
  border-color: silver;
}
```

```CSS
/* IE >= 10 */
input:-ms-input-placeholder {
  border-color: silver;
}

/* Firefox 4 -> 50 included */
/* After performing some tests, this does not work */
input:-moz-placeholder {
  border-color: silver;
}
```

Example 2:

```CSS
input:not(:placeholder-shown) {
  background-color: red;
}
```

```CSS
/* IE >= 10 */
input:not(:-ms-input-placeholder) {
  background-color: red;
}

/* Firefox 4 -> 50 included */
/* After performing some tests, this does not work */
input:not(:-moz-placeholder) {
  background-color: red;
}
```
