### ISSUE TITLE
Support prefixing `line-clamp`

### ISSUE THREAD

**Issue by jathak** [postcss/autoprefixer#1322]
While the standard [`line-clamp`](https://www.w3.org/TR/css-overflow-3/#line-clamp) property is [not yet supported](https://caniuse.com/#search=line-clamp) in any browsers, the prefixed `-webkit-line-clamp` is unusual in that it is supported in all modern browsers, including Firefox.

`-webkit-line-clamp`, unlike the standard `line-clamp`, also requires `display: -webkit-box` and `-webkit-box-orient: vertical`, so ideally Autoprefixer should add those properties as well.

### Input
```
.example {
  line-clamp: 2;
}
```

### Expected Output (for all current browsers)
```
.example {
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  line-clamp: 2;
}
```

**Comment by ai** [comment]
Thanks for the links, they are very helpful for us.

Unfortunately, because of architectural limits (and project goal), we can’t insert `display: -webkit-box` and `-webkit-box-orient: vertical` (Autoprefixer adds simple prefix and convert syntaxes, but do not work with polyfills).

Imagine if the user will write CSS like this and got an unexpected result because they didn’t know how `line-clamp` is implemented inside:

```css
.bad {
  line-clamp: 2;
  display: inline-block; /* this property will override display: -webkit-box and break the hack */
}
```

What do you think if the user should write (and Autoprefixer will insert only `-webkit-line-clamp: 2`)?

```css
.example {
  display: -webkit-box;
  -webkit-box-orient: vertical;
  line-clamp: 2; /* Autoprefixer will insert -webkit-line-clamp: 2 above */
}
```
