### ISSUE TITLE
:placeholder-shown resulting in out-of-memory builds

### ISSUE THREAD

**Issue by chamby** [postcss/autoprefixer#1323]
First, I apologize for this bug report because I am not a front-end developer and don't have much understanding of CSS or SCSS.

After upgrading our Yarn dependencies I noticed that our webpack build got stuck in a loop and ran out of memory. After bisecting through our indirect dependencies I eventually found that upgrading from `autoprefixer 9.7.6` to `autoprefixer 9.8` resulted in this behavior.

After diffing between `9.7.6` and `9.8` I see that the focus is on the pseudo-selector `:placeholder-shown`. We do make use of this pseudo-selector in our SCSS files. This is where my expertise ends. Maybe we are doing something atypical or it is simply an `autoprefixer` bug, but I don't have the ability to take it much further.

```scss
@mixin float-label-input {
  color: $color-darkSlate;
  &::placeholder {
    opacity: .75;
    transition: all .2s;
  }
  &:placeholder-shown:not(:focus)::placeholder {
      opacity: 0;
  }
}
@mixin float-label-scaled {
  &:placeholder-shown:not(:focus) + * {
    font-size: 12px;
    opacity: .55;
    text-transform: none;
    letter-spacing: normal;
    font-weight: 400;
    @content;
    @include respond-min($sm) {
      font-size: 13px;
    }
    @include respond-min($md) {
      font-size: 14px;
    }
  }
}

...

input, select {
  @include float-label-input;
  width: 100%;
  font-size: 12px;
  padding: 16px 0 10px;
  border: 0;
  border-radius: 0;
  border-bottom: 1px solid #e7e7e7;
  transition: all .2s;
  box-shadow: none;
  @include float-label-scaled {
    top: 18px;
  }
  &:focus {
    outline: none;
    border-color: $color-slate;
  }
  @include respond-min($sm) {
    font-size: 13px;
  }
  @include respond-min($md) {
    font-size: 14px;
  }
}
```

**Comment by Dan503** [comment]
Nice float label mixin! 😄

**Comment by ai** [comment]
1. What is the size of CSS input?
2. What will be if you will replace `:placeholder-shown` to `:Aplaceholder-shown`?
3. What is the full text of the error?

**Comment by chamby** [comment]
I've narrowed the scope after some more effort.

This seems to be a recursion problem with something in my toolchain (`Laravel Mix -> Webpack -> Postcss -> Autoprefixer`) combined with this selector
```css
:placeholder-shown:not(:focus)::placeholder
```

You can see the output inflate as I add more SCSS files to my project.

---

### Autoprefixer Disabled

test.scss INPUT:
```scss
input {
  &:placeholder-shown:not(:focus)::placeholder {
      opacity: 0;
  }
}
```

Laravel Mix config
```JS
{ autoprefixer: false }
```

test.css OUTPUT
```css
input:placeholder-shown:not(:focus)::placeholder {
  opacity: 0;
}
```

---

### Autoprefixer Enabled with One Input File

test.scss INPUT:
```scss
input {
  &:placeholder-shown:not(:focus)::placeholder {
      opacity: 0;
  }
}
```

Laravel Mix config
```JS
{  }
```

test.css OUTPUT
```css
input:placeholder-shown:not(:focus)::-moz-placeholder {
  opacity: 0;
}
input:placeholder-shown:not(:focus):-ms-input-placeholder {
  opacity: 0;
}
input:placeholder-shown:not(:focus)::-ms-input-placeholder {
  opacity: 0;
}
input:-moz-placeholder-shown:not(:focus)::placeholder {
  opacity: 0;
}
input:-ms-input-placeholder:not(:focus)::placeholder {
  opacity: 0;
}
input:placeholder-shown:not(:focus)::placeholder {
  opacity: 0;
}
```


---

### Autoprefixer Enabled with Two Input Files

test.scss INPUT:
```scss
input {
  &:placeholder-shown:not(:focus)::placeholder {
      opacity: 0;
  }
}
```

test-01.scss INPUT:
```scss
```

Laravel Mix config
```JS
{  }
```

test.css OUTPUT
```css
input:-moz-placeholder-shown:not(:focus)::-moz-placeholder {
  opacity: 0;
}
input:placeholder-shown:not(:focus)::-moz-placeholder {
  opacity: 0;
}
input:-ms-input-placeholder:not(:focus):-ms-input-placeholder {
  opacity: 0;
}
input:placeholder-shown:not(:focus):-ms-input-placeholder {
  opacity: 0;
}
input:-ms-input-placeholder:not(:focus)::-ms-input-placeholder {
  opacity: 0;
}
input:placeholder-shown:not(:focus)::-ms-input-placeholder {
  opacity: 0;
}
input:placeholder-shown:not(:focus):-ms-input-placeholder {
  opacity: 0;
}
input:-ms-input-placeholder:not(:focus)::placeholder {
  opacity: 0;
}
input:placeholder-shown:not(:focus)::-moz-placeholder {
  opacity: 0;
}
input:placeholder-shown:not(:focus):-ms-input-placeholder {
  opacity: 0;
}
input:placeholder-shown:not(:focus)::-ms-input-placeholder {
  opacity: 0;
}
input:-moz-placeholder-shown:not(:focus)::placeholder {
  opacity: 0;
}
input:-ms-input-placeholder:not(:focus)::placeholder {
  opacity: 0;
}
input:placeholder-shown:not(:focus)::placeholder {
  opacity: 0;
}
```

test-01.css OUTPUT
```css
```
