### ISSUE TITLE
Autoprefixer Grid does not prefix align/justify-self if display is set to flex

### ISSUE THREAD

**Issue by Dan503** [postcss/autoprefixer#1335]
I did some investigating on this comment by @nagman https://github.com/postcss/autoprefixer/issues/856#issuecomment-655472900

This works as expected:

```css
/* Input CSS */
.test {
  align-self: center;
  justify-self: end;
}

/* Output CSS */
.test {
  -ms-grid-row-align: center;
      align-self: center;
  -ms-grid-column-align: end;
      justify-self: end;
}
```

However this does not:

```css
/* Input CSS */
.test {
  display: flex;
  align-self: center;
  justify-self: end;
}

/* Output CSS */
.test {
  display: flex;
  align-self: center;
  justify-self: end;
}

/* Expected output CSS */
.test {
  display: flex;
  -ms-grid-row-align: center;
      align-self: center;
  -ms-grid-column-align: end;
      justify-self: end;
}
```

`align-self` and `justify-self` are still valid grid alignment options if the element they are on is a flex container. A flex container can be a grid child.

`align-self` and `justify-self` should just always add the grid prefixes if grid is enabled.
