### ISSUE TITLE
Miss handle of `background-size` under IE8

### ISSUE THREAD

**Issue by aleen42** [postcss/autoprefixer#1346]
As we known that `background-size` property is not supported under IE8 mentioned inside [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/background-size#Browser_compatibility), I hope that autoprefixer can handle it like `opacity`:

```css
/* before */

.figure {
    opacity: .5;
}

/* after */

.figure {
    filter: alpha(opacity=50);
}
```

When it comes to `background-size`:

```css
/* before */

.figure {
    background-size: cover;
    background-image: url(./path/image.jpg);
}

/* after */

.figure {
    background-size: cover;
    background-image: url(./path/image.jpg);
    filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='[hash].jpg', sizingMethod=scale);
}
```

But there is a special situation you need to know is that `src` should be relative to referenced page site, rather than local file system. If we all use postcss to bundle image source and rename with a specified hash, this notice can be ignored.
