### ISSUE TITLE
Different behavior between https://autoprefixer.github.io/ and plugin

### ISSUE THREAD

**Issue by Jbbouille** [postcss/autoprefixer#1347]
Hello,

I am having an issue using autoprefixer as a JS library.

When I use the autoprefixer online with and browserlist `IE 11`:
```css
.example {
    display: grid;
    transition: all .5s;
    user-select: none;
    background: linear-gradient(to bottom, white, black);
}
```
I get:

```css
.example {
    display: -ms-grid;
    display: grid;
    transition: all .5s;
    -ms-user-select: none;
        user-select: none;
    background: linear-gradient(to bottom, white, black);
}
```
But with the js library when I write: 
```js
const autoprefixer = require('autoprefixer');
const postcss = require('postcss');

const css = `
.example {
    display: grid;
    transition: all .5s;
    user-select: none;
    background: linear-gradient(to bottom, white, black);
}
`

postcss([ autoprefixer({overrideBrowserslist: 'IE 11'}) ]).process(css).then(result => {
  result.warnings().forEach(warn => {
    console.warn(warn.toString());
  })
  console.log(result.css);
})
```
I get:
```css
.example {
    display: grid;
    transition: all .5s;
    -ms-user-select: none;
        user-select: none;
    background: linear-gradient(to bottom, white, black);
}
```

I also tried specifying the `from` option with a `browserslist` specified in my `package.json` but I get the same result.

Am I doing something wrong or is there a bug ?
