### ISSUE TITLE
Support for ::before (IE8)

### ISSUE THREAD

**Issue by mishanga** [postcss/autoprefixer#135]
http://caniuse.com/#search=before

``` bash
echo 'a::before{content:""}' | \
    ./node_modules/.bin/autoprefixer -b 'ie 8' -o -
```

Now:

``` css
a::before {
  content: "";
}
```

Want to:

``` css
a:before {
  content: "";
}
```
