### ISSUE TITLE
Placeholder shown

### ISSUE THREAD

**Issue by StepFlow** [postcss/autoprefixer#1356]
Using v9.7.6, browserslist: last 2 versions

This code with pseudo-class ':placeholder-shown' usage
```css
.SiteForm__input:not(:placeholder-shown) {
  color: #828282;
}
```
will be transpiled with autoprefixer without any difference. But if we put another semicolon so it will be looked like pseudo-element
```css
.SiteForm__input:not(::placeholder-shown) {
  color: #828282;
}
```
it will be transpiled to this code 
```css
.SiteForm__input:not(::-webkit-input-placeholder-shown) {
  color: #828282;
}
.SiteForm__input:not(::-moz-placeholder-shown) {
  color: #828282;
}
.SiteForm__input:not(:-ms-input-placeholder-shown) {
  color: #828282;
}
.SiteForm__input:not(::-ms-input-placeholder-shown) {
  color: #828282;
}
.SiteForm__input:not(::placeholder-shown) {
  color: #828282;
}
```
[W3C says](https://drafts.csswg.org/selectors-4/#placeholder) that it's a pseudo-class, so I expected that the first code sample would be transpiled to the last (but with only one colon before placeholder-shown of course). Am I mistaken somewhere?
