### ISSUE TITLE
`width: -moz-fit-content` not added when using `caniuse-lite@1.0.30001165`

### ISSUE THREAD

**Issue by KenjiTakahashi** [postcss/autoprefixer#1381]
Like stated in the title, Firefox prefixed version is not added for `width: fit-content` anymore.
It works after downgrading to any earlier version of `caniuse-lite` (have to make sure `browserslist` is using the older version as well).

**Comment by ai** [comment]
Can you show:

1. Your Browserslist config
2. Small input example
3. Current output
4. Old correct output

**Comment by KenjiTakahashi** [comment]
Sure!

Browserslistrc:
```
> 1% in US
not dead
```

Input:
```css
.__header-sec {
    width: fit-content;
}
```

New output:
```css
.__header-sec {
    width: -webkit-fit-content;
    width: fit-content;
}
```

Old output:
```css
.__header-sec {
    width: -webkit-fit-content;
    width: -moz-fit-content;
    width: fit-content;
}
```
