### ISSUE TITLE
Can not find grid areas: intentional-left-blank 

### ISSUE THREAD

**Issue by loominade** [postcss/autoprefixer#1386]
lets say I have a grid layout, where I want to draw ab H where certain regions are intentionally left blank:

```css
.grid {
  grid-gap: 1px;
  grid-template-columns: repeat(3, 1fr);
  grid-template-rows: repeat(3, 1fr);
  grid-template-areas: 'left top-void    right'
                       'left center      right'
                       'left bottom-void right' 
}

.grid__left {
  grid-area: left;
}

.grid__center {
  grid-area: center;
}

.grid__right {
  grid-area: right;
}
```

The build would produce the following warning

> Can not find grid areas: top-void, bottom-void

But having empty grid areas is perfectly valid, isn't it? What should I do to solve this warning?
