### ISSUE TITLE
autoprefixer grid: off not working properly

### ISSUE THREAD

**Issue by sKopheK** [postcss/autoprefixer#1393]
hi, try this code, you can use https://autoprefixer.github.io/ to check quickly
```
.fnm .upr-grid__a {
  /* autoprefixer grid: off */
  grid-area: a;
}
.fnm .upr-grid__b {
  /* autoprefixer grid: off */
  grid-area: b;
}
.fnm .upr-grid__c {
  /* autoprefixer grid: off */
  grid-area: c;
}


  .fnm .upr-grid {
    /* autoprefixer grid: off */
    display: grid;
    grid-template-areas: "a b c";
  }
```

why does it prefix stuff? if i put the disabling comment in the root, it works as expected

**Comment by ai** [comment]
`/* autoprefixer grid: off */` works on global layer. Not on per-rule layer:

```css

  /* autoprefixer grid: off */

.fnm .upr-grid__a {
  grid-area: a;
}
.fnm .upr-grid__b {
  grid-area: b;
}
.fnm .upr-grid__c {
  grid-area: c;
}


  .fnm .upr-grid {
    display: grid;
    grid-template-areas: "a b c";
  }
```
