### ISSUE TITLE
b-vendor-order

### ISSUE THREAD

**Issue by jonathanong** [postcss/autoprefixer#14]
``` css
* {
  -moz-box-sizing: border-box;
  box-sizing: b-webkit-order-box;
  box-sizing: b-moz-order-box;
  box-sizing: b-ms-order-box;
  box-sizing: border-box
}

{
  -webkit-transition: b-webkit-order linear 0.2s, box-shadow linear 0.2s;
  -moz-transition: b-moz-order linear 0.2s, box-shadow linear 0.2s;
  -ms-transition: b-ms-order linear 0.2s, box-shadow linear 0.2s;
  -webkit-transition: border linear 0.2s, box-shadow linear 0.2s;
  -o-transition: border linear 0.2s, box-shadow linear 0.2s;
  transition: border linear 0.2s, box-shadow linear 0.2s
}
```

what's going on!? your parser doesn't like `border` or something
