### ISSUE TITLE
Breaking multiple 'and' statements in @media queries

### ISSUE THREAD

**Issue by jpduckwo** [postcss/autoprefixer#1401]
The following media queries (in SCSS) get compiled into incorrect media rules which break the targeting. I have verified this is not coming from SASS and seems to be coming from PostCSS autoprefixer.

```
@media screen and (-webkit-min-device-pixel-ratio: 0) and (min-resolution: 0.001dpcm) {
  .something {
    color: red;
  }
}
```
It compiles to:
```
@media screen and (-webkit-min-device-pixel-ratio: 0) and (-webkit-min-device-pixel-ratio: 0), screen and (-webkit-min-device-pixel-ratio: 0) and (min-resolution: 0.001dpcm)
.something {
    color: red;
}
```
As a workaround it is possible to stop this behaviour by using `/* autoprefixer: off */` however maybe this is something that could be handling in a different way?

See https://github.com/angular/angular-cli/issues/20424

**Comment by ai** [comment]
Is it input sources?

```css
@media screen and (-webkit-min-device-pixel-ratio: 0) and (min-resolution: 0.001dpcm) {
  .something {
    color: red;
  }
}
```

What do you have prefixed, unprefixed, and `and` between them? I do not see a reason for it except some tricky hack.

If you need to support this hack, you can send a PR (but I am not sure about expected output here).
