### ISSUE TITLE
Issues Indent autoprefixer with postcss-cli  how can I fix this?

### ISSUE THREAD

**Issue by HypeNeutron** [postcss/autoprefixer#1429]
### Complaint in SASS compiler on indent problem in my main.prefix.css

> Error: Inconsistent indentation: 5 spaces were used for indentation, but the rest of the document was indented using 2 spaces.

### my cil:

`postcss --use autoprefixer -b 'last 5 versions' assets/css/main.comp.css -o assets/css/main.prefix.css`

### indent in object-fit

```CSS
.card__card-tour img#tourImg {
  width: 100%;
  height: 32rem;
  -o-object-fit: cover;
     object-fit: cover;
  border-top-right-radius: 0.5rem;
  border-top-left-radius: 0.5rem;
}
```
