### ISSUE TITLE
Break inset property to four sides

### ISSUE THREAD

**Issue by amir2mi** [postcss/autoprefixer#1433]
I was wondering if Autoprefixer would break the [`inset`](https://developer.mozilla.org/en-US/docs/Web/CSS/inset) property to `top` `bottom` `left` `right` but it did not. Its browser support is still raw and it is better to convert inset.

It is the use-case for centering elements with absolute position:
### Shorthand:
```css
.box{
   position: absolute;
   inset: 0;
   margin: auto;
}
```
### Better be converted to:
```css
.box{
   position: absolute;
   top: 0;
   right: 0;
   bottom: 0;
   left: 0;
   margin: auto;
}
```
