### ISSUE TITLE
Laravel mix error with grid-template-columns

### ISSUE THREAD

**Issue by maxxwv** [postcss/autoprefixer#1434]
I'm getting the following when using autoprefixer in Laravel mix 6.x with a browserslist including `ie >= 9`:
```
1 WARNING in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
```
If I comment out the `grid-template-columns` line in my scss everything works without issue or warning. Any ideas?

My webpack.mix.js:
```javascript
mix.setPublicPath(process.env.PUBLIC_PATH)
	.js('./js/app.js', `/js`)
  .sass('./scss/app.scss', `/css`)
	.options({
		processCssUrls: true,
		autoprefixer: {
			grid: true
		},
	})
;
```

package.json:
```
{
  "scripts": {
    "dev": "mix",
		"watch": "mix watch",
		"prod": "mix --production"
  },
  "devDependencies": {
    "laravel-mix": "^6",
    "resolve-url-loader": "^4.0.0",
    "sass": "^1.43.3",
    "sass-loader": "^12.2.0"
  },
	"browserslist": [
		"last 2 versions",
		"ie >= 10"
	]
}
```

And finally, my scss:
```scss
.card-panel{
	max-width: calc(3 * 350px);
	display: grid;
	grid-template-columns: repeat(auto-fit, 300px);
	gap: 10px;
}
```
And output css:
```css
.card-panel {
  max-width: 1050px;
  display: -ms-grid;
  display: grid;
  grid-template-columns: repeat(auto-fit, 300px);
  gap: 10px;
}
```
