### ISSUE TITLE
OnceExit usage doesn't work well with other plugins for IE grid.

### ISSUE THREAD

**Issue by romainmenke** [postcss/autoprefixer#1442]
When combining `autoprefixer` with `postcss-custom-properties` I get unexpected CSS.

see : https://github.com/postcss/autoprefixer/commit/8476c1d7fb72d8977403bb75f02d41611fbaf272

Input :

```css
:root {
  --grid-gap: 15px;
}

.test-grid {
    grid-gap: var(--grid-gap);
    grid-template-areas: 'area-a area-b';
    grid-template-columns: repeat(2, 1fr);
}
```

Actual Output :

```css
.test-grid {
    grid-gap: 15px;
    grid-gap: var(--grid-gap);
        grid-template-areas: 'area-a area-b';
    -ms-grid-columns: 1fr var(--grid-gap) 1fr;
    grid-template-columns: repeat(2, 1fr);
}
```

Expected Output :

```css
.test-grid {
	grid-gap: 15px;
	grid-gap: var(--grid-gap);
	    grid-template-areas: 'area-a area-b';
	-ms-grid-columns: 1fr 15px 1fr;
	-ms-grid-columns: 1fr var(--grid-gap) 1fr;
	grid-template-columns: repeat(2, 1fr);
}
```

This worked correctly when `autoprefixer` used `Once`.

As far as I understand the issue seems to happen because `autoprefixer` takes the last value for `grid-gap` to make `-ms-grid-columns` work.

I don't know which properties are affected by this.
Maybe the IE grid magic is the only thing that takes a value from another property in this way?

-----

Is there any context for the change to `OnceExit` ?
