### ISSUE TITLE
CSS Variables

### ISSUE THREAD

**Issue by syahid246** [postcss/autoprefixer#1445]
Hi! I'm using Autoprefixer in Visual Studio Code, and when im run it, its not change css variables to value.
Example, my CSS is :
```css
:root {
  --bg-blue: lightblue;
}
#mydiv {
  background-color: var(--bg-blue);
}
```
Autoprefixer not change anything, im want my CSS convert to :
```css
#mydiv {
  background-color: lightblue;
}
```

Maybe its wrong in extension.... or in build version its same?
