### ISSUE TITLE
unexpected NaN when autoplacing grid for IE

### ISSUE THREAD

**Issue by SukkaW** [postcss/autoprefixer#1446]
Given the code:

```css
.test{grid-row-start:span 3; grid-row-end: 5}
```

autoprefixer (online demo) outputs:

```css
/*
* Prefixed by https://autoprefixer.github.io
* PostCSS: v8.3.6,
* Autoprefixer: v10.3.1
* Browsers: since 2005
*/
.test{-ms-grid-row:span 3;grid-row-start:span 3; -ms-grid-row-span: NaN; grid-row-end: 5}
```

It can also be reproduced in the latest version:

```js
const autoprefixer = require('autoprefixer')
const postcss = require('postcss')

const css = `
/* autoprefixer grid: autoplace */
.test{grid-row-start:span 3; grid-row-end: 5}
`;

postcss([ autoprefixer ]).process(css).then(result => {
  result.warnings().forEach(warn => {
    console.warn(warn.toString())
  })
  console.log(result.css)
});
```

https://runkit.com/sukkaw/postcss-issue-1446
