### ISSUE TITLE
Chrome does not support `animation-name: <string>`

### ISSUE THREAD

**Issue by yisibl** [postcss/autoprefixer#1450]
[Chrome does not currently support](https://bugs.chromium.org/p/chromium/issues/detail?id=423424#c11) animation names with quotation marks, which is not compliant with the CSS [specification](https://www.w3.org/TR/css-animations-1/#typedef-keyframes-name). 

```
<keyframes-name> = <custom-ident> | <string>

For example, the following two @keyframes rules have the same name, so the first will be ignored:
@keyframes foo { ... }
@keyframes "foo" { ... }
```

When quotes are encountered, I think Autoprefixer can automatically remove them to maintain compatibility across all browsers. Otherwise the generated styles won't work in Chrome.

`animation: "foo" 2s both 30` does not work in Chrome.

[parcel-css](https://parcel-css.vercel.app/#%7B%22minify%22%3Afalse%2C%22nesting%22%3Afalse%2C%22customMedia%22%3Afalse%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A1310720%2C%22firefox%22%3A786432%2C%22safari%22%3A655360%2C%22opera%22%3A786432%7D%2C%22source%22%3A%22%40keyframes%20%5C%22foo%5C%22%20%7B%5Cn%20%200%25%20%7B%5Cn%20%20%20%20%20%20color%3A%20pink%3B%5Cn%20%20%7D%5Cn%20%20to%20%7B%5Cn%20%20%20%20%20%20color%3A%20skyblue%3B%5Cn%20%20%7D%5Cn%7D%5Cn%5Cn.test%20%7B%5Cn%20%20animation%3A%202s%20both%2030%3B%5Cn%20%20animation-name%3A%20%5C%22foo%5C%22%3B%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%7D) will remove quotes automatically, I think @devongovett might be able to share more experience.

## Input
```css
@keyframes "foo" {
  0% {
      color: pink;
  }
  to {
      color: skyblue;
  }
}

.test {
  animation: "foo" 2s both 30;
}
```

## Output

```css
/*
* Prefixed by https://autoprefixer.github.io
* PostCSS: v8.3.6,
* Autoprefixer: v10.3.1
* Browsers: > 0%
*/

@-webkit-keyframes "foo" {
  0% {
      color: pink;
  }
  to {
      color: skyblue;
  }
}

@-moz-keyframes "foo" {
  0% {
      color: pink;
  }
  to {
      color: skyblue;
  }
}

@-o-keyframes "foo" {
  0% {
      color: pink;
  }
  to {
      color: skyblue;
  }
}

@keyframes "foo" {
  0% {
      color: pink;
  }
  to {
      color: skyblue;
  }
}

.test {
  -webkit-animation: "foo" 2s both 30;
     -moz-animation: "foo" 2s both 30;
       -o-animation: "foo" 2s both 30;
          animation: "foo" 2s both 30;
}
```

## Expected

Converting all `<string>` to `<custom-ident>` would greatly simplify the learning curve for CSS developers, and **CSS linter** should add a recommended rule to always use `<custom-ident>`.

```css
@-webkit-keyframes foo {
  0% {
    color: pink;
  }

  to {
    color: #87ceeb;
  }
}

@-moz-keyframes foo {
  0% {
    color: pink;
  }

  to {
    color: #87ceeb;
  }
}

@-o-keyframes foo {
  0% {
    color: pink;
  }

  to {
    color: #87ceeb;
  }
}

@keyframes foo {
  0% {
    color: pink;
  }

  to {
    color: #87ceeb;
  }
}

.test {
  -webkit-animation: foo 2s 30 both;
  -moz-animation: foo 2s 30 both;
  -o-animation: foo 2s 30 both;
  animation: foo 2s 30 both;
}
```

If there are whitespace characters, they should be escaped after removing the quotation marks.

```css
@keyframes "foo bar" {}

/* output */
@keyframes foo\ bar {}
```
