### ISSUE TITLE
Normalize font-family quotes for LG browser compatibility?

### ISSUE THREAD

**Issue by nex3** [postcss/autoprefixer#1455]
LG's smart TV browser has a bug where it won't recognize a custom `@font-face` if the `font-family` name doesn't use the same quotes as the original definition. For example:

```css
@font-face {
  font-family: "Foo Bar Baz";
  // ...
}

.classname {
  font: Foo Bar Baz; // This will be ignored
  font: "Foo Bar Baz"; // This will be recognized
}
```

Is it worth Autoprefixer automatically normalizing the quotes for these font names to avoid such an issue?
