### ISSUE TITLE
`-ms-` vendor prefixes not always removed

### ISSUE THREAD

**Issue by sam-ac-dixon** [postcss/autoprefixer#1461]
If you are using an empty browserlist (or `>100%`) to remove existing vendor prefixes the `-ms-` prefix is not always removed.

The output is as expected given the following CSS:

```css
.example {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
}
```
which produces:

```css
.example {
    display: flex;
}
```

But let's modify the input display property from `flex` -> `none`:

```css
.example {
    display: -webkit-box;
    display: -ms-flexbox;
    display: none;
}
```
The `-ms` prefix is not removed from the output as you'd expect:

```css
.example {
    display: -ms-flexbox;
    display: none;
}
```
