### ISSUE TITLE
`text-decoration` prefixing inconsistent

### ISSUE THREAD

**Issue by h3rmanj** [postcss/autoprefixer#1473]
`text-decoration` support was added in #857. However, it doesn't prefix for basic values. This can cause inconsistent situations;

```css
span {
  text-decoration: underline dashed;
}

span.underline-only {
  text-decoration: underline;
}

/* after autoprefix */
span {
  -webkit-text-decoration: underline dashed;
  text-decoration: underline dashed;
}

span.underline-only {
  text-decoration: underline;
}
```

```html
<span class="underline-only">Underlined text</span>
```

The span would then have a normal solid underline in most browsers, but in safari it will prefer the prefixed one, even though it should be overridden.

For my situation, I'm using a third party design system, and don't manage the bundling/processing myself (create-react-app), which makes it hard to debug and fix myself.

The solution would be to always apply the prefix on text-decoration, or have some global property that prefixes all if it has been prefixed once.

**Comment by ai** [comment]
I do not like disable the feature since it will create breaking changes for more users.

What do you think about adding the warning?

**Comment by h3rmanj** [comment]
I'm not sure I understand. I'm not suggesting removing the feature, but adding prefix to `text-decoration` with basic values as well.

Given the output and result in my example, would it not be considered a bug? Is there a specific situation I'm not thinking about that would break?

**Comment by ai** [comment]
Got it!

I am little worry of adding invalid prefixed value. But I agree that we need to fix your case somwhow.

**Comment by ai** [comment]
The problem is that we already do not prefix a few properties if value is not supported.

`check()` is also used in `image-rendering`, `background-clip`, `animation` (and a few grid properties).

It will be strange to fix only one hack.

**Comment by xec** [comment]
As far as I can tell, single value `-webkit-text-decoration` is supported in safari (only tested on iphone)

```css
div {
  /* will apply underline in safari */
  -webkit-text-decoration: underline;
}
```

https://jsfiddle.net/78z36yam/1/

So if autoprefixer would generate css like this I think it would work fine in all cases

```css
/* after autoprefix */
span {
  -webkit-text-decoration: underline dashed;
  text-decoration: underline dashed;
}
span.underline-only {
  -webkit-text-decoration: underline;
  text-decoration: underline;
}
```
