### ISSUE TITLE
either your data or your filter is incorrect

### ISSUE THREAD

**Issue by jonathanong** [postcss/autoprefixer#15]
using rework, i didn't set a filter and i get

``` css
{
  -webkit-transition: b-webkit-order linear 0.2s, box-shadow linear 0.2s;
  -moz-transition: b-moz-order linear 0.2s, box-shadow linear 0.2s;
  -ms-transition: b-ms-order linear 0.2s, box-shadow linear 0.2s;
  -webkit-transition: border linear 0.2s, box-shadow linear 0.2s;
  -o-transition: border linear 0.2s, box-shadow linear 0.2s;
  transition: border linear 0.2s, box-shadow linear 0.2s

  -moz-box-sizing: border-box;
  box-sizing: b-webkit-order-box;
  box-sizing: b-moz-order-box;
  box-sizing: b-ms-order-box;
  box-sizing: border-box
}
```

assuming it's `last 2 versions` by default (when i don't put anything), it's broken: http://caniuse.com/#feat=css-transitions. I should only be seeing `-webkit` for transitions. i should not see `-ms` for box-sizing: http://caniuse.com/#search=box-sizing

or maybe the ones that are like `b-[vendor]-` just shouldn't be there. i think that makes sense.
