### ISSUE TITLE
Converting `inset` to `top`, `right`, `bottom`, `left` breaks with custom properties

### ISSUE THREAD

**Issue by craftedsystems** [postcss/autoprefixer#1531]
If a custom property is used for inset that represents the value for multiple offsets, the converted CSS is broken.

source CSS

```css
p {
  --offset: 0 1rem 2rem 1rem;
  inset: var(--offset);
}
```

processed CSS

```css
p {
  --offset: 0 1rem 2rem 1rem;
  top: var(--offset);
  right: var(--offset);
  bottom: var(--offset);
  left: var(--offset);
}
```

CSS is invalid

```css
p {
  top: 0 1rem 2rem 1rem;
  right: 0 1rem 2rem 1rem;
  bottom: 0 1rem 2rem 1rem;
  left: 0 1rem 2rem 1rem;
}
```
