### ISSUE TITLE
-ms-flex-pack: justify is incorrect, space-between is the correct value

### ISSUE THREAD

**Issue by mgol** [postcss/autoprefixer#165]
The following:

``` css
div {
    justify-content: space-between;
}
```

is translated by Autoprefixer (with default settings) to:

``` css
div {
    -webkit-box-pack: justify;
    -webkit-justify-content: space-between;
    -ms-flex-pack: justify;
    justify-content: space-between;
}
```

but there is no such thing as `-ms-flex-pack: justify;`. It should be `space-between` as with all other versions, see:
http://msdn.microsoft.com/en-us/library/ie/jj127304(v=vs.85).aspx

Compass 1.0.0.alpha.17 does it correctly.
