### ISSUE TITLE
Missing `-moz` prefix for the `::placeholder` selector

### ISSUE THREAD

**Issue by mgol** [postcss/autoprefixer#166]
The following CSS:

``` css
::placeholder {
    color: red;
}
```

gets converted by Autoprefixer (with default settings) to:

``` css
::-webkit-input-placeholder {
    color: red;
}
:-ms-input-placeholder {
    color: red;
}
::placeholder {
    color: red;
}
```

The selector `::-moz-placeholder` is missing.

Compass 1.0.0.alpha.17 does it correctly.
