### ISSUE TITLE
-ms-flex-align: end is incorrect, flex-end is the correct value

### ISSUE THREAD

**Issue by mgol** [postcss/autoprefixer#169]
The following:

``` css
div {
    align-items: flex-end;
}
```

is translated by Autoprefixer (with default settings) to:

``` css
div {
    -webkit-box-align: end;
    -webkit-align-items: flex-end;
    -ms-flex-align: end;
    align-items: flex-end;
}
```

but there is no such thing as `-ms-flex-align: end`. It should be `flex-end` as with all other versions, see:
http://msdn.microsoft.com/en-us/library/ie/jj127304(v=vs.85).aspx

Compass 1.0.0.alpha.17 does it correctly.

See also #165 for a similar issue.
