### ISSUE TITLE
Manually added prefixed rules break source map positions

### ISSUE THREAD

**Issue by mgol** [postcss/autoprefixer#170]
I see misplaced source map line mappings in Chrome. They're usually moved only by a couple of lines which makes me think that my workaround for #165 & similar by manually adding a missing/broken rule like:

``` css
selector {
    // TODO remove the following rule when https://github.com/ai/autoprefixer/issues/165 gets fixed
    -ms-flex-pack: flex-end;
    justify-content: flex-end;
}
```

are not reflected in the final position.

I can try to construct a minimal case if you need it, @ai, but I thought that maybe it would be obvious for you where the problem lies so I haven't tried yet. Let me know if you need it. :)
