### ISSUE TITLE
Option to align prefixed properties by real property name

### ISSUE THREAD

**Issue by paulradzkov** [postcss/autoprefixer#174]
Currently Autoprefixer adds new prefixed properties and aligns them this way:

``` css
.sample {
    /* look at indentation */
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}
```

I would like to have an option to make code automatically aligned like this:

``` css
.sample {
    /* look at indentation */
    -webkit-box-sizing: border-box;
       -moz-box-sizing: border-box;
            box-sizing: border-box;
}
```

Also, if I have my code aligned like above and Autoprefixer removes unnecessary prefixes, the indentation on remaining properties is not changed and I have a few extra spaces:

``` css
.sample {
    /* look at indentation */
       -moz-box-sizing: border-box;
            box-sizing: border-box;
}
```

I would like to have code shifted left and aligned by real property name:

``` css
.sample {
    /* look at indentation */
    -moz-box-sizing: border-box;
         box-sizing: border-box;
}
```

Let the code will be beautiful until Minification
