### ISSUE TITLE
Right prefixes for break-inside

### ISSUE THREAD

**Issue by paulradzkov** [postcss/autoprefixer#177]
Currently autoprefixer expands `break-inside: avoid;` as:

``` css
.sample {
    -webkit-break-inside:avoid;
    -moz-break-inside:avoid;
    break-inside:avoid;
}
```

But working solution at this moment looks like:

``` css
.sample {
  -webkit-column-break-inside: avoid;
            page-break-inside: avoid; /* Makes effect only in Firefox v20+ */
                 break-inside: avoid; /* IE10+, Opera 11.1—12.1 */
}
```

Where webkit prefix has own syntax `-webkit-column-break-inside: avoid` and Firefox uses for it `page-break-inside: avoid` since v.20.

Maybe hack required for prefixing `break-inside :avoid`.
