### ISSUE TITLE
Custom values of prefixed props

### ISSUE THREAD

**Issue by Diokuz** [postcss/autoprefixer#2]
I need, for some reasons, following css code:

``` css
.class {
    transition: all .1s;
    -o-transition: all .2s;
}
```

And I want to generate (with autoprefixer help) something like 

``` css
.class {
    -webkit-transition: all .1s;
    transition: all .1s;
    -o-transition: all .2s;
}
```

but I got

``` css
.class {
    -o-transition: all .2s;
    -o-transition: all .1s;
    -webkit-transition: all .1s;
    transition: all .1s;
}
```

Is it possible to configure autoprefixer in such a way? i.e. I want the possibility to overwrite prefixed props by myself and place it after unprefixed prop.
