### ISSUE TITLE
Block comment on previous line copied

### ISSUE THREAD

**Issue by BBosman** [postcss/autoprefixer#201]
If I run autoprefixer on the following code:

``` css
.test {
    outline: 0; /* Random comment */
    box-shadow: 0 0 8px rgba(82,168,236,.6);
}
```

It is converted to:

``` css
.test {
    outline: 0; /* Random comment */
    -webkit-box-shadow: 0 0 8px rgba(82,168,236,.6); /* Random comment */
    box-shadow: 0 0 8px rgba(82,168,236,.6);
}
```

The comment from the preceding line is copied to the prefixed lines.

This happens with the default settings.
