### ISSUE TITLE
Invalid box-flex keywords

### ISSUE THREAD

**Issue by Rowno** [postcss/autoprefixer#202]
The `auto` and `none` keywords are invalid for `box-flex`.
### Input

``` css
.auto {
    flex: auto;
}

.none {
    flex: none;
}
```
### Output

``` css
.auto {
    -webkit-box-flex: auto;
    -webkit-flex: auto;
    -ms-flex: auto;
    flex: auto; 
}

.none {
    -webkit-box-flex: none;
    -webkit-flex: none;
    -ms-flex: none;
    flex: none; 
}
```
### Expected output

``` css
.auto {
    -webkit-box-flex: 1;
    -webkit-flex: auto;
    -ms-flex: auto;
    flex: auto; 
}

.none {
    -webkit-box-flex: 0;
    -webkit-flex: none;
    -ms-flex: none;
    flex: none; 
}
```
