### ISSUE TITLE
Mechanism doesn't see the second image in multiple gradient

### ISSUE THREAD

**Issue by boronchiev** [postcss/autoprefixer#21]
before:

``` css
BODY {
  background-image:
    linear-gradient(-45deg, transparent 0, transparent 25px, rgba(204, 54, 54, 0.8) 25px, rgba(204, 54, 54, 0.8) 35px, transparent 35px),
    linear-gradient(-45deg, transparent 0, transparent 25px, rgba(54, 104, 154, 0.8) 25px, rgba(54, 104, 154, 0.8) 35px, transparent 35px);
  background-position: 0 100%, 30px 100%;
  background-size: 60px 100%;
  background-repeat: repeat-x;
}
```

after:

``` css
BODY {
  background-image: -webkit-linear-gradient(-45deg, transparent 0, transparent 25px, rgba(204, 54, 54, 0.8) 25px, rgba(204, 54, 54, 0.8) 35px, transparent 35px),
    linear-gradient(-45deg, transparent 0, transparent 25px, rgba(54, 104, 154, 0.8) 25px, rgba(54, 104, 154, 0.8) 35px, transparent 35px);
  background-image: -o-linear-gradient(-45deg, transparent 0, transparent 25px, rgba(204, 54, 54, 0.8) 25px, rgba(204, 54, 54, 0.8) 35px, transparent 35px),
    linear-gradient(-45deg, transparent 0, transparent 25px, rgba(54, 104, 154, 0.8) 25px, rgba(54, 104, 154, 0.8) 35px, transparent 35px);
  background-image: linear-gradient(-45deg, transparent 0, transparent 25px, rgba(204, 54, 54, 0.8) 25px, rgba(204, 54, 54, 0.8) 35px, transparent 35px),
    linear-gradient(-45deg, transparent 0, transparent 25px, rgba(54, 104, 154, 0.8) 25px, rgba(54, 104, 154, 0.8) 35px, transparent 35px);
  background-position: 0 100%, 30px 100%;
  background-size: 60px 100%;
  background-repeat: repeat-x
}
```
