### ISSUE TITLE
Autoprefixer doesn't see few properties in gradients

### ISSUE THREAD

**Issue by boronchiev** [postcss/autoprefixer#214]
For example it's reproduced when i write double white space before color value

`autoprefixer -b "chrome >= 21, ff >= 4" -o after.css before.css`

**before.css**

``` css
.el
{
    background: -webkit-linear-gradient(top,  #f00 0%, #fff 100%);
    background:    -moz-linear-gradient(top,  #f00 0%, #fff 100%);
    background:   linear-gradient(to bottom,  #f00 0%, #fff 100%);
}
```

**after.css**

``` css
.el
{
    background: -webkit-linear-gradient(top,  #f00 0%, #fff 100%);
    background:    -moz-linear-gradient(top,  #f00 0%, #fff 100%);
    background:   -webkit-linear-gradient(top, #f00 0%, #fff 100%);
    background:   -moz-linear-gradient(top, #f00 0%, #fff 100%);
    background:   linear-gradient(to bottom,  #f00 0%, #fff 100%);
}
```
