### ISSUE TITLE
Inherit prefixes from @keyframes

### ISSUE THREAD

**Issue by mishanga** [postcss/autoprefixer#222]
``` bash
$ autoprefixer -v
autoprefixer 1.1.20140319
$ autoprefixer popup.css
```

Source:

``` css
@keyframes popup {
    0% {
        transform: translateX(-10px);
    }
    100% {
        transform: translateX(0);
    }
}
```

Result:

``` css
@-webkit-keyframes popup {
    0% {
        -webkit-transform: translateX(-10px);
        transform: translateX(-10px);
    }
    100% {
        -webkit-transform: translateX(0);
        transform: translateX(0);
    }
}
@keyframes popup {
    0% {
        -webkit-transform: translateX(-10px);
        -ms-transform: translateX(-10px);
        transform: translateX(-10px);
    }
    100% {
        -webkit-transform: translateX(0);
        -ms-transform: translateX(0);
        transform: translateX(0);
    }
}
```

Expected:

``` css
@-webkit-keyframes popup {
    0% {
        -webkit-transform: translateX(-10px);
    }
    100% {
        -webkit-transform: translateX(0);
    }
}
@keyframes popup {
    0% {
        transform: translateX(-10px);
    }
    100% {
        transform: translateX(0);
    }
}
```
