### ISSUE TITLE
Drop `-moz-` prefix for `wavy` property

### ISSUE THREAD

**Issue by shiedman** [postcss/autoprefixer#239]
`text-decoration-style` support added by #209, but is the `-moz-`  prefix really needed for `wavy`?  I check [text-decoration-style](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-style) on MDN, but not found any information about `-moz-wavy`.

when tested on FF24/FF28, `-moz-wavy` is dropped, totally ignored. this is the test:

``` css
  .example1 {    
      -moz-text-decoration-line: underline;
      -moz-text-decoration-color: red;
      -moz-text-decoration-style: -moz-wavy;
  }
  .example2 {    
      -moz-text-decoration-line: underline;
      -moz-text-decoration-color: red;
      -moz-text-decoration-style: wavy;
  }
```

``` html
<p class="example1">This is not working.</p>
<p class="example2">This is working</p>
```

![_moz_wavy](https://cloud.githubusercontent.com/assets/2113350/2739325/c5abbb78-c6a9-11e3-93d2-34b13b247810.jpg)
