### ISSUE TITLE
What about a new syntax for gradients?

### ISSUE THREAD

**Issue by nDmitry** [postcss/autoprefixer#24]
It would be nice to have a fallback for old syntax when we use the new one (with `to` keyword). I mean if I type this:

``` css
.test {
  background-image: linear-gradient(to right bottom, #000, #fff);
}
```

I would like to see this output:

``` css
.test {
  background-image: -webkit-linear-gradient(top left, #000, #fff); /* and other prefixes... */
  background-image: linear-gradient(top left, #000, #fff); /* fallback to old syntax */
  background-image: linear-gradient(to right bottom, #000, #fff);
}
```
