### ISSUE TITLE
Adds -webkit-gradient duplicate property

### ISSUE THREAD

**Issue by arikon** [postcss/autoprefixer#242]
browsers: `android >= 2.3`

Input:

``` css
.a {
    background: -webkit-gradient(linear, 0 0, 0 100%, from(#f4646c), to(#f04650));
    background:         linear-gradient(to bottom, #f4646c, #f04650);
}
```

Output:

``` css
.a {
    background: -webkit-gradient(linear, 0 0, 0 100%, from(#f4646c), to(#f04650));
    background: -webkit-linear-gradient(top, #f4646c, #f04650);
    background: -webkit-gradient(linear, left top, left bottom, from(#f4646c), to(#f04650));
    background:         linear-gradient(to bottom, #f4646c, #f04650);
}
```

Expected output:

``` css
.a {
    background: -webkit-gradient(linear, 0 0, 0 100%, from(#f4646c), to(#f04650));
    background: -webkit-linear-gradient(top, #f4646c, #f04650);
    background:         linear-gradient(to bottom, #f4646c, #f04650);
}
```

Autoprefixer should interpret numeric values and match them to strings `top`, `left`, etc and not produce duplicate property if it is already specified.
