### ISSUE TITLE
Wrong linear-gradient rule processing for Android 2.3 browsers

### ISSUE THREAD

**Issue by narqo** [postcss/autoprefixer#245]
Input CSS:

``` css
.foo
{
    background: linear-gradient(to right top, rgba(255,100,100,.9), rgba(255,100,100,.9) 50%, rgba(0,0,0,0) 50%);
}
```

After applying `autoprefixer` with `last 2 version, android 2.3` as a browsers parameter I have the output CSS:

``` css
.foo
{
    background: -webkit-gradient(linear, , from(rgba(255,100,100,.9)), color-stop(50%, rgba(255,100,100,.9)), to(rgba(0,0,0,0)));
    background: -webkit-linear-gradient(left bottom, rgba(255,100,100,.9), rgba(255,100,100,.9) 50%, rgba(0,0,0,0) 50%);
    background: linear-gradient(to right top, rgba(255,100,100,.9), rgba(255,100,100,.9) 50%, rgba(0,0,0,0) 50%);
}
```

Here you can see, that `-webkit-gradient(linear,..` (first rule) has an incorrect set of parameters.

I use `autoprefixer@1.1.20140410`
