### ISSUE TITLE
Background shorthand is not autoprefixed if color is declared first

### ISSUE THREAD

**Issue by kpeatt** [postcss/autoprefixer#262]
Shorthanding the `background` value with a `color` value before the `linear-gradient` results in no autoprefixing for the gradient value. While color should be written after `linear-gradient`, browsers do not enforce this order so autoprefixer likely shouldn't either.
### Entered value:

``` scss
.shorthand {
  background: red linear-gradient(blue, red);
}
```
### Results:

``` scss
.shorthand {
  background: red linear-gradient(blue, red);
}
```
### Expected Results:

``` scss
.shorthand {
  background: red -webkit-gradient(linear, left top, left bottom, from(blue), to(red));
  background: red -webkit-linear-gradient(blue, red);
  background: red linear-gradient(blue, red);
```
