### ISSUE TITLE
(-moz-)document parsing is broken

### ISSUE THREAD

**Issue by aprescott** [postcss/autoprefixer#27]
The following CSS breaks:

``` css
@-moz-document url-prefix(){
    .ui-select .ui-btn select{
        opacity:.0001
    }
}
```

This showed up as part of some jQuery CSS.

This also breaks:

``` css
@document url-prefix(){
    .ui-select .ui-btn select{
        opacity:.0001
    }
}
```

Output in both cases when reading in a file with the above content:

```
TypeError: 'undefined' is not an object (evaluating 'node.declarations.map')
/Users/adam/.rvm/gems/ruby-1.9.3-p194/gems/execjs-1.4.0/lib/execjs/external_runtime.rb:68:in `extract_result'
/Users/adam/.rvm/gems/ruby-1.9.3-p194/gems/execjs-1.4.0/lib/execjs/external_runtime.rb:28:in `block in exec'
/Users/adam/.rvm/gems/ruby-1.9.3-p194/gems/execjs-1.4.0/lib/execjs/external_runtime.rb:41:in `compile_to_tempfile'
/Users/adam/.rvm/gems/ruby-1.9.3-p194/gems/execjs-1.4.0/lib/execjs/external_runtime.rb:27:in `exec'
/Users/adam/.rvm/gems/ruby-1.9.3-p194/gems/execjs-1.4.0/lib/execjs/external_runtime.rb:19:in `eval'
/Users/adam/.rvm/gems/ruby-1.9.3-p194/gems/execjs-1.4.0/lib/execjs/external_runtime.rb:33:in `call'
/Users/adam/.rvm/gems/ruby-1.9.3-p194/gems/autoprefixer-rails-0.4.20130515/lib/autoprefixer-rails.rb:27:in `compile'
```
