### ISSUE TITLE
weird @keyframes issue

### ISSUE THREAD

**Issue by varemenos** [postcss/autoprefixer#278]
I'm experiencing a weird issue related to `@keyframes`.

I have the following SASS code:

``` scss
@mixin loading(){
    content: "";
    display: inline-block;
    width: 0;
    height: 0;
    border: solid 1em;
    border-radius: 10em;
    border-color: #09f transparent #09f transparent;
    animation: spin 1s linear infinite;

    @keyframes spin{
        0% {
            transform: rotate(0deg);
        }
        100% {
            transform: rotate(360deg);
        }
    }
}

.loader{
    @include loading();
}
```

But the resulting CSS after I preprocess and autoprefix it, is the following:

``` css
.loader {
    content: "";
    display: inline-block;
    width: 0;
    height: 0;
    border: solid 1em;
    border-radius: 10em;
    border-color: #09f transparent #09f transparent;
    -webkit-animation: spin 1s linear infinite;
    animation: spin 1s linear infinite
}
@-webkit-keyframes spin {
    .loader 0% {
        -webkit-transform: rotate(0deg);
        transform: rotate(0deg)
    }
    .loader 100% {
        -webkit-transform: rotate(360deg);
        transform: rotate(360deg)
    }
}
@keyframes spin {
    .loader 0% {
        -webkit-transform: rotate(0deg);
        transform: rotate(0deg)
    }
    .loader 100% {
        -webkit-transform: rotate(360deg);
        transform: rotate(360deg)
    }
}
```

Notice the `.loader` next to each keyframe's percentage value.

I'm not sure whether I screwed something up so bad even autoprefixer couldn't handle it or there is a bug in autoprefixer.
