### ISSUE TITLE
image-mask gets duplicated

### ISSUE THREAD

**Issue by stevenvachon** [postcss/autoprefixer#283]
``` css
rule {
    image-mask: url(...);
}
```

produces:

``` css
rule {
    image-mask: url(...);
    image-mask: url(...);
}
```

**Edit:**
Granted, `image-mask` is incorrect, the issue persists with `mask-image` and `mask`.
