### ISSUE TITLE
Readme continuity

### ISSUE THREAD

**Issue by kieranju** [postcss/autoprefixer#295]
I've read through Autoprefixer's readme and am looking to reword some of it for ease of use and clarity, but have stumbled across a continuity issue to be addressed.

Autoprefixer cleans up redundant, old prefixes. For example, the readme declares that:

``` css
a {
    -webkit-border-radius: 5px;
            border-radius: 5px;
}
```

compiles to:

``` css
a {
    border-radius: 5px;
}
```

**however,** in the Disabling section, it declares that:

If you need some browser specific hack just write prefixed property after unprefixed.

``` css
a {
    transform: scale(0.5);
    -moz-transform: scale(0.6);
}
```

_Does this mean that all redundant prefixed properties that come after the unprefixed one will be ignored by Autoprefixer?_ It's possible that someone might do this by accident. Maybe it would be best to remove this functionality and have users utilize only `/* autoprefixer: off */` to make Autoprefixer ignore certain blocks of code.
