### ISSUE TITLE
transition: filter doesn't work in Chrome

### ISSUE THREAD

**Issue by gaearon** [postcss/autoprefixer#299]
Hi,

``` css
div {
  transition: filter .3s cubic-bezier(0.175, 0.885, 0.32, 1);
}
```

gives you

``` css
div {
  -webkit-transition: -webkit-filter .3s cubic-bezier(0.175, 0.885, 0.32, 1);
          transition: filter .3s cubic-bezier(0.175, 0.885, 0.32, 1);
}
```

This will not, however, work in Chrome, because while prefixless `transition` is supported, prefixless `filter` is not, and the rule is ignored.
