### ISSUE TITLE
Visual Cascade only formats CSS that was affected by autoprefixer

### ISSUE THREAD

**Issue by nathanziarek** [postcss/autoprefixer#300]
Given this code:

``` css
.element {
  color: purple;
  touch-action: manipulation;
}
```

...autoprefixer outputs...

``` css
.btn {
  color: purple;
  -ms-touch-action: manipulation;
      touch-action: manipulation;
}
```

I'd expect it to output...

``` css
.btn {
             color: purple;
  -ms-touch-action: manipulation;
      touch-action: manipulation;
}
```
