### ISSUE TITLE
Transform :nth-child(x) to adjacent selectors (+)

### ISSUE THREAD

**Issue by Calvein** [postcss/autoprefixer#301]
The title isn't great but it's actually pretty easy to understand by example.  
Those are the same:

``` css
li:nth-child(3),
:first-child + * + li {
    same: thing;
}

:nth-child(2),
:first-child + * {
    same: thing-again;
}
```

`E:nth-last-child(n)`, `E:nth-of-type(n)` and `E:nth-last-of-type(n)` can't be achieved this way though.  
Anyway, the good thing is that it `:first-child` works for IE7+, while :nth-child() is IE9+ so it would be great if a transform like this could be implemented.
