### ISSUE TITLE
Issue with gradient not closed

### ISSUE THREAD

**Issue by MoOx** [postcss/autoprefixer#303]
``` css
div {
  background: linear-gradient(red, blue;
}
```

yields into:

``` css
div {
  background: -webkit-linear-gradient(red, blue)linear-gradient(red, blue;;
  background: linear-gradient(red, blue;
}
```
