### ISSUE TITLE
Support media query range context

### ISSUE THREAD

**Issue by jussi-kalliokoski** [postcss/autoprefixer#304]
http://dev.w3.org/csswg/mediaqueries/#mq-range-context

Strictly speaking, not necessarily prefixing, but regardless an incredibly nice CSS feature that is possible to emulate using the old `min-` and `max-` queries, but is terrible pain to emulate by hand.

For example, a use case where you want to serve different size renditions of a background based on the pixel density, you want the default to be a 1x image, then if pixel density is above `1`, serve a 1.3x image. If pixel density is greater than 1.3x, serve a 1.5x image and so on. You don't want to use `min-resolution: 1dppx` since that would serve the 1.3x image on 1x screens. You also don't want to use `max-resolution: 1dppx` because then you don't have a default unless you specify the 1x rendition twice. With the range context feature, this is simple:

``` css
.foo {
    background-image: url(foo-1x.png);
}

@media (resolution > 1dppx) {
    .foo {
        background-image: url(foo-1.3x.png);
    }
}

@media (resolution > 1.3dppx) {
    .foo {
        background-image: url(foo-1.5x.png);
    }
}

@media (resolution > 1.5dppx) {
    .foo {
        background-image: url(foo-2x.png);
    }
}

@media (resolution > 2dppx) {
    .foo {
        background-image: url(foo-3x.png);
    }
}
```

Would be great if you'd consider adding this!
