### ISSUE TITLE
Old flexbox being prefixed with incorrect values

### ISSUE THREAD

**Issue by mrmartineau** [postcss/autoprefixer#312]
I am using grunt-autoprefixer with these settings:

``` js
browsers: ['> 5%', 'last 4 versions', 'firefox > 3.6', 'ie > 7']
```

I am using different `order` values, e.g. `order: 1` and changing it at one breakpoint, and the old, prefixed code has incorrect numbers.

See this codepen for full markup and styles (I do not know what autoprefixer settings it is using): http://codepen.io/mrmartineau/pen/xLCAD

This is the output on my local machine which adds `-webkit-box-ordinal-group: 2;` to `.pagination-btn--prev` (and other incorrect values to other elements) when the value should be `-webkit-box-ordinal-group: 1;`

Shortened code output below (apologies for the long code block in advance):

``` css
.pagination {
  text-align: center;
  display: -webkit-box;
  display: -webkit-flex;
  display: -moz-box;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-orient: horizontal;
  -webkit-box-direction: normal;
  -webkit-flex-direction: row;
     -moz-box-orient: horizontal;
     -moz-box-direction: normal;
      -ms-flex-direction: row;
          flex-direction: row;
  -webkit-flex-wrap: wrap;
      -ms-flex-wrap: wrap;
          flex-wrap: wrap;
  -webkit-justify-content: space-around;
      -ms-flex-pack: distribute;
          justify-content: space-around;
  text-transform: uppercase;
}

.pagination-btn--prev {
  margin-right: 2em;
  -webkit-box-ordinal-group: 2;
  -webkit-order: 1;
     -moz-box-ordinal-group: 2;
      -ms-flex-order: 1;
          order: 1;
}
.pagination-btn--next {
  margin-left: 2em;
  -webkit-box-ordinal-group: 3;
  -webkit-order: 2;
     -moz-box-ordinal-group: 3;
      -ms-flex-order: 2;
          order: 2;
}
@media screen and (min-width: 31.25em) {
  .pagination-btn--next {
    -webkit-box-ordinal-group: 4;
    -webkit-order: 3;
       -moz-box-ordinal-group: 4;
        -ms-flex-order: 3;
            order: 3;
  }
}

.pagination-list {
  display: inline-block;
  -webkit-box-ordinal-group: 4;
  -webkit-order: 3;
     -moz-box-ordinal-group: 4;
      -ms-flex-order: 3;
          order: 3;
  -webkit-flex-basis: 100%;
      -ms-flex-preferred-size: 100%;
          flex-basis: 100%;
}
@media screen and (min-width: 31.25em) {
  .pagination-list {
    -webkit-box-ordinal-group: 3;
    -webkit-order: 2;
       -moz-box-ordinal-group: 3;
        -ms-flex-order: 2;
            order: 2;
    -webkit-flex-basis: auto;
        -ms-flex-preferred-size: auto;
            flex-basis: auto;
  }
}
```

What should I do? Does the other prefixed code look right?
