### ISSUE TITLE
Non-prefixed property not added

### ISSUE THREAD

**Issue by iamvdo** [postcss/autoprefixer#314]
When a code is something like:

``` css
.e {
    -webkit-transition: width 2s;
}
```

Autoprefixer returns 

``` css
.e {
   -webkit-transition: width 2s;
}
```

I thought that it used to returns something like:

``` css
.e {
     -webkit-transition: width 2s;
             transition: width 2s;
}
```

Can you confirm me?

Then it could be possible to use `none` to convert an old stylesheet with prefixed-only properties...
