### ISSUE TITLE
How to deal with private property?

### ISSUE THREAD

**Issue by yisibl** [postcss/autoprefixer#322]
For example

input:

``` css
body {
  -webkit-font-smoothing: antialiased;
}
```

output:

``` css
body {
  -webkit-font-smoothing: antialiased;
   -moz-osx-font-smoothing: grayscale; /* Firefox 25+ */
}
```

Maybe a lot of people do not know that Firefox also supports this feature.
