### ISSUE TITLE
padding-end, padding-start, margin-end and margin-start not supported

### ISSUE THREAD

**Issue by CarlosJeurissen** [postcss/autoprefixer#324]

**Comment by JoernBerkefeld** [comment]
+1

**Comment by ai** [comment]
@yisibl is `margin-block-start` is W3C equivalent of `-moz-margin-start`?

**Comment by ai** [comment]
I sent PR to Can I Use https://github.com/Fyrd/caniuse/pull/865

**Comment by ai** [comment]
Done https://github.com/postcss/autoprefixer-core/commit/33f83d602bbabaad6621f0d794bacb5b48a46921

Unprefixed versions are `margin-inline-start` and `padding-inline-end`

**Comment by yisibl** [comment]
@ai

In CSS specs:

> In the following example, the two rules are equivalent:

```css
blockquote {
  margin: logical 1em 2em 3em 4em;
}
blockquote {
  margin-block-start:  1em; /*  top*/
  margin-inline-end:   2em;/*  right */
  margin-block-end:    3em;/*  bottom */
  margin-inline-start: 4em;/*  left */
}
```
So,their relations should be like this:

```css
  -webkit-margin-start    = margin-inline-start
  -webkit-margin-end      = margin-inline-end
  -webkit-margin-before   = margin-block-start
  -webkit-margin-after    = margin-block-end
```
