### ISSUE TITLE
autoprefix property in CSS @supports parameter

### ISSUE THREAD

**Issue by ImBobby** [postcss/autoprefixer#331]
Properties declared inside CSS @supports parameter don't get parse. Per [@supports spec](http://docs.webplatform.org/wiki/css/atrules/@supports)

``` CSS
@supports ( transition: all .3s ease ) {
    div {
        transition: all .3s ease;
    }
}
```

should be prefixed like this

``` CSS
@supports ( transition: all .3s ease ) or ( -webkit-transition: all .3s ease ) {
    div {
        -webkit-transition: all .3s ease;
        transition: all .3s ease;
    }
}
```

But autoprefix only prefix property declared on div. Here's the output:

``` CSS
@supports (transition: all .3s ease) {
    div {
        -webkit-transition: all .3s ease;
        transition: all .3s ease;
    }
}
```

Will autoprefix add support for this?
