### ISSUE TITLE
Breaking at scale

### ISSUE THREAD

**Issue by ericandrewlewis** [postcss/autoprefixer#351]
Autoprefixer doesn't seem to scale well.

I've found a choke point in my example at 28621 lines of CSS, repeating the ruleset a lot (here's a [gist](https://gist.github.com/ericandrewlewis/ebcc3ba3fe53dfbac747))

``` css
.a {
    box-sizing: border-box;
}
```

At 28617, autoprefixer takes .558 seconds. at 28621, autoprefixer takes 54 seconds.
