### ISSUE TITLE
Incorrect combining of :fullscreen rule with other rules

### ISSUE THREAD

**Issue by silverwind** [postcss/autoprefixer#354]
AP currently combines these rules into a single group:

``` css
div:not(:fullscreen) { color: red }
div { color: red }
```

With `:fullscreen` being an invalid pseudo class on most browsers, the second rule will become invalid too after processing.
