### ISSUE TITLE
linear-gradient issue

### ISSUE THREAD

**Issue by MoOx** [postcss/autoprefixer#357]
``` css
* {
  background: linear-gradient(var(--a), var(--b));
}
```

gives

``` css
* {
  background: -webkit-linear-gradient(linear-gradient(var(--a), var(--b)), , var(--b)));
  background: linear-gradient(linear-gradient(var(--a), var(--b)), , var(--b)));
}
```

This is totally unexpected :(
