### ISSUE TITLE
Unprefixer PostCSS plugin

### ISSUE THREAD

**Issue by ai** [postcss/autoprefixer#360]
@yisibl suggested that we need some reverse Autoprefixer to clean CSS from any prefixes.

The problem is when developers uses `-webkit-transition` without unprefixed `transition`. It is a absolute evil, but we need to some tools, that can clean the hell:

```css
a {
    -webkit-transition: color 200ms;
    -moz-transition: color 200ms;
}
```

should be compiled to:

```css
a {
    transition: color 200ms;
}
```
