### ISSUE TITLE
Filter transition is not working in Chrome/Opera

### ISSUE THREAD

**Issue by miroslavraska** [postcss/autoprefixer#366]
```
transition: filter ease-in-out 1s;
```

is converted to

```
transition: -webkit-filter ease-in-out 1s, filter ease-in-out 1s;
transition: filter ease-in-out 1s;
```

and it seems that the second transition overwrites the first one with -webkit prefix which is needed for Chrome and Opera to work properly.

Example with generated autoprefixer CSS (transition not working):
http://jsfiddle.net/q9fjt04f/

Example with second transtion removed (transition working):
http://jsfiddle.net/6fxfhuu9/

Tested on Chrome 39 + Opera 26.

**Comment by ai** [comment]
Fixed https://github.com/postcss/autoprefixer-core/commit/c3ad975a7a44077d0ad241cc3f4c4911227378da

**Comment by ai** [comment]
Released today in 5.1

**Comment by dwightjack** [comment]
Hi,

i'm having an issue with transition and filter as well.

My stack is:

* SCSS with libsass
* grunt autoprefixer 2.2.0 with autoprefixer core 5.1.3
* task `browsers` option set at `['> 1%', 'last 2 versions', 'Firefox ESR', 'Opera 12.1', 'ie 9']`

SCSS source:
```
filter: blur(100px);
transition: filter 2s ease;
```

CSS output: 
```
  -webkit-filter: blur(100px);
          filter: blur(100px);
  -webkit-transition: -webkit-filter 2s ease, filter 2s ease;
          transition: filter 2s ease;
```

Am i missing something?

**Comment by ai** [comment]
Seems like some old  webkit becoome more popular and returned to selection.

**Comment by dwightjack** [comment]
Thanks for the reply,

so how do i have to tweak the browser support to get the right output?

```
transition: -webkit-filter 2s ease, filter 2s ease;
```

**Comment by ai** [comment]
This is a hot fix. Later I try to find some better solution.

**Comment by arcanis** [comment]
Would it be an acceptable solution to put the `-webkit-transition` below the unprefixed one?

```
        transition: filter .3s;
-webkit-transition: -webkit-filter .3s;
```

**Comment by ai** [comment]
Nope, because it broke Autoprefixer clean.

```js
var prefixed = autoprefixer.process(origin).css;
var clean     = autoprefixer({ browsers: [] }).process(prefixed).css;
clean == prefixed;
```

It important for text editor plugins for example. People in text editor can call Autoprefixer twice on same CSS.

**Comment by arcanis** [comment]
Hm, and using -webkit-filter everywhere filter is used?
```
-webkit-transition: -webkit-filter .3s;
        transition: filter .3s, -webkit-filter .3s;
```
The issue is that it breaks `transition-*` properties, since they don't use the same parameter list anymore : /

**Comment by cvn** [comment]
I'm still seeing this issue. http://codepen.io/cvn/pen/oXGYBO

I'll use the workaround for now.

**Comment by zanona** [comment]
Perhaps the issue should be re-opened? The only way to get it working is to use the workaround, but I believe the bug still exists?

**Comment by ai** [comment]
@zanona what browser exactly you use and what input send to Autoprefixer?

**Comment by zanona** [comment]
Hey @ai, I am using Safari.

with a similar input as @miroslavraska.
```
transition: filter .3s;
```
I hope this helps.

**Comment by ai** [comment]
Fixed https://github.com/postcss/autoprefixer-core/commit/50ea7bb2d2054f9a7f05e6c9c2725c6cac2e6ed9

**Comment by yisibl** [comment]
We must be support other  properties:

input:

```css
.foo {
    transition: filter 2s, backdrop-filter .36s;
}
```

output:

```css
.foo {
-webkit-transition: -webkit-filter 2s, -webkit-backdrop-filter .36s, filter 2s, backdrop-filter .36s;
            transition: -webkit-filter 2s, -webkit-backdrop-filter .36s, filter 2s, backdrop-filter .36s;
}
```

**Comment by yisibl** [comment]
@ai I think there are more similar properties.

**Comment by ai** [comment]
@yisibl yeap, I think we should use `-webkit-filter` for every properties.

**Comment by yisibl** [comment]
input:

```css
.foo{
  transition: transform 1s;
}
```

output:

```css
.foo {
  -webkit-transition: transform 1s;
          transition: transform 1s;
}
```

right?
