### ISSUE TITLE
Support image-rendering

### ISSUE THREAD

**Issue by yisibl** [postcss/autoprefixer#367]
## Specs(CR)

http://dev.w3.org/csswg/css-images-3/#the-image-rendering

## The standard value:

* auto
* crisp-edges
* pixelated

### optimize-contrast’ = ‘crisp-edges’

>  Changed the ‘optimize-contrast’ value to ‘crisp-edges’, and rewrote the description slightly to reduce confusion in what it does.
> http://www.w3.org/TR/2011/WD-css3-images-20110712/#changes

```css
img {
  image-rendering: -webkit-optimize-contrast;/* Webkit (non-standard naming) */
  image-rendering:          -moz-crisp-edges;         /* Firefox */
  image-rendering:            -o-crisp-edges;         /* Opera */
  -ms-interpolation-mode:   nearest-neighbor;  /* IE (non-standard property) */
  image-rendering:               crisp-edges;
}
```

##  optimizeSpeed and optimizeQuality

This property previously accepted the values `optimizeSpeed` and `optimizeQuality`. These are now deprecated; a user agent must accept them as valid values but must treat them as having the same behavior as `auto`, and authors must not use them.

MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering
More:

* http://stackoverflow.com/questions/20678639/image-rendering-crisp-edges-vs-pixelated
