### ISSUE TITLE
Support @viewport

### ISSUE THREAD

**Issue by yisibl** [postcss/autoprefixer#380]
```css
@-o-viewport {
  width: 320px;
}

@-ms-viewport {
  width: auto;
}
```

We need to increase the caniuse.com data.

* https://developer.mozilla.org/zh-CN/docs/Web/CSS/@viewport
* http://msdn.microsoft.com/en-us/library/ie/hh869615%28v=vs.85%29.aspx
* https://dev.opera.com/articles/an-introduction-to-meta-viewport-and-viewport/
