### ISSUE TITLE
Do not remove -webkit-box value if it is hack

### ISSUE THREAD

**Issue by ai** [postcss/autoprefixer#385]
Input:

```css
a {
  display: -webkit-box;
}
```

Output:

```css
a {
}
```

But expected output is same as input.
