### ISSUE TITLE
Removes display:-webkit-flex but doesn't add display:flex

### ISSUE THREAD

**Issue by i-akhmadullin** [postcss/autoprefixer#398]
browsers: `Android 4`

Before
```css
.test {
  display: -webkit-flex;
}
```
After
```css
.test {
}
```
Expected
```css
.test {
  display: flex;
}
```
