### ISSUE TITLE
Asterisk being moved into @keyframes block.

### ISSUE THREAD

**Issue by jnorth** [postcss/autoprefixer#399]
Not sure of a better way to describe this:

```css
.portfolio {
  *zoom: 1;
}

@keyframes portfolio-fadein {
  0%   { opacity: 0; }
  100% { opacity: 1; }
}
```

compiled with autoprefixer 5.0.0 (using gulp-autoprefixer 2.1.0):

```css
.portfolio {
  *zoom: 1; }

@-webkit-keyframes portfolio-fadein {

  *0% {
  *  *opacity: 0; }

  *100% {
  *  *opacity: 1; } }

@keyframes portfolio-fadein {
  0% {
    opacity: 0; }

  100% {
    opacity: 1; } }

```

Can't reproduce on codepen: http://codepen.io/anon/pen/vEZmWw
