### ISSUE TITLE
support font-feature-settings

### ISSUE THREAD

**Issue by ianstormtaylor** [postcss/autoprefixer#40]
hey, it would be awesome if `font-feature-settings` was supported: http://caniuse.com/#feat=font-feature

**Comment by yisibl** [comment]
I found that `font-feature-settings` does not generate the old syntax for older versions of Firefox.

See: [Firefox 4: OpenType font feature support](https://hacks.mozilla.org/2010/11/firefox-4-font-feature-support/#:~:text=stylistic%20set%201%20*/-,%2Dmoz%2Dfont%2Dfeature%2Dsettings,-%3A%20%22dlig%3D1%2Css01)

```css
/*
* Prefixed by https://autoprefixer.github.io
* PostCSS: v8.4.14,
* Autoprefixer: v10.4.7
* Browsers: > 0%
*/

.example {
    -webkit-font-feature-settings: "ss01" 1, "ss08" on;
       -moz-font-feature-settings: "ss01" 1, "ss08" on;
            font-feature-settings: "ss01" 1, "ss08" on;
}
```
