### ISSUE TITLE
code style changed with upgrade to 5.x

### ISSUE THREAD

**Issue by MoOx** [postcss/autoprefixer#400]
This is not a real bug, but more a totally unexpected generated code style.

Input

```css
* {
  transition: transform 1s;
}

@keyframes spin {
  0% { transform: rotate(0deg) }
  100% { transform: rotate(360deg) }
}
```

Expected output (output for v4.x)

```css
* {
  -webkit-transition: -webkit-transform 1s;
          transition: transform 1s;
}

@-webkit-keyframes spin {
  0% { -webkit-transform: rotate(0deg); transform: rotate(0deg) }
  100% { -webkit-transform: rotate(360deg); transform: rotate(360deg) }
}

@keyframes spin {
  0% { -webkit-transform: rotate(0deg); transform: rotate(0deg) }
  100% { -webkit-transform: rotate(360deg); transform: rotate(360deg) }
}
```

Actual output

```css
* {
  -webkit-transition: -webkit-transform 1s;
          transition: transform 1s;
}

@-webkit-keyframes spin {

  0% {
    -webkit-transform: rotate(0deg);
            transform: rotate(0deg);
  }

  100% {
    -webkit-transform: rotate(360deg);
            transform: rotate(360deg);
  }
}

@keyframes spin {
  0% { -webkit-transform: rotate(0deg); transform: rotate(0deg) }
  100% { -webkit-transform: rotate(360deg); transform: rotate(360deg) }
}
```

Let my comment the unexpected change due to 5.0 upgrade

```css
@-webkit-keyframes spin {
/* new \n. Why ?*/
  0% {
    -webkit-transform: rotate(0deg); /*why don't you just do like it was before? You should not add some \n and weird whitespace transformation when it's not asked. */
            transform: rotate(0deg);
  } 
/* another new \n. Same question ?*/
  100% {
    -webkit-transform: rotate(360deg);
            transform: rotate(360deg);
  }
}

/* also after that you edit the normal keyframes correctly. Even more weird :) */
```

I'm not sure if it's intentional or not, but it's pretty weird to bring this kind of unexpected output.
