### ISSUE TITLE
Do not remove at-rules code styles

### ISSUE THREAD

**Issue by ai** [postcss/autoprefixer#401]
Input:

```css
* {
  transition: transform 1s;
}

@keyframes spin {
  0% { transform: rotate(0deg) }
  100% { transform: rotate(360deg) }
}
```

Output:

```css
@-webkit-keyframes spin {

  0% {
    -webkit-transform: rotate(0deg);
            transform: rotate(0deg);
  }

  100% {
    -webkit-transform: rotate(360deg);
            transform: rotate(360deg);
  }
}

@keyframes spin {
  0% { -webkit-transform: rotate(0deg); transform: rotate(0deg) }
  100% { -webkit-transform: rotate(360deg); transform: rotate(360deg) }
}
````

https://github.com/postcss/autoprefixer-core/issues/30
