### ISSUE TITLE
-ms-transform is not being removed web config exclude IE support

### ISSUE THREAD

**Issue by pkuczynski** [postcss/autoprefixer#404]
My ```browserslist``` looks as following:

```
last 2 Chrome versions
last 2 Opera versions
last 2 Firefox versions
```

I am intentionally excluding IE, as we do not want to support it. Still my file contains lines like

```css
@-ms-keyframes spin {
    0% {
        -ms-transform: rotate(0deg)
    }

    100% {
        -ms-transform: rotate(359deg)
    }
}
```

which come from Font Awesome 3.2.1. How do I get rid of those?
