### ISSUE TITLE
-ms-text-size-adjust is not being removed when IE excluded

### ISSUE THREAD

**Issue by pkuczynski** [postcss/autoprefixer#405]
My ```browserslist``` looks as following:

```
last 2 Chrome versions
last 2 Opera versions
last 2 Firefox versions
```

I am intentionally excluding IE, as we do not want to support it. Still my file contains lines like

```css
html {
    -ms-text-size-adjust: 100%
}

img {
    -ms-interpolation-mode: bicubic
}

input:-ms-input-placeholder,textarea:-ms-input-placeholder {
    color: #b7b8bb
}

.bar {
    -ms-animation: progress-bar-stripes 2s linear infinite;
}
```

How do I get rid of those?

**Comment by ai** [comment]
All these examples will not be deleted, because there is no unprefixed version below. So Autoprefixer thinked that it is vendor hacks like `-webkit-transform: translateZ(0)`.

**Comment by ai** [comment]
I recheck them with unprefixed version and only `-ms-interpolation-mode: bicubic;` was keeped.

**Comment by ai** [comment]
Ouh, I forgot that unprefixed form of `-ms-interpolation-mode` is `image-rendering`. Now Autoprefixer deleted it too.

```css
html {
    -ms-text-size-adjust: 100%;
    text-size-adjust: 100%;
}

img {
    -ms-interpolation-mode: bicubic;
    image-rendering: auto;
}


input:-ms-input-placeholder,textarea:-ms-input-placeholder {
    color: #b7b8bb
}

input::placeholder,textarea::placeholder {
    color: #b7b8bb
}

.bar {
    -ms-animation: progress-bar-stripes 2s linear infinite;
    animation: progress-bar-stripes 2s linear infinite;
}
```

↓

```css
html {
    text-size-adjust: 100%;
}

img {
    image-rendering: auto;
}

input::placeholder,textarea::placeholder {
    color: #b7b8bb
}

.bar {
    animation: progress-bar-stripes 2s linear infinite;
}
```

**Comment by pkuczynski** [comment]
So I checked it with the latest autoprefixer-rails-5.1.3 following lines still are not being removed whilst my ```browserslist``` excludes IE:

```
{
-ms-text-size-adjust: 100%
-ms-interpolation-mode: bicubic
}

input:-ms-input-placeholder,textarea:-ms-input-placeholder {
   ...
}
```

How shall I configure my ```browsers list``` to get rid of them?

**Comment by ai** [comment]
Problem is not with `browserslist`, but with CSS.

Autoprefixer will remove `-ms-text-size-adjust` in:

```css
a {
    -ms-text-size-adjust: 100%;
    text-size-adjust: 100%;
}
```

And will not remove in:

```css
a {
    -ms-text-size-adjust: 100%;
}
```

Because last example looks like, that you know, that `-ms-text-size-adjust: 100%`, but you need special hack only for IE.
