### ISSUE TITLE
-moz- prefix being removed from ::selection

### ISSUE THREAD

**Issue by AllThingsSmitty** [postcss/autoprefixer#417]
According to [Mozilla's documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/::selection#compat_hint1) for `::selection` the `-moz-` prefix is required, e.g, `::-moz-selection`. Autoprefixer is removing this.

Original:
```css
::-moz-selection {
  background: #b3d4fc;
}
```
Autoprefixer:
```css
::selection {
  background: #b3d4fc;
 }
```

**Comment by ai** [comment]
I used plain Autoprefixer with default options in [interactive demo](http://simevidas.jsbin.com/gufoko/quiet) and receive this results:

Input:

```css
::selection {
  background: #b3d4fc;
}
```

Output:

```css
::-moz-selection {
  background: #b3d4fc;
}
::selection {
  background: #b3d4fc;
}
```

So, I think problem is in some other tool from your enviroment. Or  maybe you set different browsers list without Firefox.
