### ISSUE TITLE
why is there a comma after the value for webkit-box-flex?

### ISSUE THREAD

**Issue by bassjobsen** [postcss/autoprefixer#426]
input:
```css
e { 
flex: 1, 1, 10px;
}
```
output:
```css
e {
  -webkit-box-flex: 1,;
  -webkit-flex: 1, 1, 10px;
      -ms-flex: 1, 1, 10px;
          flex: 1, 1, 10px;
}
```
