### ISSUE TITLE
mask/mask-image not support the -webkit-linear-gradient()

### ISSUE THREAD

**Issue by yisibl** [postcss/autoprefixer#428]
Use `>0%`

input

```css
.foo{
  mask: linear-gradient(to top, transparent, rgba(0, 0, 0, 0.8) 20px, #000 30px, #000) no-repeat;
}
```

output

```css
.foo{
  -webkit-mask: linear-gradient(to top, transparent, rgba(0, 0, 0, 0.8) 20px, #000 30px, #000) no-repeat;
          mask: linear-gradient(to top, transparent, rgba(0, 0, 0, 0.8) 20px, #000 30px, #000) no-repeat;
}
```

The expected output:

```css
.foo {
  -webkit-mask: -webkit-linear-gradient(bottom, transparent, rgba(0, 0, 0, 0.8) 20px, #000 30px, #000) no-repeat;
  -webkit-mask: linear-gradient(to top, transparent, rgba(0, 0, 0, 0.8) 20px, #000 30px, #000) no-repeat;
          mask: linear-gradient(to top, transparent, rgba(0, 0, 0, 0.8) 20px, #000 30px, #000) no-repeat;
```
