### ISSUE TITLE
Autoprefixer generates selector duplicates

### ISSUE THREAD

**Issue by lifeiscontent** [postcss/autoprefixer#436]
when I write the following SCSS

``` scss
.checkbox-input,
.radio-input,
.text-input,
.textarea-input,
.select-input,
.range-input,
.color-input {
  background-color: map-get($colors, "white");
  border-color: map-get($colors, "gray");
  color: map-get($colors, "black");

  ::placeholder,
  .placeholder {
    color: map-get($colors, "gray-lighter");
  }
}
```

I get the following output.

``` css
.checkbox-input,
.radio-input,
.text-input,
.textarea-input,
.select-input,
.range-input,
.color-input {
  background-color: #FFFFFF;
  border-color: #C8C8CE;
  color: #2D2D2E;
}
/* line 12, ../../../../Workspace/fortitude-sass/app/assets/stylesheets/fortitude/theme/extensions/_input.scss */
.checkbox-input ::-webkit-input-placeholder,
.checkbox-input .placeholder,
.radio-input ::-webkit-input-placeholder,
.radio-input .placeholder,
.text-input ::-webkit-input-placeholder,
.text-input .placeholder,
.textarea-input ::-webkit-input-placeholder,
.textarea-input .placeholder,
.select-input ::-webkit-input-placeholder,
.select-input .placeholder,
.range-input ::-webkit-input-placeholder,
.range-input .placeholder,
.color-input ::-webkit-input-placeholder,
.color-input .placeholder {
  color: #F9F9FA;
}
.checkbox-input ::-moz-placeholder,
.checkbox-input .placeholder,
.radio-input ::-moz-placeholder,
.radio-input .placeholder,
.text-input ::-moz-placeholder,
.text-input .placeholder,
.textarea-input ::-moz-placeholder,
.textarea-input .placeholder,
.select-input ::-moz-placeholder,
.select-input .placeholder,
.range-input ::-moz-placeholder,
.range-input .placeholder,
.color-input ::-moz-placeholder,
.color-input .placeholder {
  color: #F9F9FA;
}
.checkbox-input :-ms-input-placeholder,
.checkbox-input .placeholder,
.radio-input :-ms-input-placeholder,
.radio-input .placeholder,
.text-input :-ms-input-placeholder,
.text-input .placeholder,
.textarea-input :-ms-input-placeholder,
.textarea-input .placeholder,
.select-input :-ms-input-placeholder,
.select-input .placeholder,
.range-input :-ms-input-placeholder,
.range-input .placeholder,
.color-input :-ms-input-placeholder,
.color-input .placeholder {
  color: #F9F9FA;
}
.checkbox-input ::placeholder,
.checkbox-input .placeholder,
.radio-input ::placeholder,
.radio-input .placeholder,
.text-input ::placeholder,
.text-input .placeholder,
.textarea-input ::placeholder,
.textarea-input .placeholder,
.select-input ::placeholder,
.select-input .placeholder,
.range-input ::placeholder,
.range-input .placeholder,
.color-input ::placeholder,
.color-input .placeholder {
  color: #F9F9FA;
}
```
