### ISSUE TITLE
Support for ::input-placeholder

### ISSUE THREAD

**Issue by kossnocorp** [postcss/autoprefixer#44]
From "[Change an input's HTML5 placeholder color with CSS](http://stackoverflow.com/questions/2610497/change-an-inputs-html5-placeholder-color-with-css)":

``` css
::-webkit-input-placeholder { /* WebKit browsers */
    color:    #999;
}
:-moz-placeholder { /* Mozilla Firefox 4 to 18 */
    color:    #999;
}
::-moz-placeholder { /* Mozilla Firefox 19+ */
    color:    #999;
}
:-ms-input-placeholder { /* Internet Explorer 10+ */
    color:    #999;
}
```

I tried different variations (`::input-placeholder`, `::placeholder`) but seems like it doesn't supports by _autoprefixer_.

Thanks.
