### ISSUE TITLE
Missing final semicolon (addressed in postcss Issue 136, but not here).

### ISSUE THREAD

**Issue by SterlingVix** [postcss/autoprefixer#442]
My CSS output is missing the final semicolon of each block. This is consistent with most of the examples provided on the README.md. Output looks like this:

`  :-webkit-full-screen a {`
`      display: -webkit-box;`
`      display: -webkit-flex;`
`      display: flex /* Missing semicolon */`
`  }`
`  :-moz-full-screen a {`
`      display: flex /* Missing semicolon */`
`}`

This is an issue that was addressed and resolved in postcss release 3.0.6+ on November 2014. See:

https://github.com/postcss/postcss/issues/136

As stated in the issue that generated that issue (https://github.com/postcss/autoprefixer/issues/348), while not strictly required, including the semicolon is advocated as a best practice by many including Google.

**Comment by ai** [comment]
What Autoprefixer and PostCSS versions do you use?

What is CSS input?

**Comment by TrySound** [comment]
@ai https://github.com/postcss/postcss-nested/blob/master/test/test.js#L74-L101
The same problem

**Comment by ai** [comment]
Hm. I understand the problem. Autoprefixer and nested remove style code on nodes moving.

**Comment by SterlingVix** [comment]
"What Autoprefixer and PostCSS versions do you use?"

My package.json lists:

`"autoprefixer-core": "~5.1.11",`
`"grunt-postcss": "~0.3.0",`

**Comment by ai** [comment]
[Can’t reproduce it](http://simevidas.jsbin.com/gufoko/quiet).

Input 1:

```css
:fullscreen a {
    display: flex;
}
```

Output 1:

```css
:-webkit-full-screen a {
    display: -webkit-box;
    display: -webkit-flex;
    display: flex;
}
:-moz-full-screen a {
    display: flex;
}
:-ms-fullscreen a {
    display: -ms-flexbox;
    display: flex;
}
:fullscreen a {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
}
```

Input 2:

```css
:fullscreen a {
    display: flex
}
```

Output 2:

```css
:-webkit-full-screen a {
    display: -webkit-box;
    display: -webkit-flex;
    display: flex
}
:-moz-full-screen a {
    display: flex
}
:-ms-fullscreen a {
    display: -ms-flexbox;
    display: flex
}
:fullscreen a {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex
}
```

Input 3:

```css
:fullscreen a {
    display: flex; /* missed semicolon */
}
```

Output 3:

```css
:-webkit-full-screen a {
    display: -webkit-box;
    display: -webkit-flex;
    display: flex; /* missed semicolon */
}
:-moz-full-screen a {
    display: flex; /* missed semicolon */
}
:-ms-fullscreen a {
    display: -ms-flexbox;
    display: flex; /* missed semicolon */
}
:fullscreen a {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex; /* missed semicolon */
}
```
