### ISSUE TITLE
shorter results in animation

### ISSUE THREAD

**Issue by pikilon** [postcss/autoprefixer#444]
if you have this code
```css
@keyframes myAnimation{
transform:rotate(90deg);
}
```
the result is this one
```css
@-webkit-keyframes myAnimation{
-webkit-transform:rotate(90deg);
        transform:rotate(90deg); /* unnecesary*/
}
@keyframes myAnimation{
-webkit-transform:rotate(90deg);  /* unnecesary*/
        transform:rotate(90deg);
}
```

I think can drop unnecessary lines, can we?
We can save more lines in this example

if you have this code
```css
:fullscreen a {
    transition: transform 1s
}
```
the result now is:
```css
:-webkit-full-screen a {
    -webkit-transition: -webkit-transform 1s;
            transition: transform 1s
}
:-moz-full-screen a {
    transition: transform 1s
}
:-ms-fullscreen a {
    transition: transform 1s
}
:fullscreen a {
    -webkit-transition: -webkit-transform 1s;
            transition: transform 1s
}
 
```
And it could be like this, doesn't it?
```css
:-webkit-full-screen a {
    -webkit-transition: -webkit-transform 1s;
           /* transition: transform 1s */
}
:fullscreen a, :-moz-full-screen a,:-ms-fullscreen a {
    transition: transform 1s
}
 
```

**Comment by ai** [comment]
Nope, we can’t, because Chrome may remove keyframes support early that transform.

**Comment by pikilon** [comment]
I don't get it, sorry.

It doesn't work this code the same way?
```css
@-webkit-keyframes myAnimation{
-webkit-transform:rotate(90deg);
}
@keyframes myAnimation{
        transform:rotate(90deg);
}
```
