### ISSUE TITLE
-webkit-box comes after -webkit-flex

### ISSUE THREAD

**Issue by websirnik** [postcss/autoprefixer#445]
Some vendor libraries, like [Angular Material](https://github.com/angular/material), come with the following css:
```css
.class {
    display: -webkit-flex;
    display: flex;
}
```
This translates into: 
```css
.class {
    display: -webkit-flex;
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
}
```
That creates a problem for Safari 8, when `-webkit-box` comes after ` -webkit-flex`(behaviour is very different, not a flexbox).

Would be great to have initial declaration to translate into 
```css
.class {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
}
```
... which is the current default for `display: flex;` in Autoprefixer.
