### ISSUE TITLE
min-width future syntax

### ISSUE THREAD

**Issue by jlukic** [postcss/autoprefixer#447]
Hi there's new (very useful) [new syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/min-width) as part of the [CSS Intrinsic & Extrinsic Sizing Module Level 3 Working Draft.](http://dev.w3.org/csswg/css3-sizing/#width-height-keywords)

```css
.foo {
  min-width: -webkit-max-content;
  min-width: -moz-max-content;
  min-width: max-content;
}
```

I've noticed that autoprefixer is not prefixing
```css
.foo {
  min-width: max-content;
}
```

Since current stable releases of chrome and firefox both support, perhaps we can add support in autoprefixer? 

Min width `max-content` is very useful in cases where `white-space: nowrap` is used to ensure the parent container is not smaller than the rendered text content.

Thanks for all your hard work and contributions.
