### ISSUE TITLE
flexbugs#8-flex-basis-doesnt-support-calc

### ISSUE THREAD

**Issue by luisrudge** [postcss/autoprefixer#463]
Should autoprefixer handle this specific bug? https://github.com/philipwalton/flexbugs#8-flex-basis-doesnt-support-calc
I'm having this bug with IE11. It would be nice to be able to write the shorthand version and autoprefixer could handle specifying each flexibility property individually. What do you think?

**Comment by ai** [comment]
Nope, we have a [postcss-calc](https://github.com/postcss/postcss-calc) for this.

But we can add it to FAQ.

**Comment by luisrudge** [comment]
I don't think it does what I'm asking for.

I wanted to be able to convert this:

```css
.FlexItem {
  flex: 0 0 calc(100%/3);
}
```

to this: 

```css
.FlexItem {
  flex-grow: 0;
  flex-shrink: 0;
  flex-basis: calc(100%/3); 
}
```

This is the fix for IE11.
