### ISSUE TITLE
-webkit-box over -webkit-flex

### ISSUE THREAD

**Issue by OwenMelbz** [postcss/autoprefixer#474]
Hi,

We're running version 5.2.0 and trying with "last 50 versions" at the moment and start with this css
```
.uk-grid {
  display: flex;
  margin: 0;
  padding: 0;
  list-style: none;
}
```
we're ending up with
```
.uk-grid {
  display: -ms-flexbox;
  display: -webkit-flex;
  display: -webkit-box;
  display: -moz-box;
  display: flex;
  -ms-flex-wrap: wrap;
  -webkit-flex-wrap: wrap;
  flex-wrap: wrap;
  margin: 0;
  padding: 0;
  list-style: none;
}
```
It is putting -webkit-box; after -webkit-flex which means mobile-safari and desktop safari seem to inherit the -webkit-box instead of -webkit-flex and create layout issues as its not handling -webkit-box;

I understand that Safari should use the the correct property definition - however its not - and a fix we've found is simply swap the ordering in the output css - but obviously we cant do this every time we generate the CSS.

Could you please advise how we can potentially resolve the ordering issue?

Thanks

**Comment by ai** [comment]
BTW, `last 50 versions` is a bad practice ;). Set browsers that you really support.

**Comment by ai** [comment]
Seems like some other tool broke your CSS. I enter your input example to [Autoprefixer online demo](http://simevidas.jsbin.com/gufoko/quiet) and got correct

```css
.uk-grid {
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  margin: 0;
  padding: 0;
  list-style: none;
}
```
