### ISSUE TITLE
Extra duplication of properties for transition-property

### ISSUE THREAD

**Issue by Grawl** [postcss/autoprefixer#479]
It duplicates properties too much

Input:

```css
.foo {
	transition-property: filter, opacity;
}
```

Output:

```css
.foo {
	-webkit-transition-property: -webkit-filter, opacity, filter, opacity;
	        transition-property: filter, opacity;
}
```

Expecting:

```css
.foo {
	-webkit-transition-property: -webkit-filter, opacity;
	        transition-property: filter, opacity;
}
```

Live on Codepen: http://codepen.io/Grawl/pen/JdBzmy?editors=010
