### ISSUE TITLE
Safari incorrect behaviour

### ISSUE THREAD

**Issue by khankuan** [postcss/autoprefixer#481]
Hi, the following snippet did not work on the 100% part:
```
@keyframes glow {
  0% { opacity: 0; }
  50% { opacity: 0.5; }
  100% {
    opacity: 0; 
  }
}
```
But this works:
```
@keyframes glow {
  0% { opacity: 0; }
  50% { opacity: 0.5; }
  100% { opacity: 0; }
}
```

**Comment by ai** [comment]
I need input and output or each example.

**Comment by khankuan** [comment]
Here:

@-webkit-keyframes glow{0%{opacity:0}50%{opacity:.5}}
@keyframes glow{0%,to{opacity:0}50%{opacity:.5}to{opacity:0}}

**Comment by ai** [comment]
@khankuan is it output for first input our second?

**Comment by khankuan** [comment]
Hey, im sorry. Use this as reference:

```
@keyframes glow {
  0% { opacity: 0; }
  50% { opacity: 0.5; }
  100% { opacity: 0; }
}
```

gives:

```
@-webkit-keyframes glow{0%{opacity:0}50%{opacity:.5}}@keyframes glow{0%,to{opacity:0}50%{opacity:.5}to{opacity:0}}
```

**Comment by ai** [comment]
I checked your input in [Autoprefixer online demo](http://simevidas.jsbin.com/gufoko/quiet) and got normal result:

```css
@-webkit-keyframes glow {
  0% { opacity: 0; }
  50% { opacity: 0.5; }
  100% { opacity: 0; }
}
@keyframes glow {
  0% { opacity: 0; }
  50% { opacity: 0.5; }
  100% { opacity: 0; }
}
```

So it should be different tool.

@ben-eb can cssnano can broke this CSS? (Webpack uses it)

**Comment by ben-eb** [comment]
@ai Running the last example:

```css
@keyframes glow {
  0% { opacity: 0; }
  50% { opacity: 0.5; }
  100% { opacity: 0; }
}
```

```sh
$ cssnano --no-unused
```

Result:

```css
@keyframes glow{0%{opacity:0}50%{opacity:.5}to{opacity:0}}
```

Which maintains the structure. The `--no-unused` flag is so that cssnano will not remove the rule altogether (as there are no animation rules that reference this keyframes in the input).
