### ISSUE TITLE
Inconsistent Indentation for flex-shrink

### ISSUE THREAD

**Issue by jpotterm** [postcss/autoprefixer#482]
Expected behavior is that running autoprefix on the output of autoprefix should not change anything. Essentially we should have `autoprefix(file) == autoprefix(autoprefix(file))`. This is not working in the case of `flex-shrink` with "latest 2 versions" browser configuration.

Initial input:

```css
.test {
    flex-shrink: 0;
}
```

Initial output:

```css
.test {
    -webkit-flex-shrink: 0;
        -ms-flex-negative: 0;
            flex-shrink: 0;
}
```

Output using previous output as input:

```css
.test {
    -ms-flex-negative: 0;
        -webkit-flex-shrink: 0;
            flex-shrink: 0;
}
```

In the final run the order and indentation are wrong.
