### ISSUE TITLE
Multiple @viewport did not come into effect

### ISSUE THREAD

**Issue by yisibl** [postcss/autoprefixer#485]
input

```css
@viewport {
  max-width: 800px;
}

@viewport {
  zoom: 0.75;
  min-zoom: 0.5;
  max-zoom: 0.9;
}
```

output

```css
@-ms-viewport {
  max-width: 800px;
}

@-o-viewport {
  max-width: 800px;
}

@viewport {
  max-width: 800px;
}

@viewport {
  zoom: 0.75;
  min-zoom: 0.5;
  max-zoom: 0.9;
}
```

See also: https://github.com/yisibl/perfectionist-test/blob/master/output/viewport.css
