### ISSUE TITLE
Add support mask-border

### ISSUE THREAD

**Issue by yisibl** [postcss/autoprefixer#502]
WebKit support old specs (-webkit-) http://www.w3.org/TR/2012/WD-css-masking-20121115/

## All properties

* `mask-box-image-source` => **`mask-border-source`**
* `mask-box-image-slice`     => **`mask-border-slice`**
* `mask-box-image-width`   => **`mask-border-width`**
* `mask-box-image-outset`  => **`mask-border-outset`**
* `mask-box-image-repeat`  => **`mask-border-repeat`**
* `mask-box-image`             => **`mask-border`**

### input:
```css
.foo {
  mask-border-repeat: repeat;
}
```

### output:
```css
.foo {
  -webkit-mask-box-image-repeat: repeat;
             mask-border-repeat: repeat;
}
```

> Only support `<number>`(like 1.3) not `<integer>` in some properties.

## Test case

* https://github.com/yisibl/css3test/commit/517b98e96ebbb2efa450e56f3878dbb74baafac2#diff-ce4097fa41097a3b63603226458faf55R1047

## See also
* https://www.webkit.org/blog/181/css-masks/
* http://www.html5rocks.com/en/tutorials/masking/adobe/
