### ISSUE TITLE
Add support image cross-fade()

### ISSUE THREAD

**Issue by yisibl** [postcss/autoprefixer#505]
## Input:

```css
.foo {
    background-image: cross-fade(20%, url(foo.png) url(bar.png));
    background-image: cross-fade(.63, url(foo.png) url(bar.png));
}
```

## Output:
```css
.foo {
    background-image: -webkit-cross-fade(url(foo.png), url(bar.png), 20%)
    background-image: cross-fade(20%, url(foo.png), url(bar.png));
    background-image: -webkit-cross-fade(url(foo.png), url(bar.png), .63);
    background-image: cross-fade(.63, url(foo.png), url(bar.png));
}
```

https://drafts.csswg.org/css-images-3/#cross-fade-function

```
cross-fade() = cross-fade( <cf-mixing-image> , <cf-final-image>? )
<cf-mixing-image> = <percentage>? && <image>
<cf-final-image> = <image> | <color>
```

> The <percentage> must be between 0% and 100% inclusive; any other value is invalid. If omitted, it defaults to the value 50%.

input: 

```css
.foo {
    background-image: cross-fade(url(foo.png) url(bar.png));
}
```

output: 

```css
.foo {
    background-image: -webkit-cross-fade(url(foo.png), url(bar.png), 0.5);
    background-image: cross-fade(url(foo.png) url(bar.png));
}
```
