### ISSUE TITLE
Add support filter()

### ISSUE THREAD

**Issue by yisibl** [postcss/autoprefixer#506]
Safari 9 support `-webkit-filter()`

## input:

```css
.foo {
  background: filter(url(image.jpg), blur(2px));
  background: filter(cross-fade(url(http://image1.png), url(http://image2.png), 50%), contrast(0.5));
  background: filter(linear-gradient(0deg, white -20%, blue, black 120%), hue-rotate(90deg));
}
```

## output:

```css
.foo {
  background: -webkit-filter(url(image.jpg), blur(2px));
  background: filter(url(image.jpg), blur(2px));
  background: -webkit-filter(-webkit-cross-fade(url(http://image1.png), url(http://image2.png), 50%), contrast(0.5));
  background: filter(-webkit-cross-fade(url(http://image1.png), url(http://image2.png), 50%), contrast(0.5));
  background: -webkit-filter(linear-gradient(0deg, white -20%, blue, black 120%), hue-rotate(90deg));
  background: filter(linear-gradient(0deg, white -20%, blue, black 120%), hue-rotate(90deg));
}
```

```
filter() = filter(
    [ <image> | <string> ], <filter-function-list>
)
<image> = <url> | <image-list> | <element-reference>  | <gradient>
<image-list> = image( [ <image-decl> , ]* [ <image-decl> | <color> ] )

<filter-function-list> = [ <filter-function> | <url> ]+
<filter-function> = <blur()> | <brightness()> | <contrast()> | <drop-shadow()>
| <grayscale()> | <hue-rotate()> | <invert()> | <opacity()> | <sepia()> | <saturate()>
```

* Spec: http://www.w3.org/TR/filter-effects/#FilterCSSImageValue
* More test case: http://trac.webkit.org/browser/trunk/LayoutTests/fast/filter-image/parse-filter-image.html
* http://caniuse.com/#feat=css-filter-function
