### ISSUE TITLE
Doubling of attributes

### ISSUE THREAD

**Issue by jakob101** [postcss/autoprefixer#507]
# input
```css
.blink {
    -webkit-animation: blink 1s;
    -webkit-animation-timing-function: ease-out;
    animation: blink 1s;
}
```

# output
```css
.blink {
    -webkit-animation: blink 1s;
    -webkit-animation-timing-function: ease-out;
    -webkit-animation: blink 1s;
            animation: blink 1s;
}
```

**However, when I reorder:**
# input
```css
.blink {
    -webkit-animation-timing-function: ease-out;
    -webkit-animation: blink 1s;
    animation: blink 1s;
}
```

Then no doubling occurs:
# output
```css
.blink {
    -webkit-animation-timing-function: ease-out;
    -webkit-animation: blink 1s;
    animation: blink 1s;
}
```
