### ISSUE TITLE
Support for ::selection

### ISSUE THREAD

**Issue by porada** [postcss/autoprefixer#51]
``` css
::selection {
    transition: color 0.1s ease-out;
    color: blue;
}
```

:arrow_down:

``` css
::-moz-selection {
    -webkit-transition: color 0.1s ease-out;
    transition: color 0.1s ease-out;
    color: blue;
}

::selection {
    -webkit-transition: color 0.1s ease-out;
    transition: color 0.1s ease-out;
    color: blue;
}
```

[According to MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/::selection#Browser_compatibility), Firefox doesn’t support unprefixed `::selection` selector. Other browsers either support the unprefixed version or don’t support the selector at all, so it’s safe to assume that only the `-moz-` prefix will be needed in the near future.

Unfortunately, this is not covered in Can I Use data (yet).

I was planning to make a pull request for it, but the current architecture doesn’t seem to allow for inserting new selectors easily.
