### ISSUE TITLE
Strange -webkit-min-device-pixel-ratio value when using min-resolution

### ISSUE THREAD

**Issue by crobays** [postcss/autoprefixer#521]
Hi there,

The min-device-pixel-ratio: 3 combined with min-resolution results in a weird prefix value. ratio 2 works fine though.

```css
@media (min-device-pixel-ratio: 2), (min-resolution: 192dpi) {
  .dpi-2 {
    display: block;
  }
}
@media (min-device-pixel-ratio: 3), (min-resolution: 340dpi) {
  .dpi-3 {
    display: block;
  }
}
```
results in

```css
@media (min-device-pixel-ratio: 2), (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi) {
  .dpi-2 {
    display: block;
  }
}
@media (min-device-pixel-ratio: 3), (-webkit-min-device-pixel-ratio: 3.5416666666666665), (min-resolution: 340dpi) {
  .dpi-3 {
    display: block;
  }
}
```

Also on CodePen: http://codepen.io/anon/pen/MayLLg

Thanks,
Maikel
