### ISSUE TITLE
Media query issue

### ISSUE THREAD

**Issue by fronteed** [postcss/autoprefixer#535]
Tested at https://autoprefixer.github.io/

Input:

```css
@media print,
only screen and (-webkit-min-device-pixel-ratio: 1.5),
screen and (min-resolution: 144dpi),
screen and (min-resolution: 144dppx) {
  .header {
    background: currentColor; 
  }
}
```

Output:
```css
@media print,
only screen and (-webkit-min-device-pixel-ratio: 1.5),
screen and (-webkit-min-device-pixel-ratio: 1.5),
screen and (min-resolution: 144dpi),
screen and (-webkit-min-device-pixel-ratio: 144),
screen and (min-resolution: 144dppx) {
  .header {
    background: currentColor; 
  }
}
```

I've already replaced this query with `print, (-webkit-min-device-pixel-ratio: 1.25), (min-resolution: 120dpi)`, thought you should about the strange output anyway, since this may affect some "next day" code.

**Comment by ai** [comment]
@fronteed your input is broken:

1. You use `only screen` in `-webkit-min-device-pixel-ratio` but `screen` in other rules.
2. `144dppx` means 144 device pixel per virtual pixel ;). `dppx` is same meaning as `-webkit-min-device-pixel-ratio`, so correct input will be `1.5dppx`.

So, if you will fix all that:

```css
@media print,
screen and (-webkit-min-device-pixel-ratio: 1.5),
screen and (min-resolution: 144dpi),
screen and (min-resolution: 1.5dppx) {
  .header {
    background: currentColor; 
  }
}
```

output became normal:

```css
@media print,
screen and (-webkit-min-device-pixel-ratio: 1.5),
screen and (min-resolution: 144dpi),
screen and (min-resolution: 1.5dppx) {
  .header {
    background: currentColor; 
  }
}
```
