### ISSUE TITLE
transform rotateZ is not recognized

### ISSUE THREAD

**Issue by thasmo** [postcss/autoprefixer#537]
`transform: rotate(90deg)` does the same as `transform: rotateZ(90deg)` but autoprefixer doesn't recognize it.

**Comment by TrySound** [comment]
@thasmo Show input, output and browsers list.

**Comment by ai** [comment]
@thasmo as I understand `rotateZ` is not supported by IE 9, because `rotateZ` is part of 3D transforms, which are not supported by IE 9. So there is no need for `-ms-` prefix (it is necessary only for IE 9).

@thasmo @yisibl But maybe I am wrong. Can you test, does IE 9 support `rotateZ`.

**Comment by thasmo** [comment]
I thought about falling back to `rotate`, because, yes, IE 9 doesn't support `rotateZ`.
Input:
```css
body {
  transform: rotateZ(90deg);
}
```
Output:
```css
body {
  transform: rotateZ(90deg);
}
```
Expected Output:
```css
body {
  -ms-transform: rotate(90deg);
  transform: rotateZ(90deg);
}
```
