### ISSUE TITLE
cross-fade() prefixer is buggy

### ISSUE THREAD

**Issue by KuraFire** [postcss/autoprefixer#538]
I'm not sure which spec version it's supposed to be using, but right now it seems to be quite broken either way.

Check the Compiled CSS view in these [example code snippets with autoprefixer](http://codepen.io/KuraFire/pen/JYNXLv?editors=110) for how it bungles the output.

**Comment by ai** [comment]
@KuraFire I need input, output and expected output to fix it ;).

@yisibl maybe you can help. You know the browsers and specs the best.

**Comment by KuraFire** [comment]
Input:

```css
.test-crossfade1 {
  background: cross-fade(url("https://s3-us-west-2.amazonaws.com/s.cdpn.io/t-132/actual-result.png"), url("https://s3-us-west-2.amazonaws.com/s.cdpn.io/t-132/expected-result.png"), 50%);
  background-size: 100% 100%;
}

.test-crossfade2 {
  background: cross-fade(50%, url("https://s3-us-west-2.amazonaws.com/s.cdpn.io/t-132/actual-result.png"), url("https://s3-us-west-2.amazonaws.com/s.cdpn.io/t-132/expected-result.png"));
  background-size: 100% 100%;
}

.test-crossfade3 {
  background: cross-fade(url("https://s3-us-west-2.amazonaws.com/s.cdpn.io/t-132/actual-result.png"), url("https://s3-us-west-2.amazonaws.com/s.cdpn.io/t-132/expected-result.png"));
  background-size: 100% 100%;
}
```

Output:

```css
.test-crossfade1 {
  background: -webkit-cross-fade(l("https://s3-us-west-2.amazonaws.com/s.cdpn.io/t-132/actual-result.png"), url("https://s3-us-west-2.amazonaws.com/s.cdpn.io/t-132/expected-result.png"), 50%, s3);
  background: cross-fade(url("https://s3-us-west-2.amazonaws.com/s.cdpn.io/t-132/actual-result.png"), url("https://s3-us-west-2.amazonaws.com/s.cdpn.io/t-132/expected-result.png"), 50%);
  background-size: 100% 100%;
}

.test-crossfade2 {
  background: -webkit-cross-fade(, url("https://s3-us-west-2.amazonaws.com/s.cdpn.io/t-132/actual-result.png"), url("https://s3-us-west-2.amazonaws.com/s.cdpn.io/t-132/expected-result.png"), 50%);
  background: cross-fade(50%, url("https://s3-us-west-2.amazonaws.com/s.cdpn.io/t-132/actual-result.png"), url("https://s3-us-west-2.amazonaws.com/s.cdpn.io/t-132/expected-result.png"));
  background-size: 100% 100%;
}

.test-crossfade3 {
  background: -webkit-cross-fade(l("https://s3-us-west-2.amazonaws.com/s.cdpn.io/t-132/actual-result.png"), url("https://s3-us-west-2.amazonaws.com/s.cdpn.io/t-132/expected-result.png"), s3);
  background: cross-fade(url("https://s3-us-west-2.amazonaws.com/s.cdpn.io/t-132/actual-result.png"), url("https://s3-us-west-2.amazonaws.com/s.cdpn.io/t-132/expected-result.png"));
  background-size: 100% 100%;
}
```
