### ISSUE TITLE
Not removing unnecessary transform-style properties

### ISSUE THREAD

**Issue by himedlooff** [postcss/autoprefixer#539]
Try placing the following into the online demo:

```css
.test-1 {
    -webkit-transform-style: preserve-3d;
    -ms-transform-style: preserve-3d;
    -o-transform-style: preserve-3d;
    transform-style: preserve-3d;
}

.test-2 {
    transform-style: preserve-3d;
}
```

Here's what I'm getting back:

```css
.test-1 {
    -webkit-transform-style: preserve-3d;
    -ms-transform-style: preserve-3d;
    -o-transform-style: preserve-3d;
    transform-style: preserve-3d;
}

.test-2 {
    -webkit-transform-style: preserve-3d;
            transform-style: preserve-3d;
}
```

Shouldn't it remove the `-ms` and `-o` prefixes?
