### ISSUE TITLE
Support `:placeholder` single colon syntax

### ISSUE THREAD

**Issue by MadLittleMods** [postcss/autoprefixer#550]
Currently the single colon version of `:placeholder` doesn't get properly expanded like `::placeholder` does.

```css
.foo:placeholder {
  color: #888;
}
```

Is there some spec that defines the `placeholder` pseudo-class to have double colons?
