### ISSUE TITLE
[Question] @viewport generation

### ISSUE THREAD

**Issue by oleersoy** [postcss/autoprefixer#552]
Bootstrap 4 contains the following:
```css
@at-root {
  @-moz-viewport      { width: device-width; }
  @-ms-viewport       { width: device-width; }
  @-o-viewport        { width: device-width; }
  @-webkit-viewport   { width: device-width; }
  @viewport           { width: device-width; }
}
```
I was thinking could generate the corresponding content with autoprefixer, but it only generates:
```css
@-ms-viewport           { width: device-width; }
@-o-viewport           { width: device-width; }
@viewport           { width: device-width; }
```

Is that because the remaining prefixes are not needed?

TIA,
Ole
