### ISSUE TITLE
Support text-emphasis-position

### ISSUE THREAD

**Issue by yisibl** [postcss/autoprefixer#578]
Old Safari and Chrome support for -webkit-text-emphasis-position. These browsers support over and under as values, but not the added `left` and `right` values required by the spec.

input:
```css
em {
  text-emphasis-position: over right; /* Standard syntax in the specification */
}
```

output:

```css
em {
 -webkit-text-emphasis-position: over;
         text-emphasis-position: over right;
}
```

## Note

WebKit and Blink support over and under as values, but not the added left and right values required by the spec.

That is to say:

```css
-webkit-text-emphasis-position: under ≈ text-emphasis-position: under left;
-webkit-text-emphasis-position: over  ≈ text-emphasis-position: over right;
```

input:

```css
em {
  text-emphasis-position: under;
}
```

output:

```css
em {
 -webkit-text-emphasis-position: under;
         text-emphasis-position: under left;
}
```
[Demo](http://codepen.io/yisi/pen/GoKErz)

@zmmbreeze @ethantw Please review this.

[jquery.emphasis](https://github.com/zmmbreeze/jquery.emphasis/) and [han.css](https://github.com/ethantw/Han) muse be use standard grammar.

**Comment by ai** [comment]
Cool, we have Can I Use page for it: http://caniuse.com/#feat=text-emphasis

Try to fix it at weekend

**Comment by yisibl** [comment]
PR for caniuse: https://github.com/Fyrd/caniuse/pull/2123

**Comment by ai** [comment]
Done 5a9a8bc

**Comment by yisibl** [comment]
Are you going to support this?

input:

```css
em {
  text-emphasis-position: under;
}
```

output:

```css
em {
 -webkit-text-emphasis-position: under;
         text-emphasis-position: under left;
}
```
