### ISSUE TITLE
autoprefixer doesn't add a prefix for box-shadow

### ISSUE THREAD

**Issue by yoav-zibin** [postcss/autoprefixer#586]
Thanks for the awesome project! One tiny thing :)

According to caniuse for box-shadow: 
Global 91.45%	+	0.08%	=	91.53%
unprefixed: 91.21%

Try this test:

```css
.test {
  transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;
}
```

It will create:

```css
.test {
  -webkit-transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;
  transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;
}
```

The correct output should be:

```css
.test {
  -webkit-transition: border-color ease-in-out .15s, -webkit-box-shadow ease-in-out .15s;
  -webkit-transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;
  transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;
}
```
