### ISSUE TITLE
How to reduce the size of the CSS file?

### ISSUE THREAD

**Issue by Borodin** [postcss/autoprefixer#591]
```css
:fullscreen{
    background-image: url("data:image/png;base64,BIGDATA...");
}
```

autoprefixer significantly increases the size of the file
```css
:-webkit-full-screen{
    background-image: url("data:image/png;base64,BIGDATA...");
}
:-moz-full-screen{
    background-image: url("data:image/png;base64,BIGDATA...");
}
:-ms-fullscreen{
    background-image: url("data:image/png;base64,BIGDATA...");
}
:fullscreen{
    background-image: url("data:image/png;base64,BIGDATA...");
}
```
Can it be reduced to this kind of?
```css
:-webkit-full-screen,
:-moz-full-screen,
:-ms-fullscreen,
:-ms-fullscreen{
    background-image: url("data:image/png;base64,...");
}
```
