### ISSUE TITLE
Wrong values when autoprefixer is run after postcss-custom-properties

### ISSUE THREAD

**Issue by andy128k** [postcss/autoprefixer#601]
Following example shows that autoprefixer works incorrectly when value is already processed by another postcss plugin.

```js
var postcss = require("postcss")
var customProperties = require("postcss-custom-properties")
var autoprefixer = require("autoprefixer")

var css = `
:root {
  --main-color: red;
}

.progress-bar {
  background-image:
    repeating-linear-gradient(
      -45deg,
      var(--main-color),
      var(--main-color) 11px,
      #fff 10px,
      #fff 20px /* determines size */
    );
}
`;

function v(css) {
  return postcss().use(customProperties()).process(css).css;
}

function a(css) {
  return postcss().use(autoprefixer()).process(css).css;
}

function av(css) {
  return postcss().use(autoprefixer()).use(customProperties()).process(css).css;
}

function va(css) {
  return postcss().use(customProperties()).use(autoprefixer()).process(css).css;
}

console.log(av(css));
console.log(va(css));
console.log(a(v(css)));
```

Output is:

```css
.progress-bar {
  background-image: -webkit-repeating-linear-gradient(135deg, red, red 11px, #fff 10px, #fff 20px /* determines size */);
  background-image: repeating-linear-gradient(
      -45deg,
      red,
      red 11px,
      #fff 10px,
      #fff 20px 
    );
}


.progress-bar {
  background-image: -webkit-repeating-linear-gradient(135deg, var(--main-color), var(--main-color) 11px, #fff 10px, #fff 20px /* determines size */);
  background-image: repeating-linear-gradient(
      -45deg,
      red,
      red 11px,
      #fff 10px,
      #fff 20px 
    );
}


.progress-bar {
  background-image: -webkit-repeating-linear-gradient(135deg, red, red 11px, #fff 10px, #fff 20px);
  background-image: repeating-linear-gradient(
      -45deg,
      red,
      red 11px,
      #fff 10px,
      #fff 20px 
    );
}
```

Second example contains `--var` expressions which have to be replaced.
Third example shows that error is caused by bad encapsulation.

I believe this commit https://github.com/postcss/autoprefixer/commit/5350d614dbc1aac86da265bae434dcbf2a1e9150 causes the issue.
