### ISSUE TITLE
Compatibility with Flexibility

### ISSUE THREAD

**Issue by jonathantneal** [postcss/autoprefixer#611]
When using [Flexibility](https://github.com/10up/flexibility) with Autoprefixer, the `-js-display: flex` property is being expanded to read:

```css
{
-js-display: -webkit-box;
-js-display: -webkit-flex;
-js-display: -moz-box;
-js-display: -ms-flexbox;
-js-display: flex;
}
```

I’ve been seeing this on the web, but I didn’t know what it was until someone created this issue https://github.com/10up/flexibility/issues/27 today.
