### ISSUE TITLE
Wrong prefixing when using multiple transition-properties where one is transform

### ISSUE THREAD

**Issue by simbo** [postcss/autoprefixer#617]
I am using gulp-postcss 6.1.0 with autoprefixer 6.3.1 with the options `{browsers: ['last 2 versions', '> 0.25%']}`.

The following CSS...

```css
.foo {
  transition-property: top, transform;
}
```

... becomes:

```css
.foo {
  -webkit-transition-property: top,-webkit-transform;
  transition-property: top,-webkit-transform;
  transition-property: top,transform;
  transition-property: top,transform,-webkit-transform;
}
```

As you can see, the last rule adds a third value (and breaks my animation)...

Actually, it should generate to:

```css
.foo {
  -webkit-transition-property: top,-webkit-transform;
  transition-property: top,-webkit-transform;
  transition-property: top,transform;
}
```
