### ISSUE TITLE
break-inside css property resolves to the wrong prefixes

### ISSUE THREAD

**Issue by bertyhell** [postcss/autoprefixer#620]
My css:
```css
.my-class {
  break-inside: avoid-column;
}
```

Resolves to:
```css
.my-class {
    -webkit-break-inside: avoid-column;
    -moz-break-inside: avoid-column;
    break-inside: avoid-column;
}
```

But the correct result is:
```css
.my-class {
    -webkit-column-break-inside: avoid;
    page-break-inside: avoid;
    break-inside: avoid-column;
}
```

I would try to fix this myself, but i'm not familiar with coffeescript

**Comment by ai** [comment]
Why didn’t write `page-break-inside: avoid` which was supported anywhere? https://developer.mozilla.org/en-US/docs/Web/CSS/page-break-inside

**Comment by ai** [comment]
Note to myself about `-webkit-column-break-inside` https://developer.mozilla.org/en-US/docs/Web/CSS/break-inside

**Comment by bertyhell** [comment]
> Why didn’t write page-break-inside: avoid which was supported anywhere?

It seems page-break-inside doesn't get prefixed at all. And doesn't have the desired effect:
![image](https://cloud.githubusercontent.com/assets/1710840/13005259/ffd2509e-d180-11e5-819e-b3fa16b0d700.png)


However if i add the prefixes manually i do get the desired result:
![image](https://cloud.githubusercontent.com/assets/1710840/13005263/0f4478f4-d181-11e5-879a-718584482771.png)

**Comment by ai** [comment]
So if page-break-inside is not equal to break-inside, we should not add  for Firefox?

**Comment by bertyhell** [comment]
> So if page-break-inside is not equal to break-inside, we should not add for Firefox?

Yes, but also add this line:
`page-break-inside: avoid;`

And notice the difference in the webkit prefix:
incorrect:
`-webkit-break-inside: avoid-column;`
correct:
`-webkit-column-break-inside: avoid;`

**Comment by ai** [comment]
> Yes, but also add this line: page-break-inside: avoid;

Why we should add it if you show above that page-break-inside works not like break-inside?

**Comment by bertyhell** [comment]
Because i'm only testing this on chrome.
It might have an effect on some other browser.

I got that prefixed css from here:
http://pleeease.io/play/

**Comment by ai** [comment]
If page-break-inside works differently on Chrome, it will works differently on Firefox too. Do you have any link about why people uses page-break-inside hack in all that snippets? I think it is a bad practice, because it is completely different property and it is not safe to insert it in all cases.

Also page-break inside is not a real prefix. It is seems like polyfill for some cases and Autoprefixer doesn't do a polyfills.

**Comment by ai** [comment]
Current output on [autoprefixer online demo](http://autoprefixer.github.io/):

```css
.example {
    -webkit-column-break-inside: avoid;
       page-break-inside: avoid;
            break-inside: avoid-column;
}
```

Seems like you use outdates version of Autoprefixer.
