### ISSUE TITLE
Remove outdated browser hacks

### ISSUE THREAD

**Issue by montlebalm** [postcss/autoprefixer#638]
I was hoping to use autoprefixer to remove outdated browser hacks. For example, I expected:

```css
.container {
    background: red;
    *background: blue;
    _background: green;
}
```

to translate to:

```css
.container {
    background: red;
}
```

If IE 6 and 7 are not in the list of supported browsers. Was this intentionally left out of the lib? Are there any existing plugins that remove these browser-specific hacks?
