### ISSUE TITLE
Linear gradient nonstandard direction issue

### ISSUE THREAD

**Issue by ntwb** [postcss/autoprefixer#646]
I discovered this via stylelint rule [function-linear-gradient-no-nonstandard-direction](https://github.com/stylelint/stylelint/tree/master/src/rules/function-linear-gradient-no-nonstandard-direction)

```shell
1542:44	⚠  Unexpected nonstandard direction for linear-gradient (function-linear-gradient-no-nonstandard-direction) [stylelint]
```

The CSS:
```css
.foo { 
  background-image: linear-gradient(to left, rgba(255, 255, 255, 1), rgba(255, 255, 255, 0)); 
}
```

Autoprefixer options:
```
Android >= 2.1,Chrome >= 21,Edge >= 12,Explorer >= 7,Firefox >= 17,Opera >= 12.1,Safari >= 6.0
```

Autoprefixer result:
```css
.foo { 
  background-image: -webkit-gradient(linear, right top, left top, from(rgba(255, 255, 255, 1)), to(rgba(255, 255, 255, 0))); 
  background-image: -webkit-linear-gradient(right, rgba(255, 255, 255, 1), rgba(255, 255, 255, 0)); 
  background-image: linear-gradient(to left, rgba(255, 255, 255, 1), rgba(255, 255, 255, 0)); 
}
```

Expected result:
```css
.foo { 
  background-image: -webkit-gradient(linear, right top, left top, from(rgba(255, 255, 255, 1)), to(rgba(255, 255, 255, 0))); 
  background-image: -webkit-linear-gradient(to right, rgba(255, 255, 255, 1), rgba(255, 255, 255, 0)); 
  background-image: linear-gradient(to left, rgba(255, 255, 255, 1), rgba(255, 255, 255, 0)); 
}
```

The difference is line 2 and `to right` instead of `right`

> _"A valid and standard direction value is one of the following: `to` plus a side-or-corner (`to top`, `to bottom`, `to left`, `to right`; `to top right`, `to right top`, `to bottom left`, etc.)"_
