### ISSUE TITLE
Redundant prefixes in @keyframes

### ISSUE THREAD

**Issue by KishanBagaria** [postcss/autoprefixer#647]
1\. Save the following as `foo.css`:
```css
@keyframes foo {
from { transform: scale(1) }
}
```

2\. Run `postcss -u autoprefixer foo.css`

3\. Outputs:
```css
@-webkit-keyframes foo {
from { -webkit-transform: scale(1); transform: scale(1) }
}
@keyframes foo {
from { -webkit-transform: scale(1); transform: scale(1) }
}
```

Expected:
```css
@-webkit-keyframes foo {
from { -webkit-transform: scale(1) }
}
@keyframes foo {
from { transform: scale(1) }
}
```
