### ISSUE TITLE
Disabling specific instance of `@supports` without disabling all prefixes?

### ISSUE THREAD

**Issue by ry5n** [postcss/autoprefixer#652]
At Shopify, we use Sass as out preprocessor, and of course, autoprefixer. I ran into a situation where disabling `@supports` seems to disable prefixing globally, at least at the file level. Example:

```scss
@mixin small-caps {
  font-size: 0.75em;
  text-transform: uppercase;
  letter-spacing: 0.04em;

  @supports (font-feature-settings: 'smcp') {
    font-size: inherit;
    text-transform: initial;
    letter-spacing: initial;
    font-feature-settings: 'smcp';
  }
}
```

The problem is `-webkit-font-feature-settings` gives a false positive in some versions of iOS Safari. I don’t want autoprefixer to add vendor prefixes here. But because `@supports` must be at the top level of the stylesheet, it seems there is no way for me to add the `/* autoprefixer: off */` comment and have it work, other than at the top-level, which disables autoprefixing for the entire compiled stylesheet (obviously not an option). I also don’t want to update my config since I don’t want to disable prefixing for `@supports` across the board. 

If I’m missing something, I’d be grateful for a pointer. Otherwise, it would be ideal to adjust the way these disabling comments work, for example, something like [ESLint’s disabling comments](http://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments). Bonus is that  the way the comments work is quite obvious from reading the code, even with no prior knowledge of the tool.
