### ISSUE TITLE
Wrong `transition:transform` combination output for IE

### ISSUE THREAD

**Issue by pepelsbey** [postcss/autoprefixer#66]
Following `transition: transform` combination generates wrong output:

``` css
a {
    transition: transform 1s;
}
```

The second line is not needed, as property would work only in IE10, but value is aimed to IE9 only.

``` css
a {
    -webkit-transition: -webkit-transform 1s;
    transition: -ms-transform 1s;
    transition: transform 1s;
}
```
