### ISSUE TITLE
Doesn't exclude ms prefixes with display flex

### ISSUE THREAD

**Issue by TrySound** [postcss/autoprefixer#668]
And yeah browserslist shows correct result.
```js
var gulp = require('gulp');
var postcss = require('gulp-postcss');
var autoprefixer = require('autoprefixer');

gulp.task('default', function () {
	return gulp.src('src/header.css')
		.pipe(postcss([
			autoprefixer({
				browsers: 'last 10 versions, not ie <= 11'
			})
		]))
		.pipe(gulp.dest('dist'));
});

```
```css
.component {
	display: flex;
}
```
```css
.component {
	display: -webkit-box;
	display: -webkit-flex;
	display: -ms-flexbox;
	display: flex;
}
```
