### ISSUE TITLE
Autoprefixer stopped working on :global

### ISSUE THREAD

**Issue by xinghul** [postcss/autoprefixer#674]
After applying :global for css modules, autoprefixer skips the parsing:

Here's the source sass:

```sass
:global(.filter-leave.filter-leave-active) {
  opacity: 0.01;
  transform: scale(0.2);

  transition: all 300ms ease-out;
}
```

Compiled css:

```css
.filter-leave.filter-leave-active {
  opacity: 0.01;
  transform: scale(0.2);
  transition: all 300ms ease-out; }
```

Here's my postcss config:
```javascript
{
        test: /\.scss$/,
        loader: ExtractTextPlugin.extract("style-loader", "css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!sass-loader!postcss-loader")
}
......
postcss: function () {
   return [require("postcss-input-range"), require("postcss-sorting"), require("autoprefixer")];
}
```
