### ISSUE TITLE
`transition: transform` output incorrect?

### ISSUE THREAD

**Issue by aaarichter** [postcss/autoprefixer#677]
when having a rule like
```stylus
.test
  transition: transform 250ms
```

with an autoprefixer setting of `browsers: ['last 2 versions', 'ie >= 9', 'safari >= 8', 'iOS >= 8']`
the output is

```css
.test {
  transition: -webkit-transform 250ms;
  transition: transform 250ms;
  transition: transform 250ms, -webkit-transform 250ms;
}
```

Shouldn't it be just:
```css
.test {
  transition: -webkit-transform 250ms;
  transition: transform 250ms;
}
```
