### ISSUE TITLE
`transition: transform` doesn't respect all vendor prefixed `transform` property

### ISSUE THREAD

**Issue by aaarichter** [postcss/autoprefixer#678]
with an autoprefixer setting of browsers: ['last 2 versions', 'ie >= 9', 'safari >= 8', 'iOS >= 8']

when converting the following selector
```stylus
.test
    transform: rotate(0deg)
    transition: transform 250ms
```

I receive
```css
.test {
  -webkit-transform: rotate(0deg);
  -ms-transform: rotate(0deg);
  transform: rotate(0deg);

  transition: -webkit-transform 250ms;
  transition: transform 250ms;
  transition: transform 250ms, -webkit-transform 250ms;
}
```

The `transition` property sets the `-webkit-transform` property but misses `-ms-transform`.

(non critical - just wanted to report this)
