### ISSUE TITLE
Don't use old flexbox syntax when unnecessary

### ISSUE THREAD

**Issue by nstepien** [postcss/autoprefixer#68]
For Chrome 27-28 for example:

``` css
a {
  flex: 1;
}
```

will compile to

``` css
a {
  -webkit-box-flex: 1;
  -webkit-flex: 1;
  flex: 1;
}
```
