### ISSUE TITLE
Properties remain unprefixed in transitions

### ISSUE THREAD

**Issue by nstepien** [postcss/autoprefixer#69]
For Chrome 27-28 for example:

``` css
a {
  transition: border-color .25s, flex .25s;
}
```

will **not** compile to

``` css
a {
  transition: border-color .25s, -webkit-flex .25s;
  transition: border-color .25s, flex .25s;
}
```
