### ISSUE TITLE
Do not remove prefixes when they appers after unprefixed property

### ISSUE THREAD

**Issue by kolonist** [postcss/autoprefixer#694]
Just a little example:

```css
a {
    -webkit-border-radius: 5px;
            border-radius: 5px;
}
```

compiles to:

```css
a {
    border-radius: 5px;
}
```

But
```css
a {
            border-radius: 5px;
    -webkit-border-radius: 5px;
}
```
compiles to:
```css
a {
            border-radius: 5px;
    -webkit-border-radius: 5px;
}
```
