### ISSUE TITLE
need "-moz-" prefix for "linear-gradient"

### ISSUE THREAD

**Issue by chaucerling** [postcss/autoprefixer#709]
```css
.home-index-content .content{
    position: absolute;
    top: 21.1rem;
    z-index: 100;
    /*background: none;*/
    padding: 0 1rem 1rem;
    margin-top: 0;
    /*background: red;*/
    /*background: rgba(0,0,0,0.6);*/
    background: linear-gradient(top,rgba(0, 0, 0, 0),rgba(0, 0, 0, 0.7),rgba(0, 0, 0, 0.7),rgba(0, 0, 0, 0.7),rgba(0, 0, 0, 0.7));
}
```
it genearate into 
![image](https://cloud.githubusercontent.com/assets/6396793/18119847/44953776-6f8f-11e6-9282-c0238f1cbd40.png)
![image](https://cloud.githubusercontent.com/assets/6396793/18119763/dd427188-6f8e-11e6-87f8-125602a7482f.png)

this works fine on max osx 10.11, chrome 52 and safari 9 but does't work on firefox 48. Firefox seem to need to prefix `-moz-`.

![image](https://cloud.githubusercontent.com/assets/6396793/18119922/93f0167e-6f8f-11e6-8334-788d34fe1aec.png)
