### ISSUE TITLE
transforms box-orient: horizontal to vertical

### ISSUE THREAD

**Issue by Bilderbastlerin** [postcss/autoprefixer#71]
``` css
.someClass{
    box-orient: horizontal;
}
```

will turn into this

``` css
.someClass {
  -webkit-box-orient: vertical;
  -webkit-box-direction: normal;
  -webkit-flex-direction: horizontal;
  -moz-box-orient: vertical;
  -moz-box-direction: normal;
  -ms-flex-direction: horizontal;
  box-orient: horizontal;
}
```

the prefixed versions of **box-orient** are now vertical, while the unprefixed line remains horizontal. I had expected the complete output to remain horizontal.
