### ISSUE TITLE
box-sizing vendor specific property is not added

### ISSUE THREAD

**Issue by SuperPat45** [postcss/autoprefixer#710]
Hello,

Autoprefixer does not add  the box-sizing vendor specific property needed for android 2.3, safari < 5.1 and firefox < 29:

-weblit-box-sizing: border-box;
-moz-box-sizing: border-box;

Worse than that, if I manually add it, they will be erased.

My configuration:
    browsers: [
      'Chrome >= 20',
      'Firefox >= 24',
      'Edge >= 12',
      'Explorer >= 10',
      'iOS >= 5',
      'Safari >= 5',
      'Android 2.3',
      'Android >= 4',
      'Opera >= 15'
    ]

**Comment by ai** [comment]
I tested this input:

```css
a {
  box-sizing: border-box
}
```

in [online demo](http://autoprefixer.github.io/) with your requirements and got this result:

```css
a {
  -webkit-box-sizing: border-box;
     -moz-box-sizing: border-box;
          box-sizing: border-box
}
```
