### ISSUE TITLE
Wrong value for -ms-grid-row-align

### ISSUE THREAD

**Issue by smelukov** [postcss/autoprefixer#722]
### input:
```css
.example {
    align-items: flex-end
}
```

### output:
```css
.example {
  -webkit-box-align: end;
  -ms-flex-align: end;
  -ms-grid-row-align: flex-end;
  align-items: flex-end
}
```

But in spec there is no `flex-end` for `-ms-grid-row-align` - https://www.w3.org/TR/2012/WD-css3-grid-layout-20120322/#grid-row-align
And `-ms-grid-row-align: flex-end` does not work in IE

In this case `end` is right value instead of `flex-end`

**Comment by ai** [comment]
What is right for IE?

**Comment by smelukov** [comment]
`-ms-grid-row-align: end` works fine

**Comment by smelukov** [comment]
There is the same problem with `align-items: flex-start`

**Comment by ai** [comment]
start instead if flex-start for IE?

**Comment by smelukov** [comment]
Yep - https://msdn.microsoft.com/ru-ru/library/dn265027(v=vs.85).aspx

**Comment by smelukov** [comment]
Yep https://msdn.microsoft.com/ru-ru/library/hh772256(v=vs.85).aspx

**Comment by ai** [comment]
Seems like `align-items` was removed in Grid spec. I will try to rewrite all Grid support in this weekend.

You could disable `grid: false` to avoid this issue as quick fix.

**Comment by smelukov** [comment]
@ai Thanks ;)

**Comment by smelukov** [comment]
Seems like output must be:
```css
.example {
  -webkit-align-items: flex-end; /*old safari, old chrome, old opera, old android */
  -ms-grid-row-align: end; /* ie with grid */
  -ms-flex-align: end; /* ie10 */
  align-items: flex-end; /* all other */
}
```

**Comment by ai** [comment]
@smelukov we don’t need `-ms-grid-row-align` here ;). It is a Grid, not Flexbox.

Previous Grid spec uses `align-items`, same as flexbox. In current draft they change it.

**Comment by smelukov** [comment]
@ai https://www.w3.org/TR/css-align-3/#overview
In `Applies to` column there is `grid-container` for `align-items` ;)
Yes, this is not `grid` or `flexbox` spec, but AP does not know the context of a rule. Does it?

**Comment by ai** [comment]
@smelukov fuck! so `align-items` could be used for Grid?

**Comment by ai** [comment]
What you think about this fix? 54c0db1

Is it enough or we should fix something other in grid/flexbox support?

**Comment by smelukov** [comment]
@ai Obviously yes... if we'll beleave to spec.
However, -ms-grid-row-align value must be end, not flex-end ;)

**Comment by ai** [comment]
@smelukov `flex-end` is for flexbox, so (as I understand) we don’t need a Grid’s `-ms-grid-row-align` in this case

**Comment by smelukov** [comment]
I've put some comments to commit.
> flex-end is for flexbox

Yes. But if beleave to spec
https://www.w3.org/TR/css-align-3/#overview
align-items can be used for flexbox AND grid containers
If grid is not disabled, then AP should add ms-grid-row/column-align to align-items

**Comment by ai** [comment]
@smelukov yeap, `align-items` could be used for grid and flex. But as I understand only `end` value will use for both. `flex-end` is used only for flexbox. Or I am wrong?

**Comment by ai** [comment]
> flex-start (self, content)
> Only used in flex layout. 

https://www.w3.org/TR/css-align-3/#valdef-self-position-flex-start

**Comment by smelukov** [comment]
Hmmm.... do you mean that AP should not touch flex-* values if grid is on?
Maybe some warning messages? )

**Comment by ai** [comment]
Nope, I mean, that AP should add only flexbox prefixes, and not grid prefixes ;).

Right output is:

```css
.example {
  -webkit-align-items: flex-end; /* old webkit-based browsers */
  /* NOT -ms-grid-row-align: end; */
  -ms-flex-align: end; /* ie10 */
  align-items: flex-end; /* all other */
}
```
