### ISSUE TITLE
`rem` support

### ISSUE THREAD

**Issue by kizu** [postcss/autoprefixer#73]
I'm not sure if that should be an autoprefixer issue, but I think it should be — while it is not something that needs prefixes, it is something that should have a fallback.

However, the implementation of this would be not that trivial: there should be a way to set the root font-size that would be used as a fallback. It could be either a param or in absence of it you could try and find a `html` selector in the CSS, then get the font-size from it.

And when (and if) you've found the root font-size, you could make fallbacks everywhere:

``` CSS
html {
  font-size: 10px;
}
.foo {
  width: 3rem;
}
```

it should be transformed to this by autoprefixer:

``` CSS
html {
  font-size: 10px;
}
.foo {
  width: 30px;
  width: 3rem;
}
```

Also, if the font-size is set to be relative on HTML (in `%` or `em`), you should use it's approximate size in pixels, using `16px` as a base font size and multiplying it on the given relative font-size.

And again: while it is not a “prefix” issue, it is a thing that is non-trivial to emulate in most preprocessors, so it would be really cool if you'd support it.
