### ISSUE TITLE
not getting display: -webkit-flex with any options

### ISSUE THREAD

**Issue by terion-name** [postcss/autoprefixer#734]
Safari 8 needs `display: -webkit-flex`.
With any options I pass — I on't get it. Even with such hardcore as:

``` js
gulp.task('cssOwn:build', () => {
  return gulp.src(path.src.css) // css: 'src/css/styles.scss',
    .pipe(sass({
      includePaths: [path.dist.css],
      errLogToConsole: true
    }))
    .pipe(sass().on('error', sass.logError))
    .pipe(prefixer({
      browser: ['last 10 versions']
    }))
    .pipe(sourcemaps.write('./maps'))
    .pipe(gulp.dest(path.dist.css))
    .pipe(connect.reload())
});
```

This results in:

``` css
ol.o-list {
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  -ms-flex-flow: column;
      flex-flow: column;
  -webkit-box-align: stretch;
      -ms-flex-align: stretch;
          align-items: stretch;
  -webkit-box-pack: justify;
      -ms-flex-pack: justify;
          justify-content: space-between; }
```

It sets `display: -webkit-box;` for Safari 6, but not `display: -webkit-flex` for Safari 8
