### ISSUE TITLE
Cursor grab/grabbing not autoprefixing

### ISSUE THREAD

**Issue by mscarchilli** [postcss/autoprefixer#735]
Autoprefixer is not adding prefixes to cursor grab and grabbing.

grunt-postcss: ^0.8.0
autoprefixer: ^6.5.1

```javascript
    postcss: {
      options: {
        processors: [
        require("autoprefixer")({browsers: 'last 2 versions'})
        ],
        map: {
          inline: false,
          sourcesContent: true,
          prev: "assets/css/main.min.css.map",
          annotation: "assets/css/"
        },
      },
      dist: {
        src: ["assets/css/**/*.css", "!assets/css/vendor/**/*.css"]
      },
    },
```

**Comment by ai** [comment]
I tested in [online demo](http://autoprefixer.github.io/) this input:

```css
.example {
    cursor: grabbing
}
```

and got this output:

```css
.example {
    cursor: -webkit-grabbing;
    cursor: grabbing
}
```

You should check your environment.
