### ISSUE TITLE
@supports (display: flex) is not prefixed

### ISSUE THREAD

**Issue by owenders** [postcss/autoprefixer#750]
The result of gulp-autoprefixer on the following block 
```css
@supports (display: flex) {
  div {
     display: flex;
     /* ... */
  }
}
```
is
```css
@supports (display: flex) {
  div {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    /* ... */
  }
}
```
So the display declaration is well prefixed but, if I'm not wrong, the @supports should be prefixed like this:
```css
@supports (display: -webkit-box) or (display: -webkit-flex) or (display: -ms-flexbox) or (display: flex) {
  div {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    /* ... */
  }
}
```
Is it a bug ? Thank you in advance and sorry if I'm wrong.

**Comment by ai** [comment]
Could you try some flex property instead of display?

**Comment by owenders** [comment]
I just tried with:
```css
@supports (flex: 1) {
  div {
     flex: 1;
     /* ... */
  }
}
```
and it is prefixed like this:
```css
@supports (flex: 1) {
  div {
    -webkit-box-flex: 1;
    -webkit-flex: 1;
    -ms-flex: 1;
    flex: 1;
    /* ... */
  }
}
```

**Comment by ai** [comment]
Strange. Could you try in https://autoprefixer.github.io/

**Comment by owenders** [comment]
Here is the result:
![capture d ecran 2016-12-07 a 16 48 20](https://cloud.githubusercontent.com/assets/8795289/20974608/237fd946-bc9d-11e6-9ee2-a2c15254235c.png)

**Comment by ai** [comment]
Yeap. Seems like we have a bug here. I will look at in on next week (sorry, preparing for conference)

**Comment by ai** [comment]
I found that is was not a bug, but a feature :D.

`-webkit-flex` browsers from your browsers list doesn’t support `@supports`. All your browsers with `@supports` support works with unprefixed flexbox.

Technically only few browsers doesn’t support unprefixed flexbox, but support `@supports`.

You can test my thoughts by `chrome 28` browser in Autoprefixer settings. Output will be:

```css
@supports ((-webkit-flex: 1) or (flex: 1)) {
  div {
     -webkit-flex: 1;
             flex: 1;
  }
}
```

**Comment by ai** [comment]
There is a small real issue — Autoprefixer adds prefixes to `flex: 1`, but not `display: flex`. But because right now there is not browsers for flexbox and `@support` in real use, I think we could ignore this issue.

**Comment by owenders** [comment]
Thank you Andrey for your explanation and in general for your great plugin !

You're right, but wouldn't it be better then that when Autoprefixer doesn't add the prefixes in @supports (...) because of the lack of ```@supports```support, it doesn't add the prefixes in the blocks inside @supports as well ? So instead of having, like now, the following result:

```css
@supports (flex: 1) {
  div {
    -webkit-box-flex: 1;
    -webkit-flex: 1;
    -ms-flex: 1;
    flex: 1;
    /* ... */
  }
}
```

We would have this result:

```css
@supports (flex: 1) {
  div {
    flex: 1;
    /* ... */
  }
}
```
