### ISSUE TITLE
Could not autoprefix `min-device-pixel-ratio`?

### ISSUE THREAD

**Issue by JounQin** [postcss/autoprefixer#753]
Tested in https://autoprefixer.github.io/

input:
``` css
.example {
    display: flex;
    transition: all .5s;
    user-select: none;
    background: linear-gradient(to bottom, white, black);
}

@media (min-device-pixel-ratio: 2) {
    .example {
        transition: all 1s;
    }
}
```

output:
``` css
.example {
    display: -webkit-box;
    display: -webkit-flex;
    display: -moz-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-transition: all .5s;
    -o-transition: all .5s;
    -moz-transition: all .5s;
    transition: all .5s;
    -webkit-user-select: none;
       -moz-user-select: none;
        -ms-user-select: none;
            user-select: none;
    background: -webkit-gradient(linear, left top, left bottom, from(white), to(black));
    background: -webkit-linear-gradient(top, white, black);
    background: -moz-linear-gradient(top, white, black);
    background: -o-linear-gradient(top, white, black);
    background: linear-gradient(to bottom, white, black);
}

@media (min-device-pixel-ratio: 2) {
    .example {
        -webkit-transition: all 1s;
        -o-transition: all 1s;
        -moz-transition: all 1s;
        transition: all 1s;
    }
}
```

I've changed the `browers` to `> 0%`

**Comment by JounQin** [comment]
Sorry it seems should be:

``` css
.example {
    display: flex;
    transition: all .5s;
    user-select: none;
    background: linear-gradient(to bottom, white, black);
}

@media (min-resolution: 2dppx) {
    .example {
        transition: all 1s;
    }
}
```
