### ISSUE TITLE
[Bug] o-tab-size was deleted

### ISSUE THREAD

**Issue by Kristinita** [postcss/autoprefixer#759]
### 1. Summary

`o-tab-size` property delete for me. But in caniuse.com I see, that we need `o-tab-size` for Opera Mini browser: **<http://caniuse.com/#search=tab-size>**.

### 2. Expected behavior

Not remove `o-tab-size` property.

### 3. Actual behavior

Remove `o-tab-size` property.

### 4. Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

I install [**Autoprefixer**](https://github.com/sindresorhus/sublime-autoprefixer) Sublime Text package use Package Control.

For example, I have `test.css` file:

```css
pre
{
    white-space: pre-wrap;
    -moz-tab-size: 4;
      -o-tab-size: 4;
         tab-size: 4;
}
```

In `test.css` file I press <kbd>Ctrl+Shift+P</kbd> → `Autoprefix CSS` → I get result:

```css
pre
{
    white-space: pre-wrap;
    -moz-tab-size: 4;
         tab-size: 4;
}
```

### 5. Environment

**Operating system and version:**
Windows 32-bit 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by ai** [comment]
Thanks for good issue report with all details :).

I think problems is with your browers list. Maybe Sublime plugin has different defaults without old Opera?

For example, [online demo](http://autoprefixer.github.io/) outputs is (don’t forget to change browsers to `defaults`):

```css
pre
{
    white-space: pre-wrap;
         -moz-tab-size: 4;
           -o-tab-size: 4;
              tab-size: 4;
}
```
