### ISSUE TITLE
Autoprefixer never outputs -webkit-flex

### ISSUE THREAD

**Issue by benjigreig** [postcss/autoprefixer#766]
We've been conducting a lengthy tests to narrow down an issue which is having an effect on iOS 7-8 users predominantly in one of our new projects. It has to do with `display: flex`. What's missing in action is webkit prefixes for post 2009 flexbox.

The following browser versions require the `-webkit` vendor prefix for flexbox post 2009 to work

> iOS 7.1-8.4
> Chrome v21-28
> Safari 6.1-8

I've been pulling my hair out over the weekend and today trying to isolate the issue and this is where I've come to.

**Input CSS**
```css
.flex-test {
    display: flex;
    flex-wrap: wrap-reverse;
    justify-content: space-between;
    width: 100%;
}

.flex-text .child {
    flex: 1;
}

.flex-text .child.noflex {
    flex: none;
}
```

**Autoprefixer configuration**
```javascript
autoprefixer({
	browsers: ['> 1%', 'last 3 versions', 'Firefox >= 20', 'iOS >=7']
})
```

**Output with above config (including 2009 flexbox model)**
```css
.flex-test {
    display:-webkit-box;
    display:-ms-flexbox;
    display:flex;
    -ms-flex-wrap:wrap-reverse;
    flex-wrap:wrap-reverse;
    -webkit-box-pack:justify;
    -ms-flex-pack:justify;
    justify-content:space-between;
    width:100%
}

.flex-text .child {
    -webkit-box-flex:1;
    -ms-flex:1;
    flex:1
}

.flex-text .child.noflex {
    -webkit-box-flex:0;
    -ms-flex:none;
    flex:none
}
```

**Output with above config & "no-2009" flag**
```css
.flex-test {
    display:-ms-flexbox;
    display:flex;
    -ms-flex-wrap:wrap-reverse;
    flex-wrap:wrap-reverse;
    -ms-flex-pack:justify;
    justify-content:space-between;
    width:100%
}

.flex-text .child {
    -ms-flex:1;
    flex:1
}

.flex-text .child.noflex {
    -ms-flex:none;
    flex:none
}
```

**What we're expecting (with "no-2009" flag)**
```css
.flex-test {
    display:-ms-flexbox;
    display:-webkit-flex;
    display:flex;
    -ms-flex-wrap:wrap-reverse;
    -webkit-flex-wrap:wrap-reverse;
    flex-wrap:wrap-reverse;
    -ms-flex-pack:justify;
    -webkit-justify-content:space-between;
    justify-content:space-between;
    width:100%
}

.flex-text .child {
    -ms-flex:1;
    -webkit-flex:1;
    flex:1
}

.flex-text .child.noflex {
    -ms-flex:none;
    -webkit-flex:none;
    flex:none
}
```

Any help resolving this would be greatly appreciated.

**Comment by ai** [comment]
I tested your input example in [online demo](http://autoprefixer.github.io/ru/) and got:

```css
.flex-test {
	display: -webkit-box;
	display: -webkit-flex;
	display: -moz-box;
	display: -ms-flexbox;
	display: flex;
	-webkit-flex-wrap: wrap-reverse;
	    -ms-flex-wrap: wrap-reverse;
	        flex-wrap: wrap-reverse;
	-webkit-box-pack: justify;
	-webkit-justify-content: space-between;
	   -moz-box-pack: justify;
	    -ms-flex-pack: justify;
	        justify-content: space-between;
	width: 100%;
}

.flex-text .child {
	-webkit-box-flex: 1;
	-webkit-flex: 1;
	   -moz-box-flex: 1;
	    -ms-flex: 1;
	        flex: 1;
}

.flex-text .child.noflex {
	-webkit-box-flex: 0;
	-webkit-flex: none;
	   -moz-box-flex: 0;
	    -ms-flex: none;
	        flex: none;
}
```

So it is a environment problem, not inside Autoprefixer itself.
