### ISSUE TITLE
`grid: false` does not disable adding of `-ms-grid` to `@supports`

### ISSUE THREAD

**Issue by sgomes** [postcss/autoprefixer#778]
The following input CSS:

```css
@supports (display: grid) {
  .foo {
    display: grid;
  }
}
```

produces the following result with the `grid: false` option passed to autoprefixer:

```css
@supports ((display: -ms-grid) or (display: grid)) {
  .foo {
    display: grid; } }
```

This is unexpected and leads to inconsistent prefixing. Setting `grid: false` should in my mind disable it everywhere, including `@supports` rules.
