### ISSUE TITLE
Grayscale weird behaviour in firefox

### ISSUE THREAD

**Issue by anshulshukla** [postcss/autoprefixer#791]
I am using` filter : grascale(1)` for grayouting the div. My structure is like this : 
```
 .a {
  .b {
   filter : grayscale(1);
}
}
```

Result I am expecting is :

```
 .a {
  .b {
   filter: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg"><filter id="filter"><feColorMatrix type="matrix" color-interpolation-filters="sRGB" values="0.2126 0.7152 0.0722 0 0 0.2126 0.7152 0.0722 0 0 0.2126 0.7152 0.0722 0 0 0 0 0 1 0" /></filter></svg>#filter');
	-webkit-filter: grayscale(1);
	filter: grayscale(1);
}
}
```

but actual result I am getting is : 

```
 .a {

filter: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg"><filter id="filter"><feColorMatrix type="matrix" color-interpolation-filters="sRGB" values="0.2126 0.7152 0.0722 0 0 0.2126 0.7152 0.0722 0 0 0.2126 0.7152 0.0722 0 0 0 0 0 1 0" /></filter></svg>#filter');
  .b {
   filter: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg"><filter id="filter"><feColorMatrix type="matrix" color-interpolation-filters="sRGB" values="0.2126 0.7152 0.0722 0 0 0.2126 0.7152 0.0722 0 0 0.2126 0.7152 0.0722 0 0 0 0 0 1 0" /></filter></svg>#filter');
	-webkit-filter: grayscale(1);
	filter: grayscale(1);
}
}
```

Any Idea what is happening here ?

`firefox version - 51.0.1`

**Comment by ai** [comment]
1. Autoprefixer doesn't insert `url` hack. It does other PostCSS tool.
2. Autoprefixer and other polyfill tools (like that PostCSS plugin, that insert `url`), should be run sheet `postcss-nested` or any other preprocessor.

**Comment by ai** [comment]
@iamvdo I think it is for you.

**Comment by anshulshukla** [comment]
It looks like issue with postcss-nested, I am using  ` "postcss-nested": "1.0.0"`.

**Comment by ai** [comment]
PostCSS plugin debug is very easy.

Send this input:

```css
.a {
  .b {
   filter: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg"><filter id="filter"><feColorMatrix type="matrix" color-interpolation-filters="sRGB" values="0.2126 0.7152 0.0722 0 0 0.2126 0.7152 0.0722 0 0 0.2126 0.7152 0.0722 0 0 0 0 0 1 0" /></filter></svg>#filter');
	-webkit-filter: grayscale(1);
	filter: grayscale(1);
}
}
```

To `postcss-nested` **only** (disable all other plugins).
