### ISSUE TITLE
@page at-rule disappears after prefixing

### ISSUE THREAD

**Issue by nDmitry** [postcss/autoprefixer#8]
This code:

``` css
@page {
    margin: .5cm;
}
```

transforms to this (without the at-rule):

```
 {
   margin: .5cm;
}
```

More about @page: https://developer.mozilla.org/en-US/docs/CSS/@page
