### ISSUE TITLE
Certain CSS lines are ignored

### ISSUE THREAD

**Issue by HandySam** [postcss/autoprefixer#801]
Hi

I have found an issue with the latest version (6.7.7) of this plugin. 

My project uses Gulp for build automation and I use the gulp-autoprefixer package, which requires this package. When using the latest version 6.7.7 of autoprefixer, the CSS property "-webkit-box-orient" is being left out. No matter where I place the property, it is not present in the final CSS file. 

Version 6.4.0 does not have this issue. 

By switching between version 6.4.0 and 6.7.7, I am able to reproduce this reliably. 

Kind regards

**Comment by ai** [comment]
1. Please use gulp-postcss as official way to use Autoprefixer.

**Comment by ai** [comment]
2. If you need old webkit flexbox, set old Safari into `browserslist` config. Autoprefixer remove this prefix, because modern (default browsers list) Safari doesn't need it anymore.

https://github.com/ai/browserslist

**Comment by HandySam** [comment]
Currently my browserslist is `['last 2 Chrome versions', 'last 3 iOS versions']`. 

I will look into using postcss.

**Comment by ai** [comment]
@HandySam https://github.com/postcss/autoprefixer#gulp

You already uses PostCSS, it just hidden inside `gulp-autoprefixer`.

**Comment by ai** [comment]
@HandySam according Can I Use `last 3 iOS versions` doesn’t need `-webkit-` for flexbox http://caniuse.com/#feat=flexbox

**Comment by HandySam** [comment]
I am using the old flexbox `display: -webkit-box` to have `-webkit-line-clamp`, which needs `-webkit-box-orient: vertical;`. This is why a regular flexbox is not desired in this specific use-case.

**Comment by ai** [comment]
@HandySam could you show your input CSS, output CSS and expected output CSS. I think I missed how you can use `display: -webkit-box` — in Autoprefixer you should not write prefixes.

**Comment by HandySam** [comment]
```css 
.some-class {
  position: relative;
  display: -webkit-box;
  width: 100%;
  vertical-align: middle;
  text-align: center;
  white-space: normal;
  word-wrap: break-word;
  overflow: hidden;
  text-overflow: ellipsis;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 3;
}
```
To my understanding, it is not possible to use line-clamp with a regular flexbox.
