### ISSUE TITLE
[css-grid]min-content/max-content prefix in Safari

### ISSUE THREAD

**Issue by yisibl** [postcss/autoprefixer#803]
input:

```css
.foo {
     grid-template-columns: minmax(100px, min-content);
}
```

output:

```css
.foo {
     -ms-grid-columns: minmax(100px, min-content);
         grid-template-columns: minmax(100px, min-content);
}
```

These properties just remove the prefix in https://trac.webkit.org/changeset/213831 , but I'm not sure which version of Safari.

@mrego Can you help me?

http://caniuse.com/#feat=css-grid
