### ISSUE TITLE
Optimized CSS gradients support

### ISSUE THREAD

**Issue by yisibl** [postcss/autoprefixer#815]
CSS gradients has several stages of syntax, Autoprefixer will generate the current prefix period does not support the property, but in fact older browsers do not support them, we should select the special syntax.

# CSS image 4 color interpolation hint(aka Midpoints)
  * Webkit: https://bugs.webkit.org/show_bug.cgi?id=137171
 * Chrome: https://crbug.com/420527
 * Firefox:https://bugzilla.mozilla.org/show_bug.cgi?id=1074056
 * Edge: https://msdn.microsoft.com/en-us/library/jj152126(v=vs.85).aspx#Remarks

input: 

```css
.foo {
  background: linear-gradient(red, 30%, blue);

  background: radial-gradient(yellow, 30%, green);
}
```
output(use > 0%):

```css
.foo {
  background: -webkit-gradient(linear, left top, left bottom, from(red), color-stop(30%), to(blue)); /* Syntax error */
  background: -webkit-linear-gradient(red, 30%, blue); /* Not support */
  background: -moz-linear-gradient(red, 30%, blue); /* Not support */
  background: -o-linear-gradient(red, 30%, blue); /* Not support */
  background: linear-gradient(red, 30%, blue);

  background: -webkit-radial-gradient(yellow, 30%, green); /* Not support */
  background: -moz-radial-gradient(yellow, 30%, green); /* Not support */
  background: -o-radial-gradient(yellow, 30%, green); /* Not support */
  background: radial-gradient(yellow, 30%, green);
}
```

## Edge offsets `<position>`

  **I'm not sure if there is a version that supports both prefix and "edge offsets `<position>`"**

input: 

```css
.foo {
  background: radial-gradient(circle at bottom right 10px , yellow, green);
}
```

output(use > 0%):

```css
.foo {
  background: -webkit-radial-gradient(bottom right 10px, circle , yellow,  green); /* Not support */
  background: -moz-radial-gradient(bottom right 10px, circle , yellow, green);  /* Not support */
  background: -o-radial-gradient(bottom right 10px, circle , yellow, green); /*  Not support */
  background: radial-gradient(circle at bottom right 10px , yellow, green);
}
```

## at syntax (final standard syntax)

 * https://developer.mozilla.org/en-US/docs/Web/CSS/radial-gradient#Browser_compatibility

`<length>` at `<position>`

input: 

```css
.foo {
  background: radial-gradient(60px at 50px 20px, yellow, green);
  background: radial-gradient(60px 10px at 50px 20px, yellow, green);
}
```

output(use > 0%):

```css
.foo {
  background: -webkit-radial-gradient(50px 20px, 60px, yellow, green); /* Not support */
  background: -moz-radial-gradient(50px 20px, 60px, yellow, green);  /* Not support */
 /* Opera 11.10 and 11.50 also refers to only having support for linear gradients */
  background: -o-radial-gradient(50px 20px, 60px, yellow, green); /* Not support */
  background: radial-gradient(60px at 50px 20px, yellow, green);
  background: -webkit-radial-gradient(60px 10px at 50px 20px, yellow, green); /* Not support */
  background: -moz-radial-gradient(60px 10px at 50px 20px, yellow, green); /* Not support */
  /* Opera 11.10 and 11.50 also refers to only having support for linear gradients */
  background: -o-radial-gradient(60px 10px at 50px 20px, yellow, green); /* Not support */
  background: radial-gradient(60px 10px at 50px 20px, yellow, green);
}
```

These historical syntax is really a headache, we should not generate an error if the autoprefixer cannot be returned to the correct value.

At the same time, I strongly recommend adding an option to turn off `-webkit-gradient()` generation,because the grammar is too old, we don't usually use it.

In addition, the old syntax will lead to the collapse of Safari([Bug](https://twitter.com/jieorlin/status/851397718069182464)) 😭 .

See also: [Special CSS radial-gradient() value test](http://codepen.io/yisi/pen/JWgOmW)

## CSS image 4 [multiple color-stop positions](https://drafts.csswg.org/css-images-4/#color-stop-syntax) 
    linear-gradient(45deg, #f06,  #f06 50%, #f06 75%, yellow)

can be written as  

    linear-gradient(45deg, #f06, #f06 50% 75%, yellow)

This is a syntax sugar, currently only Chrome Canary support(See [bug 707047](https://bugs.chromium.org/p/chromium/issues/detail?id=707047)). 

Autoprefixer can be easily supported, of course, I can also develop a plugin to deal with this syntax, and then Autoprefixer gives warning tips.

## Premultiplied color-space

```css
.foo {
  background: linear-gradient(90deg, red, transparent, blue)
}
```

![image](https://cloud.githubusercontent.com/assets/2784308/25039219/19784d3c-2135-11e7-9a7c-8dbf7773269e.png)

Spec: https://drafts.csswg.org/css-images-3/#example-15b97eed
Solution: Use https://github.com/gilmoreorless/postcss-gradient-transparency-fix
