### ISSUE TITLE
Question: The property `-webkit-box-orient` seems be filtered by autoprefixer?

### ISSUE THREAD

**Issue by blade254353074** [postcss/autoprefixer#833]
autoprefixer v7.0.0
postcss-loader 1.3.3

input:
```scss
@mixin double-line () {
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  word-break: break-all;
  overflow: hidden;
  text-overflow: ellipsis;
}
```
output:
```css
.double-line {
  display: -webkit-box;
  -webkit-line-clamp: 2;
  word-break: break-all;
  overflow: hidden;
  text-overflow: ellipsis;
}
```
