### ISSUE TITLE
appearance support?

### ISSUE THREAD

**Issue by ianstormtaylor** [postcss/autoprefixer#84]
i find myself doing this a lot:

``` css
button {
  -webkit-appearance: none;
  -moz-appearance: none;
  appearance: none;
}
```

would be awesome to have appearance baked in, i think that's the last thing i worry about prefixing nowadays ;p
