### ISSUE TITLE
The option `browsers: ['not ie < 8']` not works

### ISSUE THREAD

**Issue by aleen42** [postcss/autoprefixer#841]
I have set up `postcss` and `autoprefix` to want to build the following CSS code:

```css
.example {
    display: flex;
    transition: all .5s;
    user-select: none;
    background: linear-gradient(to bottom, white, black);
}
```

With the following option:

```js
gulp.src('./test.css')
        .pipe(postcss([autoprefixer({ browsers: ['not ie < 8'] })]))
        .pipe(gulp.dest('./dist'));
```

But it seems not work, and why?

I have also tested with `last 4 versions`, it works! And also why? I am using the newest version of **autoprefixer@7.1.0**
