### ISSUE TITLE
only kept  last rule when I use multiple `linear-gradient`

### ISSUE THREAD

**Issue by zzzzc** [postcss/autoprefixer#843]
### input
```css
.wallet-wrap {
  background: -moz-linear-gradient(top, #000 0%, #ddd 100%);
  background: -webkit-linear-gradient(top, #000 0%,#ddd 100%);
  background: -o-linear-gradient(top, #000 0%,#ddd 100%);
  background: -ms-linear-gradient(top, #000 0%,#ddd 100%);
}
```
### output
```css
.wallet-wrap {
  background: -ms-linear-gradient(top, #000 0%,#ddd 100%);
}
```

### input
```css
.wallet-wrap {
  background: -ms-linear-gradient(top, #000 0%,#ddd 100%);
  background: -moz-linear-gradient(top, #000 0%, #ddd 100%);
  background: -webkit-linear-gradient(top, #000 0%,#ddd 100%);
  background: -o-linear-gradient(top, #000 0%,#ddd 100%);
}
```
### output
```css
.wallet-wrap {
  background: -o-linear-gradient(top, #000 0%,#ddd 100%);
}
```
