### ISSUE TITLE
Number of transitioned properties can change

### ISSUE THREAD

**Issue by zipper** [postcss/autoprefixer#855]
Let's assume following input:
```css
.foo {
    transition: visibility 0s linear 300ms, opacity 300ms ease, transform 600ms ease;
    transition-delay: 900ms, 600ms, 0ms;
}
```
It translates into output (with `last 1 versions` eg.):
```css
.foo {
    transition: visibility 0s linear 300ms, opacity 300ms ease, -webkit-transform 600ms ease;
    transition: visibility 0s linear 300ms, opacity 300ms ease, transform 600ms ease;
    transition: visibility 0s linear 300ms, opacity 300ms ease, transform 600ms ease, -webkit-transform 600ms ease;
    transition-delay: 900ms, 600ms, 0ms;
}
```

That leads to a problem:
1. **The number of transitioned properties has changed** (for Chrome). Browsers will use the last `transition` property defined, which has 4 properties. But there are only 3 defined in `transition-delay`, so the fourth will use `900ms`, which is inconvenient and potentially unexpected.
2. In case of transitioning, even the latest desktop Chrome will use `-webkit-transform` property instead of `transform`, respectively it uses its delay - 900ms instead of 0ms expected. As a result, transition in example is never seen as the element gets hidden (using visibility and opacity) before it starts.

The solution for css author is quite straightforward - merge `transition-delay` into `transition`. But it might not always be possible (eg. because of css generated by pre-processors). Here the reason was just to make it more transparent. Moreover, the `transition-delay` could even be defined in different selector.

Could this be prevented without modifying input css?

See https://jsfiddle.net/sxfqrr0f/4/ - on mouse in (don't mind the mouse out), the green reacts as expected, red doesn't.
