### ISSUE TITLE
justify-self IE11

### ISSUE THREAD

**Issue by veke** [postcss/autoprefixer#856]
In grid css layout justify-self is not producing needed -ms-grid-column-align property

**Comment by ai** [comment]
Can you show input, output and expected output CSS? :)

**Comment by veke** [comment]
Well if you have last 2 versions for example and try:
```
any {
    justify-self: center;
    align-self: center;
}
=> 
any {
    -ms-flex-item-align: center;
    -ms-grid-row-align: center;
    align-self: center;
    justify-self: center;
}
```
It is missing ```-ms-grid-column-align: center;``` which centers grid column item horizontally.

**Comment by ai** [comment]
Strange, it works in tests: https://github.com/postcss/autoprefixer/blob/master/test/cases/grid.out.css#L45

Can you try different `justify-self` values or try to put `display: grid` to rule to find source of issue?

**Comment by veke** [comment]
Different values did not produce anything. Display grid removed ```ms-flex-item-align: center;```

**Comment by ai** [comment]
You want Grid or Flexbox centering?

**Comment by veke** [comment]
grid

**Comment by ai** [comment]
Since Grid is disabled by default, this task is low priority. I will look on Friday.

Also put your build tool config and Autoprefixer version (we fixed issues with Grid in 7.0, be sure that you use last version).

**Comment by veke** [comment]
Just checked version. It seems that angular cli latest (1.2.0)is using ```"autoprefixer": "^6.5.3"```

**Comment by veke** [comment]
I think I update and try again :D

**Comment by veke** [comment]
No help, Installed 7.1.1 but no luck with ms-flex-item-align: center;

**Comment by veke** [comment]
"Since Grid is disabled by default, this task is low priority. I will look on Friday."
 - Thanks for your help

**Comment by ai** [comment]
Did you enabled Grids after migration to 7.0?

In 7.0 IE prefixes for Grids are disabled by default

**Comment by veke** [comment]
That was it. I updated angular cli's autoprefixer to latest and added { grid: true }.
Not it added missing ```-ms-grid-column-align: center; ```
Now I need to find a way to configure autoprefixer settings in angular cli.

**Comment by veke** [comment]
@ai Closing this. Was not a bug but config issue with angular cli.
Thank you.

**Comment by Dan503** [comment]
In the latest version of Autoprefixer, you can enable/disable CSS Grid translations using a control comment.

`/* autoprefixer grid: on/off/autoplace */`

`autoplace` will allow for limited autoplacement support.

**Comment by dereklin** [comment]
I am using @angular/cli 7.1.0.

```
/* autoprefixer grid: on*/
```
works for most things but not addig -ms-grid-column-align: center;

```
/* autoprefixer grid: autoplace */
```
doesn't work.  I also tried putting grid: on on the top level and grid: autoplace above just-self

**Comment by nagman** [comment]
I'm using autoprefixer in `create-react-app` v16.9, and `justify-self` doesn't output the `-ms-grid-column-align` property.

I've added `AUTOPREFIXER_GRID=no-autoplace` to my `build` script, and it does add prefixes to every grid property for IE, **except** for `justify-self` (whereas `align-self` does produce `-ms-grid-row-align`).

**Comment by nagman** [comment]
Oh! I got it! My bad.

Actually I was using `justify-self: flex-start`. But IE doesn't know `flex-start` and autoprefixer doesn't convert `flex-start` to `start`.  
So when you set `justify-self`, you must use only one of the following: `start`, `end`, `center` and `stretch`.

They are all valid values. I tried with `left` and `right` but that doesn't work. Will stick to those 4 values for now.

**But!** I've found another bug relative to `justify-self` **and** `align-self`: if your element is a flex container (`display: flex`) and has a `justify-self` and/or an `align-self`, none of those are prefixed.  
If I set `display: block` on my element, then the two other properties are prefixed.  
I tried with `display: inline-flex` but same issue.

Apparently, autoprefixer thinks that the `justify-self` and `align-self` properties apply for `flex` (and IE does support those properties with flex) so it doesn't add prefixes. But my element is a child of a grid container and is itself a flex container, and autoprefixer doesn't understand that.

**Comment by Dan503** [comment]
Can you provide a small code sample showing input and output?

**Comment by nagman** [comment]
Input:
```css
.wrapper {
  display: grid;
  grid-template-rows: 1fr;
  grid-template-columns: 1fr 1fr 1fr;
}

.child {
  grid-row: 1;
  grid-column: 3;
  align-self: center;
  justify-self: end;

  display: flex;
  align-items: center;
}
```

Current output:
```css
.wrapper {
  display: -ms-grid;
  display: grid;
  -ms-grid-rows: 1fr;
  grid-template-rows: 1fr;
  -ms-grid-columns: 1fr 1fr 1fr;
  grid-template-columns: 1fr 1fr 1fr;
}
.child {
  -ms-grid-row: 1;
  grid-row: 1;
  -ms-grid-column: 3;
  grid-column: 3;
  align-self: center;
  justify-self: end;

  display: flex;
  align-items: center;
}
```

Expected output:
```css
.wrapper {
  display: -ms-grid;
  display: grid;
  -ms-grid-rows: 1fr;
  grid-template-rows: 1fr;
  -ms-grid-columns: 1fr 1fr 1fr;
  grid-template-columns: 1fr 1fr 1fr;
}
.child {
  -ms-grid-row: 1;
  grid-row: 1;
  -ms-grid-column: 3;
  grid-column: 3;
  -ms-grid-row-align: center; /* this */
  align-self: center;
  -ms-grid-column-align: end; /* and that */
  justify-self: end;

  display: flex;
  align-items: center;
}
```

**Comment by Dan503** [comment]
@nagman I figured out a work around for the issue.

Instead of this:
```css
.child {
  align-self: center;
  justify-self: end;

  display: flex;
  align-items: center;
}
```

Do this:

```css
.child {
  display: grid;
  align-self: center;
  justify-self: end;

  display: flex;
  align-items: center;
}
```

`display: grid;` will get overridden in the browser so it will still display as flex. It tricks Autoprefixer into thinking it is a grid container instead of a flex container.

That is just a work around until the core issue is fixed.
