### ISSUE TITLE
Not inserting -webkit- for transform: translate3d on iOS8

### ISSUE THREAD

**Issue by nabchar** [postcss/autoprefixer#875]
I've noticed that the autoprefixer seems to be having issues inserting `-webkit-` for `transform: translate3d` for devices running iOS 8.

I thought it might be related to the fact that iOS8 is not supported by default, so I added the following into my package.json:
```js
  "browserlist": [
      "> 1%",
      "last 2 versions",
      "iOS 8"
  ]
```
That fix didn't seem to have an effect. However, it does seem that autoprefixer is inserting the `-webkit-` prefix for other CSS3 properties though, so I'm not sure why it is skipping over it for this one.

**Comment by ai** [comment]
Can you add input, output and expected output

**Comment by nabchar** [comment]
Input: `transform: translate3d(0, 0, 0);`
Output: `transform: translate3d(0, 0, 0);`
Expected Output: `-webkit-transform: translate3d(0, 0, 0);`

Thanks.

**Comment by ai** [comment]
@nabchar input:

```css
.foo {
  transform: translate3d(0, 0, 0);
}
```

output

```css
.foo {
  transform: translate3d(0, 0, 0);
}
```

expected output

```css
.foo {
  -webkit-transform: translate3d(0, 0, 0);
  transform: translate3d(0, 0, 0);
}
```

or:

```css
.foo {
  -webkit-transform: translate3d(0, 0, 0);
}
```

**Comment by ai** [comment]
I checked your input and browsers on [online demo](http://autoprefixer.github.io/) and got:

```css
.foo {
  -webkit-transform: translate3d(0, 0, 0);
  transform: translate3d(0, 0, 0);
}
```

Seems like you have the problem in the environment. Maybe webpack CSS minifier remove prefixes? Try https://github.com/zoobestik/csso-webpack-plugin
