### ISSUE TITLE
Advice handling transition-property errors.

### ISSUE THREAD

**Issue by colshacol** [postcss/autoprefixer#896]
<img width="1140" alt="screen shot 2017-09-04 at 2 31 30 am" src="https://user-images.githubusercontent.com/19484365/30016097-3ec0ed98-9119-11e7-924f-266ff24570c8.png">

I've Googled enough to find the various issues filed pertaining to this over the years. I know that the general advice is just not to use `transition-*` in favor of the `transition` shorthand.

That said, I am working on overhauling an enterprise project that is three years old. There are currently 914 instances of `transition-property`, and from what I have seen, each one has the same siblings, such as:

```css
.example {
        transition-duration: 100ms;
        transition-property: font-size, color, padding;
        transition-timing-function: cubic-bezier(0.86, 0, 0.07, 1);
}
```

Needless to say, I probably won't be allotted the bandwidth to go through and replace each one with the correct `transition` shorthand, but I _need_ autoprefixer to be a part of this build improvement.

While a solution would be nice (maybe a plugin that will get me past this error?), any advice would be appreciated.

**Comment by ai** [comment]
Write a custom PostCSS plugin and put it before Autoprefixer.

For example, this plugin could translate `transition-property` to `transition`.

**Comment by colshacol** [comment]
I did a `ctrl-f`, "transition-property", replace with "transition", but to no avail. It seems to be failing not only on `transition property`.

By the way. I've seen **you** handling these inquiries for years. Two thumbs up, good sir.

**Comment by ai** [comment]
@colshacol `transition` properties have different values that `transition-property` ;).

You need to replace this:

```css
.example {
        transition-duration: 100ms;
        transition-property: font-size, color, padding;
        transition-timing-function: cubic-bezier(0.86, 0, 0.07, 1);
}
```

to:

```css
.example {
        transition: font-size 100ms cubic-bezier(0.86, 0, 0.07, 1), color 100ms cubic-bezier(0.86, 0, 0.07, 1), padding 100ms cubic-bezier(0.86, 0, 0.07, 1);
}
```
