### ISSUE TITLE
Allow to use hacks with prefixes

### ISSUE THREAD

**Issue by ai** [postcss/autoprefixer#92]
Don’t remove outdated prefixes if there is no any unprefixed version.

``` css
a {
  -moz-transform: scale(.9999);
  transform: scale(.9999);
}

b {
  -moz-transform: scale(.9999);
}
```

will compile to:

``` css
a {
  transform: scale(.9999);
}

b {
  -moz-transform: scale(.9999);
}
```
