### ISSUE TITLE
justify-content: space-evenly

### ISSUE THREAD

**Issue by dilame** [postcss/autoprefixer#926]
This powerful feature is supported by a small number of browsers. The closest well-supported analogue is justify-content: space-around. I think autoprefixer should turn this 
```css
.class {
  justify-content: space-evenly;
}
```
to this
```css
.class {
  justify-content: space-around;
  justify-content: space-evenly;
}
```
or even this

```scss
.class {
  justify-content: space-around;
  @supports (justify-content: space-evenly){
    justify-content: space-evenly;
  }
}
```
