### ISSUE TITLE
gradient / -webkit-gradient

### ISSUE THREAD

**Issue by strarsis** [postcss/autoprefixer#942]
Autoprefixer doesn't transform `gradient`, when used with `mask-image` to `-webkit-gradient`.
Without `-webkit-` on `gradient` the mask will not work in Chrome, Firefox and Safari.

Input:
```css
.test {
        mask-image: gradient(linear, left top, left bottom, from(rgba(0,0,0,1)), to(rgba(0,0,0,0)));
}
````

Output:
```css
.test {
        -webkit-mask-image: gradient(linear, left top, left bottom, from(rgba(0,0,0,1)), to(rgba(0,0,0,0)));
                mask-image: gradient(linear, left top, left bottom, from(rgba(0,0,0,1)), to(rgba(0,0,0,0)));
}
````

Expected (working in browsers):
```css
.test {
        -webkit-mask-image: -webkit-gradient(linear, left top, left bottom, from(rgba(0,0,0,1)), to(rgba(0,0,0,0)));
                mask-image:         gradient(linear, left top, left bottom, from(rgba(0,0,0,1)), to(rgba(0,0,0,0)));
}
````

Edit: It appears that there are more complex variations of `-webkit-gradient` like with using it `color-stop`.
