### ISSUE TITLE
Autoprefixer for 3 background image values

### ISSUE THREAD

**Issue by nichalko** [postcss/autoprefixer#947]
Hi,

first of all, thanks for the Autoprefixer :)

I got an issue with bg image. This code
`background-image: url("images/overlay.png"), linear-gradient(60deg, rgba(255, 165, 150, 0.5) 5%, rgba(0, 228, 255, 0.35)), url("../../images/bg.jpg");`

will not autoprefix. Neither will it give any warnings.

**Comment by ai** [comment]
https://github.com/postcss/autoprefixer#why-doesnt-autoprefixer-add-prefixes-to-border-radius

Modern browsers don't need prefixes for `linear-gradient`.

I tested this CSS on [online demo](http://autoprefixer.github.io) for old browsers (`> 0%`) and everything works correctly:

```css
a {
  background-image: url("images/overlay.png"), -webkit-linear-gradient(30deg, rgba(255, 165, 150, 0.5) 5%, rgba(0, 228, 255, 0.35)), url("../../images/bg.jpg");
  background-image: url("images/overlay.png"), -moz-linear-gradient(30deg, rgba(255, 165, 150, 0.5) 5%, rgba(0, 228, 255, 0.35)), url("../../images/bg.jpg");
  background-image: url("images/overlay.png"), -o-linear-gradient(30deg, rgba(255, 165, 150, 0.5) 5%, rgba(0, 228, 255, 0.35)), url("../../images/bg.jpg");
  background-image: url("images/overlay.png"), linear-gradient(60deg, rgba(255, 165, 150, 0.5) 5%, rgba(0, 228, 255, 0.35)), url("../../images/bg.jpg");
}
```
