### ISSUE TITLE
`display: grid` and alignment properties 

### ISSUE THREAD

**Issue by jonnitto** [postcss/autoprefixer#953]
If you have `display: grid` and alignment properties (`align-items`, `justify-content`, `align-content`) autoprefixer output the prefixes for `flex` and not for the `grid`. 

### Input:
```css
.foo {
    display: grid;
    align-items: center;
}
```

### Output
```css
.foo {
    display: -ms-grid;
    display: grid;
    -webkit-box-align: center;
    -ms-flex-align: center;
    align-items: center;
}
```

### Expected output
```css
.foo {
    display: -ms-grid;
    display: grid;
    -webkit-align-items: center;
    -ms-grid-row-align: center;
    align-items: center;
}
```
