### ISSUE TITLE
CSS-Grid wrong ms prop values w/ media queries

### ISSUE THREAD

**Issue by pcjmfranken** [postcss/autoprefixer#954]
**Description**
When a container with `display: grid;` changes the `grid-template-areas` property in a media query, children with a `grid-area` property will end up with values for `-ms-grid-row`, `-ms-grid-column` and `-ms-grid-column-span` that correspond to whichever `grid-template-areas` comes first, any other instances are ignored resulting in wrong placement.

**Expected or desired result**
*Depending on whether you consider this a bug, an oversight or a feature request ;)*

Children with a `grid-area` property should be rendered once inside a new media query for each time its parent's `grid` changes with MS values corresponding to these new grid values.

**Example**
I don't know how to add the `grid: true` config option to CodePen's Autoprefixer so unfortunately, you're going to have to try this example locally. [Here's](https://codepen.io/pcjmfranken/pen/rpaeyM) a link to the pen anyway, in case anyone knows.

If you let Autoprefixer transpile the following code you'll notice that the third box will have only received -ms- property values for the 768px media query and that it will still span two columns and be on a second row which no long exists above 1200px.

```html
<div class="container">
  <div class="box boxFirst">First box</div>
  <div class="box boxSecond">Second box</div>
  <div class="box boxThird">Third box</div>
</div>
```

```css
@media screen and (min-width: 768px) {
  .container {
    display: grid;
    grid-template-columns: 1fr 1fr;
    grid-template-rows: auto;
    grid-template-areas:
      "boxFirst boxSecond"
      "boxThird boxThird";
  }
}

@media screen and (min-width: 1200px) {
  .container {
    grid-template-columns: 1fr 1fr 1fr;
    grid-template-rows: auto;
    grid-template-areas:
      "boxFirst boxSecond boxThird";
  }
}

.box { padding: 16px; text-align: center; color: white; font-family: sans-serif; }

.boxFirst { grid-area: boxFirst; background-color: #90afc5;  }
.boxSecond { grid-area: boxSecond; background-color: #2a3132; }
.boxThird { grid-area: boxThird; background-color: #763626; }
```

After transpilation:
```css
.boxThird {
  background-color: background-color: #763626;
  -ms-grid-row: 2;
  -ms-grid-column: 1;
  -ms-grid-column-span: 2;
  grid-area: boxThird;
}
```

Expected after transpilation:
```css
@media screen and (min-width: 768px) {
  .boxThird {
    background-color: background-color: #763626;
    -ms-grid-row: 2;
    -ms-grid-column: 1;
    -ms-grid-column-span: 2;
    grid-area: boxThird;
  }
}

@media screen and (min-width: 1200px) {
  .boxThird {
    background-color: background-color: #763626;
    -ms-grid-row: 1;
    -ms-grid-column: 3;
    -ms-grid-column-span: 1;
    grid-area: boxThird;
  }
}
```

**Comment by ai** [comment]
@evgeny-petukhov seems like we need to insert rules to first `parent.type === "atrule || parent.type === "root"`. Do you want to fix it?

**Comment by evgeny-petukhov** [comment]
Yes, I'll fix it. @ai How do you think what tests can cover this situation?
I want to fully support media query, and insert different positions for different media (like the example in issue), but it's not a hotfix, it needs more time.

**Comment by ai** [comment]
You don't need to create another media, just find first at-rule parent and insert new rules there instead of inserting to root

**Comment by ai** [comment]
I will release a fix few hours later, when I will be at home

**Comment by pcjmfranken** [comment]
Thanks for the quick work!

Might be worth mentioning somewhere that this solution requires the elements that you want to position within the grid and their parent, to be located under the same media query and that the `grid-area` property has to be declared again for every child each time you change the grid in the parent.

My test website broke (layout was messed up and autoprefixer warning that grid areas couldn't be found) so I had to figure it out by looking at the changes in the commit.

Here's the code that didn't work, I'm using Stylus with the Rupture plugin for media queries:

```styl
.parent
  display grid
  +above(768px)
    grid-template-columns 1fr 1fr
    grid-template-rows auto auto
    grid-template-areas \
      'boxFirst boxSecond' \
      'boxThird boxThird'
  +above(1200px)
    grid-template-columns 1fr 1fr 1fr
    grid-template-rows auto
    grid-template-areas \
      'boxFirst boxSecond boxThird'

.boxFirst
  grid-area boxFirst

.boxSecond
  grid-area boxSecond

.boxThird
  grid-area boxThird
```

**Comment by ai** [comment]
@pcjmfranken can you show me CSS, which was passed to Autoprefixer and CSS from Autoprefixer?

For example, just add console.log to PostCSS.

**Comment by pcjmfranken** [comment]
I'm sorry, I don't quite understand where to add the console.log to get the CSS that was passed to Autoprefixer (using Webpack).

What I do have for you is the input Styl and the output CSS:

**Input Styl**
```styl
.parent
  display grid
  color white
  text-align center
  +above(768px)
    grid-template-columns 1fr 1fr
    grid-template-rows auto auto
    grid-template-areas \
      'boxFirst boxSecond' \
      'boxThird boxThird'
  +above(1200px)
    grid-template-columns 1fr 1fr 1fr
    grid-template-rows auto
    grid-template-areas \
      'boxFirst boxSecond boxThird'

.boxFirst
  background-color #90afc5
  grid-area boxFirst

.boxSecond
  background-color #2a3132
  grid-area boxSecond

.boxThird
  background-color #763626
  grid-area boxThird
```

**Output CSS**
```css
.parent
  display grid
  color white
  text-align center
  +above(768px)
    grid-template-columns 1fr 1fr
    grid-template-rows auto auto
    grid-template-areas \
      'boxFirst boxSecond' \
      'boxThird boxThird'
  +above(1200px)
    grid-template-columns 1fr 1fr 1fr
    grid-template-rows auto
    grid-template-areas \
      'boxFirst boxSecond boxThird'

.boxFirst
  background-color #90afc5
  grid-area boxFirst

.boxSecond
  background-color #2a3132
  grid-area boxSecond

.boxThird
  background-color #763626
  grid-area boxThird
```

**Warning**
```
warning  in ./src/test/test.styl

autoprefixer: .\src\test\test.styl:14:4: Can not find grid areas: boxFirst, boxSecond, boxThird
```

**Comment by ai** [comment]
Temporary solution: dublicate grid-area inside media-query.

@evgeny-petukhov you will not like this 😅 seems like in case when we didn't find area in media we need do to root, find selector, then create new rule in media query.

**Comment by evgeny-petukhov** [comment]
@ai I wanted to implement this solution but it's not so quick. I am working on it.

**Comment by ai** [comment]
Of course 👍 it doesn't look as quick fix for me too 😅

**Comment by pcjmfranken** [comment]
Sorry for being your CSS Grid party pooper this week 💩

Your temporary solution doesn't work, at least not in the following way:

**Input Styl**
Added `grid-area` for each media query.

```styl
.parent
  display grid
  color white
  text-align center
  +above(768px)
    grid-template-columns 1fr 1fr
    grid-template-rows auto auto
    grid-template-areas \
      'boxFirst boxSecond' \
      'boxThird boxThird'
  +above(1200px)
    grid-template-columns 1fr 1fr 1fr
    grid-template-rows auto
    grid-template-areas \
      'boxFirst boxSecond boxThird'

.boxFirst
  background-color #90afc5
  +above(768px)
    grid-area boxFirst
  +above(1200px)
    grid-area boxFirst

.boxSecond
  background-color #2a3132
  +above(768px)
    grid-area boxSecond
  +above(1200px)
    grid-area boxSecond

.boxThird
  background-color #763626
  +above(768px)
    grid-area boxThird
  +above(1200px)
    grid-area boxThird
```

**Output CSS**
It just repeat-outputs the children without actually transpiling their `grid-area` prop into -ms- props.

```css
.parent {
  display: -ms-grid;
  display: grid;
  color: #fff;
  text-align: center
}

@media only screen and (min-width: 768px) {
  .parent {
    -ms-grid-columns:1fr 1fr;
    grid-template-columns: 1fr 1fr;
    -ms-grid-rows: auto auto;
    grid-template-rows: auto auto;
    grid-template-areas: "boxFirst boxSecond" "boxThird boxThird"
  }
}

@media only screen and (min-width: 1200px) {
  .parent {
    -ms-grid-columns:1fr 1fr 1fr;
    grid-template-columns: 1fr 1fr 1fr;
    -ms-grid-rows: auto;
    grid-template-rows: auto;
    grid-template-areas: "boxFirst boxSecond boxThird"
  }
}

.boxFirst {
  background-color: #90afc5
}

@media only screen and (min-width: 768px) {
  .boxFirst {
    grid-area:boxFirst
  }
}

@media only screen and (min-width: 1200px) {
  .boxFirst {
    grid-area:boxFirst
  }
}

.boxSecond {
  background-color: #2a3132
}

@media only screen and (min-width: 768px) {
  .boxSecond {
    grid-area:boxSecond
  }
}

@media only screen and (min-width: 1200px) {
  .boxSecond {
    grid-area:boxSecond
  }
}

.boxThird {
  background-color: #763626
}

@media only screen and (min-width: 768px) {
  .boxThird {
    grid-area:boxThird
  }
}

@media only screen and (min-width: 1200px) {
  .boxThird {
    grid-area:boxThird
  }
}
```

## Working temporary solution
Repeated parent `grid-template-areas` prop and children's `grid-area` prop for each media query where `grid-template-areas` prop changes.

**Input Styl**
```styl
.parent
  display grid
  color white
  text-align center

.boxFirst
  background-color #90afc5

.boxSecond
  background-color #2a3132

.boxThird
  background-color #763626

+above(768px)
  .parent
    grid-template-columns 1fr 1fr
    grid-template-rows auto auto
    grid-template-areas \
      'boxFirst boxSecond' \
      'boxThird boxThird'

  .boxFirst
    grid-area boxFirst

  .boxSecond
    grid-area boxSecond

  .boxThird
    grid-area boxThird

+above(1200px)
  .parent
    grid-template-columns 1fr 1fr 1fr
    grid-template-rows auto
    grid-template-areas \
      'boxFirst boxSecond boxThird'

  .boxFirst
    grid-area boxFirst

  .boxSecond
    grid-area boxSecond

  .boxThird
    grid-area boxThird
```

**Output CSS**
```css
.parent {
  display: -ms-grid;
  display: grid;
  color: #fff;
  text-align: center
}

.boxFirst {
  background-color: #90afc5
}

.boxSecond {
  background-color: #2a3132
}

.boxThird {
  background-color: #763626
}

@media only screen and (min-width: 768px) {
  .parent {
    -ms-grid-columns:1fr 1fr;
    grid-template-columns: 1fr 1fr;
    -ms-grid-rows: auto auto;
    grid-template-rows: auto auto;
    grid-template-areas: "boxFirst boxSecond" "boxThird boxThird"
  }

  .boxFirst {
    -ms-grid-row: 1;
    -ms-grid-column: 1;
    grid-area: boxFirst
  }

  .boxSecond {
    -ms-grid-row: 1;
    -ms-grid-column: 2;
    grid-area: boxSecond
  }

  .boxThird {
    -ms-grid-row: 2;
    -ms-grid-column: 1;
    -ms-grid-column-span: 2;
    grid-area: boxThird
  }
}

@media only screen and (min-width: 1200px) {
  .parent {
    -ms-grid-columns:1fr 1fr 1fr;
    grid-template-columns: 1fr 1fr 1fr;
    -ms-grid-rows: auto;
    grid-template-rows: auto;
    grid-template-areas: "boxFirst boxSecond boxThird"
  }

  .boxFirst {
    -ms-grid-row: 1;
    -ms-grid-column: 1;
    grid-area: boxFirst
  }

  .boxSecond {
    -ms-grid-row: 1;
    -ms-grid-column: 2;
    grid-area: boxSecond
  }

  .boxThird {
    -ms-grid-row: 1;
    -ms-grid-column: 3;
    grid-area: boxThird
  }
}
```

Hopefully this information helps you reach a solution. May the force be with you.
