### ISSUE TITLE
webpack justify-content can't add prefix

### ISSUE THREAD

**Issue by aiuluna** [postcss/autoprefixer#958]
```css
.nav {
    display: flex;
    padding: 0 vw(35);
    height: vw(100);
    align-items: center;
    justify-content: space-around;
    background-color: #f6f6f6;
    color: #474342;
}
```

and the output:
```css
.footer .nav {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    padding: 0 5.46875vw;
    height: 15.625vw;
    -webkit-box-align: center;
    -ms-flex-align: center;
    align-items: center;
    -ms-flex-pack: distribute;
    justify-content: space-around;
    background-color: #f6f6f6;
    color: #474342;
}
```

why `justify-content` can't use, how to solve this problem?
