### ISSUE TITLE
transition: transform - is result redundant or not?

### ISSUE THREAD

**Issue by victor-homyakov** [postcss/autoprefixer#965]
Running autoprefixer for `android >= 4.4` on following CSS

```css
.example {
    transition: transform 1s ease;
}
```

gives me the result

```css
.example {
    transition: -webkit-transform 1s ease;
    transition: transform 1s ease;
    transition: transform 1s ease, -webkit-transform 1s ease;
}
```

According to https://www.w3.org/TR/css-transitions/#propdef-transition-property unrecognized transition properties should be ignored, so this code looks a bit redundant and could be simplified to

```css
.example {
    transition: transform 1s ease, -webkit-transform 1s ease;
}
```

What do you think?

**Comment by ai** [comment]
Safari has the wrong behavior here and ignores whole `transition` on any unknown property there.

**Comment by victor-homyakov** [comment]
Thanks for the clarification!

**Comment by zhouqicf** [comment]
@ai 
why not export like this:

````css
.example {
    transition: -webkit-transform 1s ease;
    transition: transform 1s ease;
}
````

`transition: transform 1s ease, -webkit-transform 1s ease;` is necessary?

**Comment by ai** [comment]
@zhouqicf we also Chrome and Chromium-based browsers ;). They need both properties.

**Comment by zhouqicf** [comment]
@ai 
Thanks for your reply，
but are there browsers that support `transition: transform 1s ease, -webkit-transform 1s ease;` but not `transition: -webkit-transform 1s ease;transition: transform 1s ease;`? 
Can you tell me which version can reproduce? thank you.

**Comment by victor-homyakov** [comment]
`transition: -webkit-transform 1s ease; transition: transform 1s ease;` does not work as intended - it is effectively equal to `transition: transform 1s ease;` because first rule is overridden by the last one

**Comment by ai** [comment]
@zhouqicf check which Chrome version needs `-webkit-` for `transform`. Here are 6.1 changelog, when we add new `transition` logic https://github.com/postcss/autoprefixer/releases/tag/6.1.0

**Comment by ai** [comment]
> transition: -webkit-transform 1s ease; transition: transform 1s ease; does not work as intended - it is effectively equal to transition: transform 1s ease; because first rule is overridden by the last one

Nope, the second property will override first property only if property value will be recognized in a browser. Since Safari didn’t recognize `transition` with unknown properties, second `transition` will be ignored.

**Comment by ai** [comment]
Here is an example from 6.1 release:

```css
a {
    -webkit-transition: -webkit-filter 1s;    /* UC and old Safari */
    transition: -webkit-filter 1s;            /* Safari */
    transition: filter 1s;                    /* Future version of Safari */
    transition: filter 1s, -webkit-filter 1s; /* Blink and other browsers */
}
```

If you need more details, you can look in closed issues. There were many edge cases.
