### ISSUE TITLE
Plugin not working when selector in sass partial

### ISSUE THREAD

**Issue by fabianMendez** [postcss/autoprefixer#968]
According to [caniuse](https://caniuse.com/#search=::selection) the ::selection pseudo-element is supported by firefox with the -moz- prefix
Can you please add support for it?

Thanks

**Comment by fabianMendez** [comment]
Well, according to http://autoprefixer.github.io, it's already supported, but in my project it's not working.

In my package.json I have:
```json
"autoprefixer": "^7.2.1",
```
and this is the scss:
```scss
body
{
  color: $text-color-dark;
  background-color: $color-secondary;
  
  &::selection
  {
    color: $color-secondary;
    background-color: $text-color-dark;
  }
}
```

When transpiled I just get:
```css
body {
  color: red;
  background-color: #E0E0E0; }
  body::selection {
    color: #E0E0E0;
    background-color: red; }
```
