### ISSUE TITLE
Prefix is not added using the universal selector (*)

### ISSUE THREAD

**Issue by dcardosods** [postcss/autoprefixer#97]
I found a issue with universal selector and the box-sizing property.

``` css
* {
    box-sizing: border-box;
}
```

In the options I used "last 1 version", then -moz prefix shoul be added.
